-- Multi-species batch: dog context record, mouse liver-specific locus, and
-- three genuinely new species (pig, goat, cattle) with rich per-tissue data.
--
-- DOG FINDING: two independent searches (Europe PMC + general web) turned up
-- NO peer-reviewed paper characterizing a genomic safe-harbor locus in dog --
-- this is a real, confirmed gap in the literature, not a search failure. The
-- one directly relevant dog record found (Can f 1 knockout) is NOT a safe
-- harbor -- it is a functional gene knockout -- but it is the first
-- peer-reviewed proof that CRISPR + SCNT + embryo transfer to live dogs works
-- end-to-end, which is directly useful methodological context for this project.

insert into public_safe_harbors_staging
  (species, genome_build, coords, locus_name, evidence_summary, confidence, stability, tissue_context, source_pmid, source_title, reviewed, approved)
values

('Dog', null, null, 'Can f 1 (allergen gene -- NOT a safe harbor, this is a functional knockout target)',
 'Not a safe-harbor record -- included as methodological context, since no dog safe-harbor locus exists in the literature (confirmed by targeted search, see project notes). Canine primary fibroblasts CRISPR-edited with a 1bp insertion/frameshift in Can f 1 exon 1, then used for somatic cell nuclear transfer (SCNT) and embryo transfer -- resulted in two live, healthy female beagle puppies (Sept 2024). Salivary/hair protein absent; skin-prick testing in a sensitized human showed no detectable IgE reaction to the edited dogs'' extracts, vs. robust reactivity to controls. First peer-reviewed proof that the full CRISPR-in-fibroblast -> SCNT -> live-dog pipeline works end to end -- directly relevant methodology for eventually testing a real dog safe-harbor candidate.',
 'high', 'Live, healthy adult dogs produced; phenotype (allergen absence) confirmed stable post-natally', 'Whole organism (fibroblast editing + SCNT + embryo transfer; not tissue-restricted, though the assayed phenotype is salivary/dermal).', '42554239', 'Targeted Genetic Knockout of Can f 1, the Major Allergen in Dogs', true, false),

('Mouse', null, null, 'Albumin (Alb, 3'' end)',
 'Liver-directed AAV-HITI (homology-independent targeted integration) at the 3'' end of the highly transcribed albumin locus, in mouse models of two inherited diseases. Achieved productive integration in ~15% of hepatocytes, reaching therapeutic levels of the systemic transgene protein after a single neonatal treatment. Full-length donor DNA preferentially integrated on nuclease cleavage; despite partial AAV genome integration at the target locus, no gross chromosomal rearrangements or off-target indels were found, and no hepatocellular carcinoma was observed over 1 year of follow-up. Albumin is deliberately chosen because it is expressed at very high levels, so a small reduction in endogenous albumin production from the edited allele is well tolerated.',
 'high', 'No hepatocellular carcinoma or gross rearrangements at 1-year follow-up; therapeutic protein levels sustained after a single neonatal dose', 'Liver / hepatocytes specifically (~15% integration efficiency) -- an intentionally tissue-restricted safe harbor, not a general-purpose one; do not extrapolate to other tissues.', '38897206', 'Safe and effective liver-directed AAV-mediated homology-independent targeted integration in mouse models of inherited diseases', true, false),

('Pig', null, null, 'pH11',
 'Newly characterized porcine ortholog of the human/mouse H11 safe harbor, located on pig chromosome 14q, intergenic between DRG1 and EIF4ENIF1 (3.7kb 3'' of DRG1, 1.3kb 5'' of EIF4ENIF1 -- same gene-pair architecture as the human H11 locus). CMV-GFP knock-in gave 54% efficiency with drug selection (6% without). Expression detected from the 2-4 cell embryo stage and confirmed postnatally across heart, liver, spleen, lung, kidney, and muscle in a cloned piglet generated by somatic cell nuclear transfer, with single-copy, stable hemizygous expression. Germline transmission not yet confirmed -- authors explicitly note more cloned pigs need to be bred to test this.',
 'high', 'Stable single-copy expression from 2-4 cell embryo through postnatal tissues in a live cloned piglet; germline transmission not yet tested', 'Confirmed by direct assay in heart, liver, spleen, lung, kidney, and muscle (broad, not tissue-restricted in this species).', '26381350', 'Highly efficient CRISPR/Cas9-mediated transgene knockin at the H11 locus in pigs', true, false),

('Goat', null, 'chr17:69,574,165-69,575,165', 'H11 (caprine)',
 'Caprine ortholog of the human/mouse H11 locus, intergenic between DRG1 and EIF4ENIF1 (same architecture as human/pig H11). EGFP knock-in gave 9,200-fold higher expression than wild-type control at the cellular level, with 67.86% integration efficiency. No significant change in cell cycle, apoptosis, or proliferation; no change in adjacent gene expression (DRG1, EIF4ENIF1); 100% sequence homology at the target with no off-target events detected. Normal embryonic development; cloned offspring showed wild-type-comparable growth at 12 months.',
 'high', 'No off-target effects; normal development; wild-type-comparable growth through 12 months in cloned offspring', 'Directly assayed across 8 tissues: heart, liver, spleen, lung, kidney, muscle, small intestine, and skin -- broad expression, not tissue-restricted.', '40879839', 'Validation of caprine H11 and the Rosa26 platform for transgene integration via CRISPR-based system: investigations on stable transgene expression and genetic biosafety', true, false),

('Goat', null, 'chr22:17,030,817-17,033,107', 'ROSA26 (caprine)',
 'Caprine ortholog of ROSA26, intergenic between SETD5 and THUMPD3. In the same head-to-head study as caprine H11 (see paired record): EGFP expression was 46,416-fold above wild-type at the cellular level -- higher than H11 in this study (1.25x higher protein expression by Western blot) -- though integration efficiency was lower than H11 (46.15% vs. 67.86%). Notably, expression here was NOT tissue-uniform: heart and skin showed 2-3x higher fluorescence intensity than the other 6 tissues assayed, a clear example of the same locus behaving differently by tissue -- exactly the ATAC/TAD-driven variability this catalog is trying to track. No adverse effects on adjacent gene expression (THUMPD5, SETD5) or development.',
 'high', 'Higher raw expression than H11 in the same study, but at lower integration efficiency; growth normal in cloned offspring', 'Directly assayed across 8 tissues; heart and skin show 2-3x higher expression than liver/spleen/lung/kidney/muscle/small intestine -- NOT tissue-uniform, unlike caprine H11 in the same study.', '40879839', 'Validation of caprine H11 and the Rosa26 platform for transgene integration via CRISPR-based system: investigations on stable transgene expression and genetic biosafety', true, false),

('Cattle', null, null, 'ROSA26 (bovine)',
 'First identification of the bovine ortholog of the mouse ROSA26 locus, via genomic sequence homology. 5''RACE/3''RACE/RT-PCR/qPCR show it encodes a 2-exon long noncoding RNA (lncRNA), expressed ubiquitously and stably across tissues -- the same "quiet lncRNA locus" architecture that makes mouse ROSA26 useful. TALEN-mediated EGFP knock-in gave ubiquitous expression confirmed across cells, embryos, fetuses, and live cattle.',
 'high', 'Ubiquitous, stable expression confirmed across cells, embryos, fetuses, AND live adult cattle -- the most developmentally complete validation among the new livestock entries in this batch', 'Ubiquitous across assayed developmental stages and tissues (not tissue-restricted); exact tissue panel not itemized in the abstract-level source used here.', '29991797', 'Efficient targeted integration into the bovine Rosa26 locus using TALENs', true, false);

-- Genome builds intentionally left null for the pig/goat/cattle coordinate-bearing
-- records above: the specific reference assembly used by each paper was not
-- confirmed from the sources read here (unlike the Drosophila dm3 case, where
-- the assembly was a known, unambiguous fact). Confirm against Sscrofa11.1
-- (pig), ARS1 or newer (goat), and ARS-UCD1.2 (cattle) before using for design.
