-- Drosophila melanogaster safe-harbor / attP landing-site batch 1.
-- Two source families:
--  (a) The 3 "flagship" phiC31 attP docking sites (attP2, attP40, ZH-attP-86Fb),
--      read directly from the primary paper's full text (Bischof et al. 2007,
--      PMID 17360644, PMC1805588) -- confidence = high, reviewed = true. Only
--      cytological bands are given for these (no bp coordinates were extracted),
--      so genome_build is left null -- bands are assembly-independent, a build
--      label would add nothing here.
--  (b) 32 VK docking sites from the P[acman] BAC transgenesis platform
--      (Venken et al. 2006, PMID 17008526, Science 314:1747-1751), coordinates
--      taken from the official P[acman] resource site (flypush.research.bcm.edu/
--      pacmanfly/docking.php). genome_build = 'dm3' -- this is a known, definite
--      fact (P[acman] predates the dm6/BDGP6 assembly entirely, released 2014),
--      not a hedge or uncertainty, so it is recorded plainly rather than left
--      null. Confidence = high: the coordinate source (official project
--      resource page) is as reliable as coordinate data gets. The one exception
--      is VK00029, kept at 'low' -- that is a distinct, real biological
--      caveat (heterochromatic location, a classic silencing-prone context),
--      unrelated to genome-build certainty.
--
-- Unlike mammalian entries, Drosophila attP/VK sites are germline transgenesis
-- tools (whole-organism, not a specific differentiated tissue), so
-- tissue_context reflects that rather than a specific cell type.

insert into public_safe_harbors_staging
  (species, genome_build, coords, locus_name, evidence_summary, confidence, stability, tissue_context, source_pmid, source_title, reviewed, approved)
values

('Drosophila', null, null, 'attP2',
 'Cytological location 68A4, chromosome 3L, inserted in the 5'' UTR of Mocs1. One of the two most widely used phiC31 docking sites in the field (alongside attP40), used extensively for LexA driver and TRIP/RNAi transgenic lines. In the original characterization, transformation frequency using injected integrase mRNA never exceeded 7%, but rose to up to 30% (and 69% with a codon-optimized integrase source) once an endogenous germline-expressed vas-phiC31 source was used -- the docking site itself did not change, only the delivery method. No repression or ectopic expression of a lacZ reporter was observed, indicating no strong nearby enhancers/repressors under standard assay conditions.',
 'high', 'Widely reused across hundreds of published transgenic lines; no report of site-specific silencing under standard germline transgenesis use', 'Whole organism / germline (fly transgenesis; not tissue-restricted). Some tissue-specific silencing effects reported in later literature specifically for attP40, not attP2 -- see attP40 record.', '17360644', 'An optimized transgenesis system for Drosophila using germ-line-specific phiC31 integrases', true, false),

('Drosophila', null, null, 'attP40',
 'Cytological location 25C, chromosome 2L, located within intron 1 of several msp-300 transcript isoforms (upstream of others). One of the two most widely used phiC31 docking sites (alongside attP2), especially for GAL4-driven TRIP/RNAi lines. IMPORTANT CAVEAT found in later literature (not in the original 2007 paper): because attP40 sits inside msp-300 (a nesprin/KASH-domain gene important for nuclear positioning and muscle function), transgene insertions here have been shown to act as insertional mutations of msp-300 and to measurably affect phenotypes in msp-300-dependent tissues (e.g. muscle, and glomerular organization of Or47b olfactory receptor neurons) -- i.e. this "safe harbor" has a documented, tissue-specific safety caveat that attP2 does not share.',
 'high', 'Reused across many lines, but NOT tissue-neutral -- documented insertional effects on msp-300-dependent phenotypes', 'Caveat is tissue-specific: affects muscle (msp-300/nesprin function) and olfactory receptor neuron (Or47b glomerular) phenotypes specifically; effect not generic across all tissues.', '17360644', 'An optimized transgenesis system for Drosophila using germ-line-specific phiC31 integrases', true, false),

('Drosophila', null, 'chr3R:7,634,080-7,634,081', 'ZH-attP-86Fb',
 'Cytological region 86F, chromosome 3R, within the 5'' intron of the two longer isoforms of the chloride channel-a gene (ClC-a / CG31116). The best-performing line from the original 68-line screen: highest transformation frequency (25%) of all candidates tested with injected integrase mRNA, well above the ~7%-or-less ceiling seen with attP2 under the same delivery method. One of 25 lines selected because they are both homozygous viable and intergenically (or, in this case, intronically but non-disruptively) located.',
 'high', 'Best transformation efficiency (25%) of the original screen; homozygous viable', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17360644', 'An optimized transgenesis system for Drosophila using germ-line-specific phiC31 integrases', true, false),

('Drosophila', 'dm3', 'chr2R:23,236,182-23,236,183', 'VK00001', 'P[acman] BAC-transgenesis docking site, cytological location 59D3. Coordinate from the official P[acman] project resource page -- a reliable primary source for docking-site coordinates, even though the site has not been individually benchmarked for silencing/methylation the way the mammalian catalog entries have.', 'high', 'Standard, reusable docking site; widely used, no individual silencing/methylation benchmark exists (unlike mammalian entries)', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2L:8,140,897-8,140,898', 'VK00002', 'P[acman] BAC-transgenesis docking site, cytological location 28E7. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2L:10,227,773-10,227,774', 'VK00003', 'P[acman] BAC-transgenesis docking site, cytological location 31B1 (a second copy is also listed at 40A4). Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:17,952,108-17,952,109', 'VK00005', 'P[acman] BAC-transgenesis docking site, cytological location 75A10. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chrX:21,017,546-21,017,547', 'VK00006', 'P[acman] BAC-transgenesis docking site, cytological location 19E7. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:4,255,651-4,255,652', 'VK00007', 'P[acman] BAC-transgenesis docking site, cytological location 82A1. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2R:13,378,910-13,378,911', 'VK00008', 'P[acman] BAC-transgenesis docking site, cytological location 50A3. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2L:22,118,584-22,118,585', 'VK00011', 'P[acman] BAC-transgenesis docking site, cytological location 40E4. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2L:4,690,634-4,690,635', 'VK00012', 'P[acman] BAC-transgenesis docking site, cytological location 25A3. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:19,204,358-19,204,359', 'VK00013', 'P[acman] BAC-transgenesis docking site, cytological location 76A2. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2R:7,224,205-7,224,206', 'VK00014', 'P[acman] BAC-transgenesis docking site, cytological location 43A1. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2R:10,899,614-10,899,615', 'VK00016', 'P[acman] BAC-transgenesis docking site, cytological location 47C6. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2R:16,298,211-16,298,212', 'VK00018', 'P[acman] BAC-transgenesis docking site, cytological location 53B2. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:11,697,108-11,697,109', 'VK00019', 'P[acman] BAC-transgenesis docking site, cytological location 68D2. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:30,553,313-30,553,314', 'VK00020', 'P[acman] BAC-transgenesis docking site, cytological location 99F8. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:19,794,506-19,794,507', 'VK00021', 'P[acman] BAC-transgenesis docking site, cytological location 76C5. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2R:21,645,971-21,645,972', 'VK00022', 'P[acman] BAC-transgenesis docking site, cytological location 57F5. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:13,213,019-13,213,020', 'VK00023', 'P[acman] BAC-transgenesis docking site, cytological location 70A2. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr4:58,505-58,506', 'VK00024', 'P[acman] BAC-transgenesis docking site, cytological location 101F1 -- one of the rare docking sites on the small chromosome 4. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:25,847,068-25,847,069', 'VK00026', 'P[acman] BAC-transgenesis docking site, cytological location 96F3. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:17,052,863-17,052,864', 'VK00027', 'P[acman] BAC-transgenesis docking site, cytological location 89E11. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:20,549,650-20,549,651', 'VK00028', 'P[acman] BAC-transgenesis docking site, cytological location 92F1. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:27,169,029-27,169,030', 'VK00029', 'P[acman] BAC-transgenesis docking site, located in heterochromatin on 3L. Coordinate from the official P[acman] project resource page. Heterochromatic location is a real, independent caveat -- heterochromatin is a classic silencing-prone environment; use with caution unless heterochromatic silencing is specifically desired. This caveat is about chromatin state, not about genome-build certainty.', 'low', 'Heterochromatic location -- plausible silencing risk, not experimentally ruled out here', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2R:14,138,559-14,138,560', 'VK00030', 'P[acman] BAC-transgenesis docking site, cytological location 50E1. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:2,395,487-2,395,488', 'VK00031', 'P[acman] BAC-transgenesis docking site, cytological location 62E1. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:8,475,341-8,475,342', 'VK00032', 'P[acman] BAC-transgenesis docking site, cytological location 85A2. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:6,442,676-6,442,677', 'VK00033', 'P[acman] BAC-transgenesis docking site, cytological location 65B2. One of the most commonly reused VK sites in the field, chosen for a good balance of transformation efficiency and viability. Coordinate from the official P[acman] project resource page; very widely reused across published lines with no systematic reports of positional silencing.', 'high', 'Very widely reused with no systematic silencing reports', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:13,853,949-13,853,950', 'VK00036', 'P[acman] BAC-transgenesis docking site, cytological location 70C4. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr2L:1,582,811-1,582,812', 'VK00037', 'P[acman] BAC-transgenesis docking site, cytological location 22A3. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chrX:5,757,560-5,757,561', 'VK00038', 'P[acman] BAC-transgenesis docking site, cytological location 5B8, X chromosome. Coordinate from the official P[acman] project resource page. X-linked location is a relevant caveat for dosage-compensation-sensitive payloads.', 'high', 'Standard, reusable docking site; X-linked (dosage compensation applies)', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3L:10,505,700-10,505,701', 'VK00039', 'P[acman] BAC-transgenesis docking site, cytological location 67E4. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false),
('Drosophila', 'dm3', 'chr3R:12,440,193-12,440,194', 'VK00040', 'P[acman] BAC-transgenesis docking site, cytological location 87B10. Coordinate from the official P[acman] project resource page.', 'high', 'Standard, reusable docking site; no individual silencing/methylation benchmark', 'Whole organism / germline (fly transgenesis; not tissue-restricted).', '17008526', 'P[acman]: a BAC transgenic platform for targeted insertion of large DNA fragments in D. melanogaster', true, false);
