-- Backfills tissue_context for staging_insert_batch2.sql records (15 records, all PMID 41511364).

update known_safe_harbors set tissue_context = 'hESCs/iPSCs (robust); silencing risk after differentiation into cardiomyocytes, endothelial cells, myeloid cells, hepatocytes, and Jurkat T cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 19q13.4, intron 1 of PPP1R12C. Robust expression in hESCs/iPSCs without compromising pluripotency, but risk of silencing in cardiomyocytes, endothelial cells, myeloid cells, and hepatocytes, and in Jurkat T cells. Disrupts expression of PPP1R12C, TNNI3, and PPP6R1 (dense gene region). Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'hESCs/iPSCs (robust); silencing risk after differentiation into cardiomyocytes, endothelial cells, myeloid cells, hepatocytes, and Jurkat T cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 19q13.4, intron 1 of PPP1R12C. Robust expression in hESCs/iPSCs without compromising pluripotency, but risk of silencing in cardiomyocytes, endothelial cells, myeloid cells, and hepatocytes, and in Jurkat T cells. Disrupts expression of PPP1R12C, TNNI3, and PPP6R1 (dense gene region). Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'hESCs across multiple differentiation lineages; also used in HEK293 and hTERT-RPE1' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p25.3 (hROSA26), intron 2 of THUMPD3. Stable expression in hESCs across multiple differentiation lineages; no silencing reported; used in HEK293 and hTERT-RPE1. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'hESCs across multiple differentiation lineages; also used in HEK293 and hTERT-RPE1' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p25.3 (hROSA26), intron 2 of THUMPD3. Stable expression in hESCs across multiple differentiation lineages; no silencing reported; used in HEK293 and hTERT-RPE1. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'hiPSCs' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 22q12.2, intergenic region between DRG1 and EIF4ENIF1. Stable expression of several transgenes in hiPSCs without silencing; supports recombinase-mediated cassette exchange (RMCE). Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 22q12.2, intergenic region between DRG1 and EIF4ENIF1. Stable expression of several transgenes in hiPSCs without silencing; supports recombinase-mediated cassette exchange (RMCE). Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'Cell type not specified in evidence text (secondary-review-derived)' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p21.31. Low probability of transgene expression, with gradual decline observed -- weak performance compared to AAVS1/ROSA26/H11/CLYBL. Upregulates flanking genes CCR1 and CCR3. Increases susceptibility to West Nile virus infection (the CCR5-delta32 mutation confers HIV resistance but carries this cost). Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'Cell type not specified in evidence text (secondary-review-derived)' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p21.31. Low probability of transgene expression, with gradual decline observed -- weak performance compared to AAVS1/ROSA26/H11/CLYBL. Upregulates flanking genes CCR1 and CCR3. Increases susceptibility to West Nile virus infection (the CCR5-delta32 mutation confers HIV resistance but carries this cost). Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'hiPSCs and neural stem cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 13q32.1, intron 2 of the CLYBL gene itself. "Robust and superior" expression compared to AAVS1 in hiPSCs and neural stem cells. Minimal disruption of local gene expression (~50x reduction of CLYBL itself). No silencing reported; preserves pluripotency markers and differentiation capacity. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs and neural stem cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 13q32.1, intron 2 of the CLYBL gene itself. "Robust and superior" expression compared to AAVS1 in hiPSCs and neural stem cells. Minimal disruption of local gene expression (~50x reduction of CLYBL itself). No silencing reported; preserves pluripotency markers and differentiation capacity. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'Rhabdomyosarcoma cells; not yet tested in iPSCs' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 4q13.1, intergenic, identified via pseudo-sites of the mCreI homing endonuclease. Robust integration and stable transgene expression for >45 days in rhabdomyosarcoma cells. Supports functional genome editing (Cas9 expression, PAX3/FOXO1 deletion). Not yet evaluated in iPSCs. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'Rhabdomyosarcoma cells; not yet tested in iPSCs' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 4q13.1, intergenic, identified via pseudo-sites of the mCreI homing endonuclease. Robust integration and stable transgene expression for >45 days in rhabdomyosarcoma cells. Supports functional genome editing (Cas9 expression, PAX3/FOXO1 deletion). Not yet evaluated in iPSCs. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'HEK293T, Jurkat, primary T cells, fibroblasts; silencing separately reported in iPSC applications' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 1q31.3, intergenic, discovered via computational screening. Robust, sustained mRuby expression for >90 days in HEK293T and Jurkat; >20 days in primary T cells; >25 days in fibroblasts. Silencing reported in iPSC applications; effect on pluripotency not assessed. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'HEK293T, Jurkat, primary T cells, fibroblasts; silencing separately reported in iPSC applications' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 1q31.3, intergenic, discovered via computational screening. Robust, sustained mRuby expression for >90 days in HEK293T and Jurkat; >20 days in primary T cells; >25 days in fibroblasts. Silencing reported in iPSC applications; effect on pluripotency not assessed. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'HEK293T and Jurkat' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p24.3, intergenic, computational discovery. Performance similar to Rogi1; outperforms AAVS1 and CCR5. "Minimal" effect on the global transcriptional profile in HEK293T and Jurkat. Downregulation of the JUN oncogene observed. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'HEK293T and Jurkat' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p24.3, intergenic, computational discovery. Performance similar to Rogi1; outperforms AAVS1 and CCR5. "Minimal" effect on the global transcriptional profile in HEK293T and Jurkat. Downregulation of the JUN oncogene observed. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'hESCs and iPSCs, through differentiation' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 1p13.2, intergenic. Stable expression in hESCs and iPSCs, with constitutive and inducible promoters. Supports Bxb1-integrase-mediated cassette exchange. Expression maintained for >=15 passages through differentiation. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'hESCs and iPSCs, through differentiation' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 1p13.2, intergenic. Stable expression in hESCs and iPSCs, with constitutive and inducible promoters. Supports Bxb1-integrase-mediated cassette exchange. Expression maintained for >=15 passages through differentiation. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'Neural, hepatic, and cardiac differentiation lineages' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 18q21.31, intergenic. Similar characteristics to Pansio-1; minimal transcriptional effects. No silencing reported; maintained through neural, hepatic, and cardiac differentiation. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'Neural, hepatic, and cardiac differentiation lineages' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 18q21.31, intergenic. Similar characteristics to Pansio-1; minimal transcriptional effects. No silencing reported; maintained through neural, hepatic, and cardiac differentiation. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'Not itemized in evidence text; described as similar profile to Pansio-1/Olonne-18' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 19p13.3, intergenic. Expression profile similar to Pansio-1 and Olonne-18. No impact on expression of the nearest gene (ZNRF4). Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'Not itemized in evidence text; described as similar profile to Pansio-1/Olonne-18' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 19p13.3, intergenic. Expression profile similar to Pansio-1 and Olonne-18. No impact on expression of the nearest gene (ZNRF4). Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'HUDEP2 erythroid progenitors, differentiated into mature erythrocytes' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p22.2, intronic in GOLGA4. Blood-lineage-specific locus. Stable expression in HUDEP2 erythroid progenitors, maintained after differentiation into mature erythrocytes. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'HUDEP2 erythroid progenitors, differentiated into mature erythrocytes' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 3p22.2, intronic in GOLGA4. Blood-lineage-specific locus. Stable expression in HUDEP2 erythroid progenitors, maintained after differentiation into mature erythrocytes. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'HUDEP2 erythroid progenitor cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 6q25.3, intronic in ARID1B. Validated in HUDEP2 cells, stability profile similar to BLD_SHS10. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'HUDEP2 erythroid progenitor cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 6q25.3, intronic in ARID1B. Validated in HUDEP2 cells, stability profile similar to BLD_SHS10. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'Blood progenitors (validation incomplete)' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 8q24.12, associated with TAF2. Experimental validation in blood progenitors still ongoing -- lower confidence than the rest of this list, as this work is stated as incomplete. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'Blood progenitors (validation incomplete)' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 8q24.12, associated with TAF2. Experimental validation in blood progenitors still ongoing -- lower confidence than the rest of this list, as this work is stated as incomplete. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'CAR-CD19 T cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 7q36.1, within the ZNF767P pseudogene. T-cell-specific discovery via ATAC-seq. Durable CAR expression over multiple weeks in CAR-CD19 T cells; preserves the native T-cell receptor; long-term leukemia control demonstrated in vivo. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'CAR-CD19 T cells' where source_pmid = '41511364' and evidence_summary = 'Cytogenetic band 7q36.1, within the ZNF767P pseudogene. T-cell-specific discovery via ATAC-seq. Durable CAR expression over multiple weeks in CAR-CD19 T cells; preserves the native T-cell receptor; long-term leukemia control demonstrated in vivo. Via secondary review, not verified against the primary article.';

-- (batch 2 tissue_context complete -- 15/15 records)
