-- Backfills tissue_context for staging_insert_batch8.sql (12) and batch9.sql (9) -- 21 records.

update known_safe_harbors set tissue_context = 'hiPSC line' where source_pmid = '36495703' and evidence_summary = 'STRAIGHT-IN v2 system (landing pad platform) inserted at AAVS1 in a hiPSC line -- generation of genetically modified lines with ~100% efficiency in ~2-3 weeks.';
update public_safe_harbors_staging set tissue_context = 'hiPSC line' where source_pmid = '36495703' and evidence_summary = 'STRAIGHT-IN v2 system (landing pad platform) inserted at AAVS1 in a hiPSC line -- generation of genetically modified lines with ~100% efficiency in ~2-3 weeks.';

update known_safe_harbors set tissue_context = 'hiPSC line' where source_pmid = '36495703' and evidence_summary = 'Same STRAIGHT-IN v2 system also successfully generated at the CLYBL locus in the same hiPSC line -- same efficiency (~100%) and speed (~2-3 weeks) as AAVS1 in the same study.';
update public_safe_harbors_staging set tissue_context = 'hiPSC line' where source_pmid = '36495703' and evidence_summary = 'Same STRAIGHT-IN v2 system also successfully generated at the CLYBL locus in the same hiPSC line -- same efficiency (~100%) and speed (~2-3 weeks) as AAVS1 in the same study.';

update known_safe_harbors set tissue_context = 'Human iPSC, differentiated into all 3 germ layers' where source_pmid = '33207306' and evidence_summary = 'Tet-on-operator-controlled Cas9 integrated at AAVS1 in human iPSC -- cells remain pluripotent, differentiate into all 3 germ layers, normal karyotype.';
update public_safe_harbors_staging set tissue_context = 'Human iPSC, differentiated into all 3 germ layers' where source_pmid = '33207306' and evidence_summary = 'Tet-on-operator-controlled Cas9 integrated at AAVS1 in human iPSC -- cells remain pluripotent, differentiate into all 3 germ layers, normal karyotype.';

update known_safe_harbors set tissue_context = 'HEK293 cells' where source_pmid = '32470292' and evidence_summary = 'Direct comparison of 3 loci in HEK293 cells: of AAVS1, CCR5, and human ROSA26 tested for eGFP expression, AAVS1 had the highest and most homogeneous expression of the three. Expression at AAVS1 sustained ~3 months without selection. Within AAVS1 itself, promoter ranking: CMV > EF1a > SV40 > TK.';
update public_safe_harbors_staging set tissue_context = 'HEK293 cells' where source_pmid = '32470292' and evidence_summary = 'Direct comparison of 3 loci in HEK293 cells: of AAVS1, CCR5, and human ROSA26 tested for eGFP expression, AAVS1 had the highest and most homogeneous expression of the three. Expression at AAVS1 sustained ~3 months without selection. Within AAVS1 itself, promoter ranking: CMV > EF1a > SV40 > TK.';

update known_safe_harbors set tissue_context = 'HEK293 cells' where source_pmid = '32470292' and evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), CCR5 underperformed AAVS1 in eGFP expression and homogeneity.';
update public_safe_harbors_staging set tissue_context = 'HEK293 cells' where source_pmid = '32470292' and evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), CCR5 underperformed AAVS1 in eGFP expression and homogeneity.';

update known_safe_harbors set tissue_context = 'HEK293 cells' where source_pmid = '32470292' and evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), human ROSA26 underperformed AAVS1 in eGFP expression and homogeneity.';
update public_safe_harbors_staging set tissue_context = 'HEK293 cells' where source_pmid = '32470292' and evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), human ROSA26 underperformed AAVS1 in eGFP expression and homogeneity.';

update known_safe_harbors set tissue_context = 'Cell type not specified for the locus itself; effect detected via teratoma assay in vivo (both cell-type-agnostic and in vivo components)' where source_pmid = '30887735' and evidence_summary = 'Extragenic candidate locus on chromosome 1. Important cautionary finding: the locus itself allowed robust transgene expression, BUT a gene 2Mb away, within the same topologically associated domain (TAD), showed aberrant expression -- despite the distance, 3D TAD organization propagated the effect. The authors conclude Chr1-eGSH is not suitable for therapeutic gene integration despite the locus itself appearing good. Also tested with a suicide-gene safety system (HSV-TK/ganciclovir): sensitive in vitro, but resulting teratomas showed variable degrees of resistance in vivo -- the safety system itself is not reliably guaranteed.';
update public_safe_harbors_staging set tissue_context = 'Cell type not specified for the locus itself; effect detected via teratoma assay in vivo (both cell-type-agnostic and in vivo components)' where source_pmid = '30887735' and evidence_summary = 'Extragenic candidate locus on chromosome 1. Important cautionary finding: the locus itself allowed robust transgene expression, BUT a gene 2Mb away, within the same topologically associated domain (TAD), showed aberrant expression -- despite the distance, 3D TAD organization propagated the effect. The authors conclude Chr1-eGSH is not suitable for therapeutic gene integration despite the locus itself appearing good. Also tested with a suicide-gene safety system (HSV-TK/ganciclovir): sensitive in vitro, but resulting teratomas showed variable degrees of resistance in vivo -- the safety system itself is not reliably guaranteed.';

update known_safe_harbors set tissue_context = 'iPSC derived from fetal liver B progenitors' where source_pmid = '28677529' and evidence_summary = 'Doxycycline-inducible Cas9 confirmed single-copy integrated at AAVS1, in iPSC derived from fetal liver B progenitors. Pluripotency maintained after editing. Robust, specific Cas9 expression after induction, functional gene editing confirmed by T7 endonuclease assay.';
update public_safe_harbors_staging set tissue_context = 'iPSC derived from fetal liver B progenitors' where source_pmid = '28677529' and evidence_summary = 'Doxycycline-inducible Cas9 confirmed single-copy integrated at AAVS1, in iPSC derived from fetal liver B progenitors. Pluripotency maintained after editing. Robust, specific Cas9 expression after induction, functional gene editing confirmed by T7 endonuclease assay.';

update known_safe_harbors set tissue_context = 'Multiple cell types including primary human lymphocytes' where source_pmid = '21857672' and evidence_summary = 'ZFN study at CCR5 and AAVS1: careful cassette design allows robust transgene expression without detectable transcriptional disruption of the target locus or flanking genes, demonstrated across several cell types including primary human lymphocytes.';
update public_safe_harbors_staging set tissue_context = 'Multiple cell types including primary human lymphocytes' where source_pmid = '21857672' and evidence_summary = 'ZFN study at CCR5 and AAVS1: careful cassette design allows robust transgene expression without detectable transcriptional disruption of the target locus or flanking genes, demonstrated across several cell types including primary human lymphocytes.';

update known_safe_harbors set tissue_context = 'Primary human lymphocytes' where source_pmid = '21857672' and evidence_summary = 'Same study: CCR5 also showed robust expression without detectable transcriptional disruption of the locus or flanking genes, using the same careful cassette design, in primary human lymphocytes.';
update public_safe_harbors_staging set tissue_context = 'Primary human lymphocytes' where source_pmid = '21857672' and evidence_summary = 'Same study: CCR5 also showed robust expression without detectable transcriptional disruption of the locus or flanking genes, using the same careful cassette design, in primary human lymphocytes.';

update known_safe_harbors set tissue_context = 'Transformed and primary cells (fibroblasts, hES)' where source_pmid = '20508142' and evidence_summary = 'Founding paper (2010): ZFN targets PPP1R12C (AAVS1) without drug selection, transgenesis efficiency up to 15% in transient transfection, in transformed AND primary cells (fibroblasts, hES). Transgenes (shRNA, small-molecule-responsive cassettes, reporters) show consistent expression and sustained function for over 50 cell generations -- classic reference for "AAVS1 holds up over many generations".';
update public_safe_harbors_staging set tissue_context = 'Transformed and primary cells (fibroblasts, hES)' where source_pmid = '20508142' and evidence_summary = 'Founding paper (2010): ZFN targets PPP1R12C (AAVS1) without drug selection, transgenesis efficiency up to 15% in transient transfection, in transformed AND primary cells (fibroblasts, hES). Transgenes (shRNA, small-molecule-responsive cassettes, reporters) show consistent expression and sustained function for over 50 cell generations -- classic reference for "AAVS1 holds up over many generations".';

update known_safe_harbors set tissue_context = 'Human embryonic stem cells (KhES-1 line)' where source_pmid = '20071742' and evidence_summary = 'Human HPRT locus (KhES-1 hES line) targeted via homologous recombination + Cre-recombinase site-specific integration. Tetracycline/doxycycline-responsive inducible reporter system, with self-renewal and pluripotency maintained. Confirms in human the same type of locus already validated in mouse (Hprt1) in earlier batches.';
update public_safe_harbors_staging set tissue_context = 'Human embryonic stem cells (KhES-1 line)' where source_pmid = '20071742' and evidence_summary = 'Human HPRT locus (KhES-1 hES line) targeted via homologous recombination + Cre-recombinase site-specific integration. Tetracycline/doxycycline-responsive inducible reporter system, with self-renewal and pluripotency maintained. Confirms in human the same type of locus already validated in mouse (Hprt1) in earlier batches.';

update known_safe_harbors set tissue_context = 'hiPSC-CM (cardiomyocytes): ventricular, atrial, and nodal subtypes, 2D and 3D' where source_pmid = '36274846' and evidence_summary = 'Voltage indicator (VSFP, FRET) under the CAG promoter stably expressed at AAVS1 in hiPSC-CM (cardiomyocytes). Functionally validated in ventricular, atrial, and nodal subtypes, in 2D monolayers and in 3D context, with high-throughput optical action-potential recordings.';
update public_safe_harbors_staging set tissue_context = 'hiPSC-CM (cardiomyocytes): ventricular, atrial, and nodal subtypes, 2D and 3D' where source_pmid = '36274846' and evidence_summary = 'Voltage indicator (VSFP, FRET) under the CAG promoter stably expressed at AAVS1 in hiPSC-CM (cardiomyocytes). Functionally validated in ventricular, atrial, and nodal subtypes, in 2D monolayers and in 3D context, with high-throughput optical action-potential recordings.';

update known_safe_harbors set tissue_context = 'iPSCs, through differentiation into multiple lineages' where source_pmid = '34505269' and evidence_summary = 'Genetically encoded fluorescent biosensors (GEFBs) inserted at AAVS1 via CRISPR/Cas HDR, with puromycin selection and negligible off-target editing. Biosensor expression maintained through differentiation into multiple lineages.';
update public_safe_harbors_staging set tissue_context = 'iPSCs, through differentiation into multiple lineages' where source_pmid = '34505269' and evidence_summary = 'Genetically encoded fluorescent biosensors (GEFBs) inserted at AAVS1 via CRISPR/Cas HDR, with puromycin selection and negligible off-target editing. Biosensor expression maintained through differentiation into multiple lineages.';

update known_safe_harbors set tissue_context = 'Patient iPSC, differentiated into hepatocyte-like cells' where source_pmid = '31402115' and evidence_summary = 'Therapeutic AGXT minigene (for primary hyperoxaluria type 1) inserted at AAVS1 in patient iPSC, with no off-target insertions. Robust expression of the (codon-optimized) AGT enzyme confirmed in derived hepatocyte-like cells -- proof of concept for functional correction.';
update public_safe_harbors_staging set tissue_context = 'Patient iPSC, differentiated into hepatocyte-like cells' where source_pmid = '31402115' and evidence_summary = 'Therapeutic AGXT minigene (for primary hyperoxaluria type 1) inserted at AAVS1 in patient iPSC, with no off-target insertions. Robust expression of the (codon-optimized) AGT enzyme confirmed in derived hepatocyte-like cells -- proof of concept for functional correction.';

update known_safe_harbors set tissue_context = 'Human CD34+ hematopoietic stem cells; in vivo mouse model' where source_pmid = '31492863' and evidence_summary = 'Lysosomal iduronidase enzyme (deficient in Mucopolysaccharidosis type I) targeted to CCR5 in human CD34+ hematopoietic stem cells. Enzyme secretion above normal endogenous level, long-term repopulation capacity and multi-lineage differentiation maintained, improvement of biochemical/phenotypic abnormalities in an immunocompromised mouse model of the disease.';
update public_safe_harbors_staging set tissue_context = 'Human CD34+ hematopoietic stem cells; in vivo mouse model' where source_pmid = '31492863' and evidence_summary = 'Lysosomal iduronidase enzyme (deficient in Mucopolysaccharidosis type I) targeted to CCR5 in human CD34+ hematopoietic stem cells. Enzyme secretion above normal endogenous level, long-term repopulation capacity and multi-lineage differentiation maintained, improvement of biochemical/phenotypic abnormalities in an immunocompromised mouse model of the disease.';

update known_safe_harbors set tissue_context = 'Patient iPSC, differentiated hepatocytes; in vivo transplant in NOD/SCID mice' where source_pmid = '29625575' and evidence_summary = 'Full-length F9 cDNA (factor IX) inserted at AAVS1 in iPSC from a hemophilia B patient. No off-target mutations detected by whole-genome sequencing. Derived hepatocytes stably secreted hFIX and survived short-term transplant in NOD/SCID mice.';
update public_safe_harbors_staging set tissue_context = 'Patient iPSC, differentiated hepatocytes; in vivo transplant in NOD/SCID mice' where source_pmid = '29625575' and evidence_summary = 'Full-length F9 cDNA (factor IX) inserted at AAVS1 in iPSC from a hemophilia B patient. No off-target mutations detected by whole-genome sequencing. Derived hepatocytes stably secreted hFIX and survived short-term transplant in NOD/SCID mice.';

update known_safe_harbors set tissue_context = 'Human mesenchymal stem cells (MSCs)' where source_pmid = '28112377' and evidence_summary = 'hFIX inserted at AAVS1 in human mesenchymal stem cells (MSCs) -- a novel cell context compared to other records. Stem cell traits maintained after integration; hFIX effectively expressed in vivo and in vitro, with no significant expression differences between individual clones.';
update public_safe_harbors_staging set tissue_context = 'Human mesenchymal stem cells (MSCs)' where source_pmid = '28112377' and evidence_summary = 'hFIX inserted at AAVS1 in human mesenchymal stem cells (MSCs) -- a novel cell context compared to other records. Stem cell traits maintained after integration; hFIX effectively expressed in vivo and in vitro, with no significant expression differences between individual clones.';

update known_safe_harbors set tissue_context = 'Human CD34+ HSPCs; neutrophils ex vivo; bone marrow in vivo (transplanted mice)' where source_pmid = '26950749' and evidence_summary = 'Targeted integration in human CD34+ HSPCs: up to 58% Venus+ cells with 6-16% human cell engraftment marking in mice. In HSPCs from X-linked chronic granulomatous disease patients, gp91phox transgene at AAVS1 gave ~15% expression and increased NADPH oxidase activity in neutrophils ex vivo; in transplanted mice, 4-11% of human cells in bone marrow expressed gp91phox -- moderate but carefully quantified efficiency.';
update public_safe_harbors_staging set tissue_context = 'Human CD34+ HSPCs; neutrophils ex vivo; bone marrow in vivo (transplanted mice)' where source_pmid = '26950749' and evidence_summary = 'Targeted integration in human CD34+ HSPCs: up to 58% Venus+ cells with 6-16% human cell engraftment marking in mice. In HSPCs from X-linked chronic granulomatous disease patients, gp91phox transgene at AAVS1 gave ~15% expression and increased NADPH oxidase activity in neutrophils ex vivo; in transplanted mice, 4-11% of human cells in bone marrow expressed gp91phox -- moderate but carefully quantified efficiency.';

update known_safe_harbors set tissue_context = 'Human embryonic stem cells (hESC)' where source_pmid = '19680244' and evidence_summary = 'Founding paper (2009): transgene inserted at AAVS1 in hESC to create a robust, drug-inducible overexpression system -- one of the first documented uses of AAVS1 for this purpose, alongside OCT4 and PITX3 reporters (target genes, not safe harbors).';
update public_safe_harbors_staging set tissue_context = 'Human embryonic stem cells (hESC)' where source_pmid = '19680244' and evidence_summary = 'Founding paper (2009): transgene inserted at AAVS1 in hESC to create a robust, drug-inducible overexpression system -- one of the first documented uses of AAVS1 for this purpose, alongside OCT4 and PITX3 reporters (target genes, not safe harbors).';

update known_safe_harbors set tissue_context = 'hESC, differentiated into all 3 germ layers' where source_pmid = '17962703' and evidence_summary = 'A different locus category from AAVS1/ROSA26: endogenous pseudo-attP sites targeted by phiC31 integrase in hESC (not a single named locus, a hotspot profile). GFP under the Oct4 promoter tracked endogenous Oct4 expression (expected, responds to differentiation); GFP under the EF1alpha promoter gave stable, persistent expression. Clones retained differentiation capacity into all 3 germ layers.';
update public_safe_harbors_staging set tissue_context = 'hESC, differentiated into all 3 germ layers' where source_pmid = '17962703' and evidence_summary = 'A different locus category from AAVS1/ROSA26: endogenous pseudo-attP sites targeted by phiC31 integrase in hESC (not a single named locus, a hotspot profile). GFP under the Oct4 promoter tracked endogenous Oct4 expression (expected, responds to differentiation); GFP under the EF1alpha promoter gave stable, persistent expression. Clones retained differentiation capacity into all 3 germ layers.';

-- (batches 8-9 tissue_context complete -- 21/21 records)
