-- Backfills tissue_context for staging_insert_batch3..6.sql records (23 records).

update known_safe_harbors set tissue_context = 'Primary human T cells' where source_pmid = '41121349' and evidence_summary = 'Cytogenetic band 14q11.2. CRISPR/Cas9-mediated integration in primary human T cells -- "robust and consistent" CAR expression driven by the endogenous TRAC promoter. Dual benefit: the insertion disrupts the endogenous TCR, reducing graft-versus-host disease (GVHD) risk in allogeneic products. Sits in a transcriptionally active genomic environment, with no nearby oncogenic elements. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'Primary human T cells' where source_pmid = '41121349' and evidence_summary = 'Cytogenetic band 14q11.2. CRISPR/Cas9-mediated integration in primary human T cells -- "robust and consistent" CAR expression driven by the endogenous TRAC promoter. Dual benefit: the insertion disrupts the endogenous TCR, reducing graft-versus-host disease (GVHD) risk in allogeneic products. Sits in a transcriptionally active genomic environment, with no nearby oncogenic elements. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'CAR-CD19 T cells (murine leukemia model, exact cell source not itemized)' where source_pmid = '41121349' and evidence_summary = 'Chromosome not specified in the review. Anti-CD19 CAR T cells integrated at this locus showed potent antitumor activity in murine models of B-cell acute lymphoblastic leukemia, with efficacy comparable to the TRAC locus. Described as meeting all 8 GSH design criteria (including ncRNA protection and chromatin accessibility). Low confidence due to lack of a specific genomic location. Via secondary review, not verified against the primary article.';
update public_safe_harbors_staging set tissue_context = 'CAR-CD19 T cells (murine leukemia model, exact cell source not itemized)' where source_pmid = '41121349' and evidence_summary = 'Chromosome not specified in the review. Anti-CD19 CAR T cells integrated at this locus showed potent antitumor activity in murine models of B-cell acute lymphoblastic leukemia, with efficacy comparable to the TRAC locus. Described as meeting all 8 GSH design criteria (including ncRNA protection and chromatin accessibility). Low confidence due to lack of a specific genomic location. Via secondary review, not verified against the primary article.';

update known_safe_harbors set tissue_context = 'Mouse macrophages (RAW 264.7); also cerebellum/limb tissue in TRE-loxP intersectional lines' where source_pmid = '38841290' and evidence_summary = 'The Tigre locus (Igs7) used as a safe harbor in mouse macrophages (RAW 264.7) alongside ROSA26 for endogenous fluorescent knock-ins, and in mouse lines with a TRE-loxP system for intersectional expression in cerebellum and limbs. Established as an alternative to ROSA26, not merely theoretical.';
update public_safe_harbors_staging set tissue_context = 'Mouse macrophages (RAW 264.7); also cerebellum/limb tissue in TRE-loxP intersectional lines' where source_pmid = '38841290' and evidence_summary = 'The Tigre locus (Igs7) used as a safe harbor in mouse macrophages (RAW 264.7) alongside ROSA26 for endogenous fluorescent knock-ins, and in mouse lines with a TRE-loxP system for intersectional expression in cerebellum and limbs. Established as an alternative to ROSA26, not merely theoretical.';

update known_safe_harbors set tissue_context = 'Mouse oocytes (Gdf9-driven, oocyte-specific Cas9 line)' where source_pmid = '38523431' and evidence_summary = 'The Hprt1 locus (X-linked) used for single-copy integration of a Cas9 transgene (Gdf9-Cas9) -- chosen precisely because it is a well-defined integration site that "does not influence transgene expression". Genome editing mediated by the transgenic Cas9 was as efficient as exogenous Cas9.';
update public_safe_harbors_staging set tissue_context = 'Mouse oocytes (Gdf9-driven, oocyte-specific Cas9 line)' where source_pmid = '38523431' and evidence_summary = 'The Hprt1 locus (X-linked) used for single-copy integration of a Cas9 transgene (Gdf9-Cas9) -- chosen precisely because it is a well-defined integration site that "does not influence transgene expression". Genome editing mediated by the transgenic Cas9 was as efficient as exogenous Cas9.';

update known_safe_harbors set tissue_context = 'Human HAP1 cells' where source_pmid = '34805274' and evidence_summary = 'In human HAP1 cells, expression of auxin-binding F-box receptor proteins (AFB) from a transgene tends to decline with passaging in the absence of constant antibiotic selection -- does not prevent epigenetic silencing of the transgene even at the AAVS1 locus.';
update public_safe_harbors_staging set tissue_context = 'Human HAP1 cells' where source_pmid = '34805274' and evidence_summary = 'In human HAP1 cells, expression of auxin-binding F-box receptor proteins (AFB) from a transgene tends to decline with passaging in the absence of constant antibiotic selection -- does not prevent epigenetic silencing of the transgene even at the AAVS1 locus.';

update known_safe_harbors set tissue_context = 'hiPSCs, differentiated into cardiomyocytes and endothelium' where source_pmid = '38372898' and evidence_summary = 'Important finding: dCas9-VPR (CRISPRa) targeted to AAVS1 in hiPSCs activates target genes well during pluripotency, but silences after differentiation into cardiomyocytes and endothelium -- in direct CONTRAST with simple fluorescent proteins in the same construct/locus, which remain expressed. Silencing is payload-dependent, not just locus-dependent.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs, differentiated into cardiomyocytes and endothelium' where source_pmid = '38372898' and evidence_summary = 'Important finding: dCas9-VPR (CRISPRa) targeted to AAVS1 in hiPSCs activates target genes well during pluripotency, but silences after differentiation into cardiomyocytes and endothelium -- in direct CONTRAST with simple fluorescent proteins in the same construct/locus, which remain expressed. Silencing is payload-dependent, not just locus-dependent.';

update known_safe_harbors set tissue_context = 'hiPSCs, differentiated into cardiomyocytes and endothelium' where source_pmid = '38372898' and evidence_summary = 'Same comparative study: dCas9-VPR targeted to hROSA26 also silences after differentiation into cardiomyocytes/endothelium, despite working well during pluripotency -- same pattern as AAVS1 and CLYBL in the same study. Reinforces that the payload (dCas9-VPR vs. a fluorescent reporter) is the determining factor for silencing, not the chosen locus.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs, differentiated into cardiomyocytes and endothelium' where source_pmid = '38372898' and evidence_summary = 'Same comparative study: dCas9-VPR targeted to hROSA26 also silences after differentiation into cardiomyocytes/endothelium, despite working well during pluripotency -- same pattern as AAVS1 and CLYBL in the same study. Reinforces that the payload (dCas9-VPR vs. a fluorescent reporter) is the determining factor for silencing, not the chosen locus.';

update known_safe_harbors set tissue_context = 'hiPSCs, differentiated into cardiomyocytes and endothelium' where source_pmid = '38372898' and evidence_summary = 'Same comparative study: dCas9-VPR targeted to CLYBL also silences after differentiation into cardiomyocytes/endothelium, even though CLYBL is generally considered the best-performing locus among the three tested in this article. Reinforces that payload (not locus) determines silencing in this case.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs, differentiated into cardiomyocytes and endothelium' where source_pmid = '38372898' and evidence_summary = 'Same comparative study: dCas9-VPR targeted to CLYBL also silences after differentiation into cardiomyocytes/endothelium, even though CLYBL is generally considered the best-performing locus among the three tested in this article. Reinforces that payload (not locus) determines silencing in this case.';

update known_safe_harbors set tissue_context = 'Patient-derived iPSCs and differentiated endothelial cells; in vivo blood/subcutaneous transplant in mice' where source_pmid = '39762408' and evidence_summary = 'FE-FVIII variant (hemophilia A) inserted at AAVS1 via Cas9(D10A) nickase in patient-derived iPSCs. Expressed in undifferentiated iPSCs AND in differentiated endothelial cells. HA mice transplanted with these ECs: 2.12x increase in blood FVIII activity, ~20% higher post-hemorrhage survival, effect maintained >3 months after subcutaneous transplant.';
update public_safe_harbors_staging set tissue_context = 'Patient-derived iPSCs and differentiated endothelial cells; in vivo blood/subcutaneous transplant in mice' where source_pmid = '39762408' and evidence_summary = 'FE-FVIII variant (hemophilia A) inserted at AAVS1 via Cas9(D10A) nickase in patient-derived iPSCs. Expressed in undifferentiated iPSCs AND in differentiated endothelial cells. HA mice transplanted with these ECs: 2.12x increase in blood FVIII activity, ~20% higher post-hemorrhage survival, effect maintained >3 months after subcutaneous transplant.';

update known_safe_harbors set tissue_context = 'hPSCs differentiated into forebrain organoids' where source_pmid = '39545087' and evidence_summary = 'ChR2 (channelrhodopsin-2) inserted at AAVS1 in hPSCs, differentiated into forebrain organoids. Homogeneous, stable expression throughout the region, without structural/functional disruption, robust and consistent light-driven neuronal activation. Directly relevant to neuronal contexts.';
update public_safe_harbors_staging set tissue_context = 'hPSCs differentiated into forebrain organoids' where source_pmid = '39545087' and evidence_summary = 'ChR2 (channelrhodopsin-2) inserted at AAVS1 in hPSCs, differentiated into forebrain organoids. Homogeneous, stable expression throughout the region, without structural/functional disruption, robust and consistent light-driven neuronal activation. Directly relevant to neuronal contexts.';

update known_safe_harbors set tissue_context = 'Jurkat T cells' where source_pmid = '35795775' and evidence_summary = 'In Jurkat T cells, a transgene at AAVS1 does not silence up to 160 days -- but expression shows huge transcriptional variation, over two orders of magnitude (100x) between cells, measured by barcoding + single-cell next-generation sequencing. Does not silence, but is highly heterogeneous in magnitude.';
update public_safe_harbors_staging set tissue_context = 'Jurkat T cells' where source_pmid = '35795775' and evidence_summary = 'In Jurkat T cells, a transgene at AAVS1 does not silence up to 160 days -- but expression shows huge transcriptional variation, over two orders of magnitude (100x) between cells, measured by barcoding + single-cell next-generation sequencing. Does not silence, but is highly heterogeneous in magnitude.';

update known_safe_harbors set tissue_context = 'iPSCs differentiated into myeloid cells (neutrophil/macrophage lineage)' where source_pmid = '31773990' and evidence_summary = 'Correction of p47phox deficiency (chronic granulomatous disease) via AAVS1 in iPSCs, testing 3 myeloid-specific promoters after differentiation: miR223 and CatG/cFes gave therapeutically relevant expression; the MRP8 promoter was much less efficient due to high CpG methylation in differentiated cells. Silencing depends strongly on the chosen promoter, not just the locus.';
update public_safe_harbors_staging set tissue_context = 'iPSCs differentiated into myeloid cells (neutrophil/macrophage lineage)' where source_pmid = '31773990' and evidence_summary = 'Correction of p47phox deficiency (chronic granulomatous disease) via AAVS1 in iPSCs, testing 3 myeloid-specific promoters after differentiation: miR223 and CatG/cFes gave therapeutically relevant expression; the MRP8 promoter was much less efficient due to high CpG methylation in differentiated cells. Silencing depends strongly on the chosen promoter, not just the locus.';

update known_safe_harbors set tissue_context = 'hiPSCs, differentiated into cardiomyocytes' where source_pmid = '32789000' and evidence_summary = 'Title of the article itself: identifies AAVS1 as "not an entirely safe harbour". Of 24 targeted hiPSC clones, only 20 expressed the transgene, ranging 0-99.5% positive cells. During differentiation into cardiomyocytes, silencing was observed: 98.93% -> 1.3% positive cells in one clone. A doxycycline-inducible system showed up to a 10,000x drop within 8-10 days. Expression only rescued with continuous puromycin selection.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs, differentiated into cardiomyocytes' where source_pmid = '32789000' and evidence_summary = 'Title of the article itself: identifies AAVS1 as "not an entirely safe harbour". Of 24 targeted hiPSC clones, only 20 expressed the transgene, ranging 0-99.5% positive cells. During differentiation into cardiomyocytes, silencing was observed: 98.93% -> 1.3% positive cells in one clone. A doxycycline-inducible system showed up to a 10,000x drop within 8-10 days. Expression only rescued with continuous puromycin selection.';

update known_safe_harbors set tissue_context = 'Peripheral blood cells in vivo (mouse), following HSC transduction' where source_pmid = '31494053' and evidence_summary = 'Transgenic mice carrying the human AAVS1 target sequence, tested with in vivo hematopoietic stem cell (HSC) transduction using HDAd5/35++ vectors. On average >60% of peripheral blood cells expressed the transgene after in vivo selection -- gamma-globin expression significantly higher and more stable than with random integration (SB100x-transposase system) used as a comparator in the same study.';
update public_safe_harbors_staging set tissue_context = 'Peripheral blood cells in vivo (mouse), following HSC transduction' where source_pmid = '31494053' and evidence_summary = 'Transgenic mice carrying the human AAVS1 target sequence, tested with in vivo hematopoietic stem cell (HSC) transduction using HDAd5/35++ vectors. On average >60% of peripheral blood cells expressed the transgene after in vivo selection -- gamma-globin expression significantly higher and more stable than with random integration (SB100x-transposase system) used as a comparator in the same study.';

update known_safe_harbors set tissue_context = 'Liver-exclusive in vivo expression (mouse), confirmed from embryonic stage E16.5' where source_pmid = '30591434' and evidence_summary = 'H11-albumin-rtTA mice (albumin promoter driving rtTA at the H11 locus) -- liver-exclusive, doxycycline-inducible expression, confirmed by crossing with a TetO-H2BGFP reporter. Cre-mediated recombination as efficient as the conventional Albumin-Cre control. Reporter expression detectable already from embryonic stage E16.5 when induced.';
update public_safe_harbors_staging set tissue_context = 'Liver-exclusive in vivo expression (mouse), confirmed from embryonic stage E16.5' where source_pmid = '30591434' and evidence_summary = 'H11-albumin-rtTA mice (albumin promoter driving rtTA at the H11 locus) -- liver-exclusive, doxycycline-inducible expression, confirmed by crossing with a TetO-H2BGFP reporter. Cre-mediated recombination as efficient as the conventional Albumin-Cre control. Reporter expression detectable already from embryonic stage E16.5 when induced.';

update known_safe_harbors set tissue_context = 'Human iPSCs, long-term culture and multi-lineage differentiation' where source_pmid = '26707206' and evidence_summary = 'Robust, reproducible CAG-promoter-driven expression at AAVS1 (PPP1R12C intron), with reproducible copy-number control between subclones (~2x). Expression maintained during long-term culture of human iPSCs and through differentiation into multiple lineages. Widely used protocol/methodology paper, commonly cited as a reference.';
update public_safe_harbors_staging set tissue_context = 'Human iPSCs, long-term culture and multi-lineage differentiation' where source_pmid = '26707206' and evidence_summary = 'Robust, reproducible CAG-promoter-driven expression at AAVS1 (PPP1R12C intron), with reproducible copy-number control between subclones (~2x). Expression maintained during long-term culture of human iPSCs and through differentiation into multiple lineages. Widely used protocol/methodology paper, commonly cited as a reference.';

update known_safe_harbors set tissue_context = 'Undifferentiated hESCs and differentiated hepatocytes' where source_pmid = '26455413' and evidence_summary = 'Explicit conclusion from the title itself: "AAVS1 Locus-Mediated Transgene Inhibition". Unexpected, variable expression inhibition observed both in undifferentiated hESCs and in differentiated hepatocytes, attributed to DNA methylation and other unknown mechanisms. Authors'' conclusion: "AAVS1 cannot be considered a universally safe harbor for reliable transgene expression in vitro".';
update public_safe_harbors_staging set tissue_context = 'Undifferentiated hESCs and differentiated hepatocytes' where source_pmid = '26455413' and evidence_summary = 'Explicit conclusion from the title itself: "AAVS1 Locus-Mediated Transgene Inhibition". Unexpected, variable expression inhibition observed both in undifferentiated hESCs and in differentiated hepatocytes, attributed to DNA methylation and other unknown mechanisms. Authors'' conclusion: "AAVS1 cannot be considered a universally safe harbor for reliable transgene expression in vitro".';

update known_safe_harbors set tissue_context = 'Mouse ES cells' where source_pmid = '19279185' and evidence_summary = 'Promoter comparison within the ROSA26 locus itself in mouse ES cells: direct expression from the endogenous ROSA26 promoter gives a moderate level; inserting a CAGG promoter at the ROSA26 locus gives higher expression. Expression level at ROSA26 depends strongly on the promoter used, not just the choice of locus.';
update public_safe_harbors_staging set tissue_context = 'Mouse ES cells' where source_pmid = '19279185' and evidence_summary = 'Promoter comparison within the ROSA26 locus itself in mouse ES cells: direct expression from the endogenous ROSA26 promoter gives a moderate level; inserting a CAGG promoter at the ROSA26 locus gives higher expression. Expression level at ROSA26 depends strongly on the promoter used, not just the choice of locus.';

update known_safe_harbors set tissue_context = 'hESC-derived lineages (multiple, not itemized)' where source_pmid = '18037879' and evidence_summary = 'Founding paper identifying the human homolog of the mouse ROSA26 locus. tdRFP targeted by homologous recombination was expressed across multiple hESC-derived lineages. Recombinase-mediated cassette exchange (RMCE) demonstrated to swap the transgene for other cDNAs at the same locus.';
update public_safe_harbors_staging set tissue_context = 'hESC-derived lineages (multiple, not itemized)' where source_pmid = '18037879' and evidence_summary = 'Founding paper identifying the human homolog of the mouse ROSA26 locus. tdRFP targeted by homologous recombination was expressed across multiple hESC-derived lineages. Recombinase-mediated cassette exchange (RMCE) demonstrated to swap the transgene for other cDNAs at the same locus.';

update known_safe_harbors set tissue_context = 'Human embryonic stem cells (hESCs), including 15-day differentiation' where source_pmid = '18024421' and evidence_summary = 'Founding paper (2007), direct quantified comparison with random integration: with selection, 90+-4% positive cells at AAVS1 vs. 57+-32% with random integration; 25 days after removing selection, 86+-7% vs. only 39+-31% (random) -- i.e. much more resistant to silencing. After 15 days of differentiation, >90% (AAVS1) vs. ~30% (random) still positive. One of the most cited papers in the field.';
update public_safe_harbors_staging set tissue_context = 'Human embryonic stem cells (hESCs), including 15-day differentiation' where source_pmid = '18024421' and evidence_summary = 'Founding paper (2007), direct quantified comparison with random integration: with selection, 90+-4% positive cells at AAVS1 vs. 57+-32% with random integration; 25 days after removing selection, 86+-7% vs. only 39+-31% (random) -- i.e. much more resistant to silencing. After 15 days of differentiation, >90% (AAVS1) vs. ~30% (random) still positive. One of the most cited papers in the field.';

update known_safe_harbors set tissue_context = 'CAR-CD19 T cells (murine leukemia model)' where source_pmid = '36745870' and evidence_summary = 'Extragenic locus identified by a proprietary algorithm (7 criteria to minimize genotoxicity and maximize CRISPR/Cas9 efficiency and resistance to silencing). CAR-CD19 T cells built at GSH6 were curative at a low cell dose in a murine acute lymphoblastic leukemia model, matching the potency of CAR-T cells built at the TRAC locus, and resisting tumor rechallenge 100 days after infusion. Substantially stronger data than the brief mention found earlier via secondary review -- this is the primary paper.';
update public_safe_harbors_staging set tissue_context = 'CAR-CD19 T cells (murine leukemia model)' where source_pmid = '36745870' and evidence_summary = 'Extragenic locus identified by a proprietary algorithm (7 criteria to minimize genotoxicity and maximize CRISPR/Cas9 efficiency and resistance to silencing). CAR-CD19 T cells built at GSH6 were curative at a low cell dose in a murine acute lymphoblastic leukemia model, matching the potency of CAR-T cells built at the TRAC locus, and resisting tumor rechallenge 100 days after infusion. Substantially stronger data than the brief mention found earlier via secondary review -- this is the primary paper.';

update known_safe_harbors set tissue_context = 'Human rhabdomyosarcoma cells' where source_pmid = '30793977' and evidence_summary = 'Additional detail on a locus already registered: transgene-encoded Cas9 proteins at SHS231 (chromosome 4) used to introduce a large (17kb) gRNA-guided deletion in the PAX3/FOXO1 fusion oncogene in human rhabdomyosarcoma cells, and as a Cas9-VPR fusion to activate the muscle transcription factor MYF5. Confirms transgene function, not just expression, at this locus.';
update public_safe_harbors_staging set tissue_context = 'Human rhabdomyosarcoma cells' where source_pmid = '30793977' and evidence_summary = 'Additional detail on a locus already registered: transgene-encoded Cas9 proteins at SHS231 (chromosome 4) used to introduce a large (17kb) gRNA-guided deletion in the PAX3/FOXO1 fusion oncogene in human rhabdomyosarcoma cells, and as a Cas9-VPR fusion to activate the muscle transcription factor MYF5. Confirms transgene function, not just expression, at this locus.';

update known_safe_harbors set tissue_context = 'Human fibroblasts' where source_pmid = '26260320' and evidence_summary = 'An under-discussed safety consideration: the AAVS1 locus includes the coding region of the MBS85 gene (myosin binding subunit 85). Transgene insertion at AAVS1 significantly reduces MBS85 expression and alters myosin-II-dependent contractile force in human fibroblasts (via phosphorylation of the myosin regulatory light chain) -- effect reversed by restoring MBS85 expression. A real effect on a neighboring gene, not just a theoretical one.';
update public_safe_harbors_staging set tissue_context = 'Human fibroblasts' where source_pmid = '26260320' and evidence_summary = 'An under-discussed safety consideration: the AAVS1 locus includes the coding region of the MBS85 gene (myosin binding subunit 85). Transgene insertion at AAVS1 significantly reduces MBS85 expression and alters myosin-II-dependent contractile force in human fibroblasts (via phosphorylation of the myosin regulatory light chain) -- effect reversed by restoring MBS85 expression. A real effect on a neighboring gene, not just a theoretical one.';

update known_safe_harbors set tissue_context = 'Patient-derived CD34+ iPSCs, differentiated into neutrophils and macrophages' where source_pmid = '25288370' and evidence_summary = 'AAVS1-targeted (ZFN) minigene platform to correct all 5 chronic granulomatous disease genotypes in patient-derived CD34+ iPSCs. Targeted insertion with constitutive expression in 70-80% of selected clones. Neutrophils and macrophages differentiated from these corrected iPSCs showed restored oxidase activity and functional antimicrobial activity against real bacterial pathogens.';
update public_safe_harbors_staging set tissue_context = 'Patient-derived CD34+ iPSCs, differentiated into neutrophils and macrophages' where source_pmid = '25288370' and evidence_summary = 'AAVS1-targeted (ZFN) minigene platform to correct all 5 chronic granulomatous disease genotypes in patient-derived CD34+ iPSCs. Targeted insertion with constitutive expression in 70-80% of selected clones. Neutrophils and macrophages differentiated from these corrected iPSCs showed restored oxidase activity and functional antimicrobial activity against real bacterial pathogens.';

update known_safe_harbors set tissue_context = 'iPSCs, differentiated into excitatory neurons' where source_pmid = '33610017' and evidence_summary = 'Two independent iPSC lines with a doxycycline-inducible NGN2 cassette (with and without GFP) inserted at AAVS1: remain pluripotent without doxycycline, differentiate rapidly and homogeneously into excitatory neurons when induced, with no need for additional differentiation factors.';
update public_safe_harbors_staging set tissue_context = 'iPSCs, differentiated into excitatory neurons' where source_pmid = '33610017' and evidence_summary = 'Two independent iPSC lines with a doxycycline-inducible NGN2 cassette (with and without GFP) inserted at AAVS1: remain pluripotent without doxycycline, differentiate rapidly and homogeneously into excitatory neurons when induced, with no need for additional differentiation factors.';

update known_safe_harbors set tissue_context = 'hiPSCs, differentiated into excitatory neurons' where source_pmid = '35696030' and evidence_summary = 'Equivalent/independent system: a doxycycline-inducible Neurogenin-2 (Ngn2) cassette inserted at AAVS1 by CRISPR/Cas9 in hiPSCs -- generates a cell line that differentiates rapidly and homogeneously into excitatory neurons.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs, differentiated into excitatory neurons' where source_pmid = '35696030' and evidence_summary = 'Equivalent/independent system: a doxycycline-inducible Neurogenin-2 (Ngn2) cassette inserted at AAVS1 by CRISPR/Cas9 in hiPSCs -- generates a cell line that differentiates rapidly and homogeneously into excitatory neurons.';

update known_safe_harbors set tissue_context = 'Primary human T cells' where source_pmid = '31901177' and evidence_summary = 'CELiD vector (closed-ended double-stranded linear DNA, AAV-derived) used to integrate an anti-CD19 CAR directly at AAVS1 in primary human T cells -- integration efficiency up to 22.8%, resulting CAR-T cells produced abundant effector cytokines and killed up to 75% of target cells in vitro.';
update public_safe_harbors_staging set tissue_context = 'Primary human T cells' where source_pmid = '31901177' and evidence_summary = 'CELiD vector (closed-ended double-stranded linear DNA, AAV-derived) used to integrate an anti-CD19 CAR directly at AAVS1 in primary human T cells -- integration efficiency up to 22.8%, resulting CAR-T cells produced abundant effector cytokines and killed up to 75% of target cells in vitro.';

-- (batches 3-6 tissue_context complete -- 23/23 records)
