-- Backfills tissue_context for staging_insert_batch7.sql records (28 records).

update known_safe_harbors set tissue_context = 'hESC, plus derived neuronal, hepatic, cardiac, and pancreatic lineages; teratoma assay confirms all 3 germ layers' where source_pmid = '38164941' and evidence_summary = 'Exact coordinates (nearest gene: MAGI3, not MYBPC as previously thought). Validated in hESC: log2 fold-change between -0.067 and 0.065 vs. untargeted; 96 differentially expressed genes out of 29,696 tested; >98% Clover-positive cells maintained over 15 passages; stable expression in neuronal, hepatic, cardiac, and pancreatic derivatives; normal karyotype; teratoma confirms all 3 germ layers; nearest differentially expressed gene is >3Mb from the integration site.';
update public_safe_harbors_staging set tissue_context = 'hESC, plus derived neuronal, hepatic, cardiac, and pancreatic lineages; teratoma assay confirms all 3 germ layers' where source_pmid = '38164941' and evidence_summary = 'Exact coordinates (nearest gene: MAGI3, not MYBPC as previously thought). Validated in hESC: log2 fold-change between -0.067 and 0.065 vs. untargeted; 96 differentially expressed genes out of 29,696 tested; >98% Clover-positive cells maintained over 15 passages; stable expression in neuronal, hepatic, cardiac, and pancreatic derivatives; normal karyotype; teratoma confirms all 3 germ layers; nearest differentially expressed gene is >3Mb from the integration site.';

update known_safe_harbors set tissue_context = 'hESC, across all 3 germ layers (same validation panel as Pansio-1)' where source_pmid = '38164941' and evidence_summary = 'Exact coordinates (nearest gene: TXNL1). Same validation profile as Pansio-1: log2-FC -0.067 to 0.065, 111 differentially expressed genes out of 29,696, >98% Clover-positive for 15 passages, expression maintained across all 3 germ layers, normal karyotype, nearest DE gene >5Mb away.';
update public_safe_harbors_staging set tissue_context = 'hESC, across all 3 germ layers (same validation panel as Pansio-1)' where source_pmid = '38164941' and evidence_summary = 'Exact coordinates (nearest gene: TXNL1). Same validation profile as Pansio-1: log2-FC -0.067 to 0.065, 111 differentially expressed genes out of 29,696, >98% Clover-positive for 15 passages, expression maintained across all 3 germ layers, normal karyotype, nearest DE gene >5Mb away.';

update known_safe_harbors set tissue_context = 'hESC, plus derived neurons, hepatocytes, and cardiomyocytes' where source_pmid = '38164941' and evidence_summary = 'Exact coordinates (nearest gene: ZNRF4). Same validation profile: log2-FC -0.067 to 0.065, 119 differentially expressed genes out of 29,696, >98% Clover-positive, expression maintained in derived neurons/hepatocytes/cardiomyocytes, normal karyotype. Nearest DE gene only ~1Mb away -- the closest of the three, still passed safety criteria.';
update public_safe_harbors_staging set tissue_context = 'hESC, plus derived neurons, hepatocytes, and cardiomyocytes' where source_pmid = '38164941' and evidence_summary = 'Exact coordinates (nearest gene: ZNRF4). Same validation profile: log2-FC -0.067 to 0.065, 119 differentially expressed genes out of 29,696, >98% Clover-positive, expression maintained in derived neurons/hepatocytes/cardiomyocytes, normal karyotype. Nearest DE gene only ~1Mb away -- the closest of the three, still passed safety criteria.';

update known_safe_harbors set tissue_context = 'HUDEP2 erythroid progenitor cells' where source_pmid = '36131352' and evidence_summary = 'Exact coordinates (intron of GOLGA4). The only one of 3 candidates tested in HUDEP2 erythroid cells to show full success: GFP signal remained positive for 3 months, with no significant change in GOLGA4 expression or in adjacent genes within the same TAD.';
update public_safe_harbors_staging set tissue_context = 'HUDEP2 erythroid progenitor cells' where source_pmid = '36131352' and evidence_summary = 'Exact coordinates (intron of GOLGA4). The only one of 3 candidates tested in HUDEP2 erythroid cells to show full success: GFP signal remained positive for 3 months, with no significant change in GOLGA4 expression or in adjacent genes within the same TAD.';

update known_safe_harbors set tissue_context = 'HUDEP2 erythroid progenitor cells' where source_pmid = '36131352' and evidence_summary = 'CORRECTION to a prior record (batch 2, via secondary review): these two candidates (ARID1B and TAF2) were indeed tested in HUDEP2 cells alongside BLD_SHS10, but the primary article states that "only BLD_GSH_10 showed full success" -- suggesting these two did NOT have the same positive result the secondary review implied. Confidence lowered to reflect this contradiction; needs direct confirmation against the primary article before any use.';
update public_safe_harbors_staging set tissue_context = 'HUDEP2 erythroid progenitor cells' where source_pmid = '36131352' and evidence_summary = 'CORRECTION to a prior record (batch 2, via secondary review): these two candidates (ARID1B and TAF2) were indeed tested in HUDEP2 cells alongside BLD_SHS10, but the primary article states that "only BLD_GSH_10 showed full success" -- suggesting these two did NOT have the same positive result the secondary review implied. Confidence lowered to reflect this contradiction; needs direct confirmation against the primary article before any use.';

update known_safe_harbors set tissue_context = 'HEK293T (also validated in Jurkat -- see paired Rogi2 record)' where source_pmid = '35474867' and evidence_summary = 'Rich validation (exact location only in a figure, not extractable from text): stable mRuby expression 90 days after integration in HEK293T, outperforming AAVS1 in the same assay. 94.7% mRuby+ primary T cells after selection; >92% GFP+ primary dermal fibroblasts, maintained >25 days. Single-cell RNA-seq shows minimal transcriptome disruption, no upregulation of cancer-associated pathways.';
update public_safe_harbors_staging set tissue_context = 'HEK293T, primary T cells, and primary dermal fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Rich validation (exact location only in a figure, not extractable from text): stable mRuby expression 90 days after integration in HEK293T, outperforming AAVS1 in the same assay. 94.7% mRuby+ primary T cells after selection; >92% GFP+ primary dermal fibroblasts, maintained >25 days. Single-cell RNA-seq shows minimal transcriptome disruption, no upregulation of cancer-associated pathways.';

update known_safe_harbors set tissue_context = 'HEK293T, Jurkat, primary T cells, and fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Rich validation: stable mRuby expression 90 days in HEK293T AND Jurkat, outperforming the CCR5 locus in Jurkat. 91.8% mRuby+ primary T cells after selection; >92% GFP+ fibroblasts, maintained >25 days. Bulk RNA-seq showed no significant enrichment of cancer-associated genes or pathways.';
update public_safe_harbors_staging set tissue_context = 'HEK293T, Jurkat, primary T cells, and fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Rich validation: stable mRuby expression 90 days in HEK293T AND Jurkat, outperforming the CCR5 locus in Jurkat. 91.8% mRuby+ primary T cells after selection; >92% GFP+ fibroblasts, maintained >25 days. Bulk RNA-seq showed no significant enrichment of cancer-associated genes or pathways.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of ANP32E. Computational candidate via polymorphic mobile element insertions + epigenomics + 3D chromatin organization. Not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of ANP32E. Computational candidate via polymorphic mobile element insertions + epigenomics + 3D chromatin organization. Not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of NEK7. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of NEK7. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of NFRKB. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of NFRKB. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of VPS33A. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of VPS33A. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of ANKRD10. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of ANKRD10. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of GALK2. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of GALK2. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intergenic. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intergenic. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of DHX57. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of DHX57. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of FARSB. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of FARSB. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of LARS2. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of LARS2. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of SACM1L. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of SACM1L. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of AFF1. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of AFF1. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of TRMO. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of TRMO. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of FKBP15. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of FKBP15. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of CDK11A. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of CDK11A. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of MORF4L1. Computational candidate, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- no cell type assayed (computational candidate only)' where source_pmid = '36131352' and evidence_summary = 'Intron of MORF4L1. Computational candidate, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of AHCTF1. Computational candidate for brain cells, not experimentally tested. Relevant for neuronal applications.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of AHCTF1. Computational candidate for brain cells, not experimentally tested. Relevant for neuronal applications.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of WNK1. Computational candidate for brain cells, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of WNK1. Computational candidate for brain cells, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of MICAL3. Computational candidate for brain cells, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of MICAL3. Computational candidate for brain cells, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of CRMP1. Computational candidate for brain cells, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of CRMP1. Computational candidate for brain cells, not experimentally tested.';

update known_safe_harbors set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of LOC221946. Computational candidate for brain cells, not experimentally tested.';
update public_safe_harbors_staging set tissue_context = 'Not experimentally tested -- computational candidate intended for brain cell applications' where source_pmid = '36131352' and evidence_summary = 'Intron of LOC221946. Computational candidate for brain cells, not experimentally tested.';

-- (batch 7 tissue_context complete -- 28/28 records)
