-- Backfills tissue_context for staging_insert_batch1.sql records (13 records).
-- Matches by source_pmid + exact (now-English) evidence_summary. Safe to run
-- even if a pmid/locus combo repeats with different text.

update known_safe_harbors set tissue_context = 'iPSCs and HEK293T (methylation comparison); neural stem cell differentiation also tested, silencing not reversed' where source_pmid = '41468306' and evidence_summary = 'In human iPSCs, CRISPR/Cas9 targeting AAVS1 to insert optogenetic/chemogenetic receptors (ChR2/hM4Di) resulted in silencing -- TRE3G BI promoter showed 95.3-98.2% methylation in iPSCs, vs. only 5.9% in HEK293T with the same construct. Hypomethylated clones also failed to express. Differentiation into neural stem cells did not reverse silencing.';
update public_safe_harbors_staging set tissue_context = 'iPSCs and HEK293T (methylation comparison); neural stem cell differentiation also tested, silencing not reversed' where source_pmid = '41468306' and evidence_summary = 'In human iPSCs, CRISPR/Cas9 targeting AAVS1 to insert optogenetic/chemogenetic receptors (ChR2/hM4Di) resulted in silencing -- TRE3G BI promoter showed 95.3-98.2% methylation in iPSCs, vs. only 5.9% in HEK293T with the same construct. Hypomethylated clones also failed to express. Differentiation into neural stem cells did not reverse silencing.';

update known_safe_harbors set tissue_context = 'Whole organism (systemic antibody production in vivo); specific producing tissue not itemized in evidence text' where source_pmid = '41341583' and evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at ROSA26 maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.108nM.';
update public_safe_harbors_staging set tissue_context = 'Whole organism (systemic antibody production in vivo); specific producing tissue not itemized in evidence text' where source_pmid = '41341583' and evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at ROSA26 maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.108nM.';

update known_safe_harbors set tissue_context = 'Whole organism (systemic antibody production in vivo); specific producing tissue not itemized in evidence text' where source_pmid = '41341583' and evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at Hipp11 (H11) maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.154nM.';
update public_safe_harbors_staging set tissue_context = 'Whole organism (systemic antibody production in vivo); specific producing tissue not itemized in evidence text' where source_pmid = '41341583' and evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at Hipp11 (H11) maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.154nM.';

update known_safe_harbors set tissue_context = 'Macrophages (RNA-seq + TLR3/TLR4/TRIF signaling immunoblot)' where source_pmid = '41208113' and evidence_summary = 'Macrophages isolated from Rosa26-Cas9 mice (Cas9-FZ line, Jackson Lab #026179, the most widely used worldwide) showed no defects in any commonly tested macrophage signaling pathway (RNA-seq + TLR3/TLR4/TRIF signaling immunoblot), contradicting an earlier report of differences.';
update public_safe_harbors_staging set tissue_context = 'Macrophages (RNA-seq + TLR3/TLR4/TRIF signaling immunoblot)' where source_pmid = '41208113' and evidence_summary = 'Macrophages isolated from Rosa26-Cas9 mice (Cas9-FZ line, Jackson Lab #026179, the most widely used worldwide) showed no defects in any commonly tested macrophage signaling pathway (RNA-seq + TLR3/TLR4/TRIF signaling immunoblot), contradicting an earlier report of differences.';

update known_safe_harbors set tissue_context = 'Trophoblast stem cells (hTSC), differentiated into extravillous cytotrophoblast and syncytiotrophoblast' where source_pmid = '41523105' and evidence_summary = 'Human trophoblast stem cells (hTSC, CT29 line) GFP-tagged via knock-in at AAVS1 remained proliferative and able to differentiate into extravillous cytotrophoblast and syncytiotrophoblast -- first demonstration of AAVS1 integration in this cell lineage.';
update public_safe_harbors_staging set tissue_context = 'Trophoblast stem cells (hTSC), differentiated into extravillous cytotrophoblast and syncytiotrophoblast' where source_pmid = '41523105' and evidence_summary = 'Human trophoblast stem cells (hTSC, CT29 line) GFP-tagged via knock-in at AAVS1 remained proliferative and able to differentiate into extravillous cytotrophoblast and syncytiotrophoblast -- first demonstration of AAVS1 integration in this cell lineage.';

update known_safe_harbors set tissue_context = 'Mouse embryonic stem cells (mESCs), differentiated into neurons' where source_pmid = '40036200' and evidence_summary = 'Biotin ligases (MicroID/TurboID) randomly integrated in mESCs express well in stem cells but silence completely after differentiation into neurons, regardless of promoter. The same construct targeted to the mHipp11 (H11) locus retained expression, correct localization, and activity after 8-10 days of neuronal differentiation.';
update public_safe_harbors_staging set tissue_context = 'Mouse embryonic stem cells (mESCs), differentiated into neurons' where source_pmid = '40036200' and evidence_summary = 'Biotin ligases (MicroID/TurboID) randomly integrated in mESCs express well in stem cells but silence completely after differentiation into neurons, regardless of promoter. The same construct targeted to the mHipp11 (H11) locus retained expression, correct localization, and activity after 8-10 days of neuronal differentiation.';

update known_safe_harbors set tissue_context = 'hiPSCs, differentiated into cardiomyocytes (hiPSC-CM)' where source_pmid = '39926351' and evidence_summary = 'Dox-inducible system (Tet-On 3G in hROSA26 + transgene in AAVS1) undergoes significant silencing in hiPSC-derived cardiomyocytes (hiPSC-CM). Sodium butyrate restores activity but compromises hiPSC viability. Relocating the cassette to the CLYBL locus improved promoter activity relative to AAVS1, both in hiPSC and hiPSC-CM.';
update public_safe_harbors_staging set tissue_context = 'hiPSCs, differentiated into cardiomyocytes (hiPSC-CM)' where source_pmid = '39926351' and evidence_summary = 'Dox-inducible system (Tet-On 3G in hROSA26 + transgene in AAVS1) undergoes significant silencing in hiPSC-derived cardiomyocytes (hiPSC-CM). Sodium butyrate restores activity but compromises hiPSC viability. Relocating the cassette to the CLYBL locus improved promoter activity relative to AAVS1, both in hiPSC and hiPSC-CM.';

update known_safe_harbors set tissue_context = 'Mouse embryonic stem cells (mESCs)' where source_pmid = '39777513' and evidence_summary = 'Direct comparison of 3 serine integrases (PhiC31, W-beta, Bxb1) at the Gt(ROSA)26Sor locus in mESCs -- all compatible with pluripotency and germline transmission; Bxb1 was 2-3x more efficient than the other two.';
update public_safe_harbors_staging set tissue_context = 'Mouse embryonic stem cells (mESCs)' where source_pmid = '39777513' and evidence_summary = 'Direct comparison of 3 serine integrases (PhiC31, W-beta, Bxb1) at the Gt(ROSA)26Sor locus in mESCs -- all compatible with pluripotency and germline transmission; Bxb1 was 2-3x more efficient than the other two.';

update known_safe_harbors set tissue_context = 'Human iPSCs' where source_pmid = '39777513' and evidence_summary = 'Bxb1 system adapted for cassette exchange at AAVS1 in hiPSCs: the CAG promoter gave consistent, stable expression; the Ef1a (EIF1A) promoter gave a very mosaic expression pattern in the same cell line -- effect depends strongly on the promoter, not just the locus.';
update public_safe_harbors_staging set tissue_context = 'Human iPSCs' where source_pmid = '39777513' and evidence_summary = 'Bxb1 system adapted for cassette exchange at AAVS1 in hiPSCs: the CAG promoter gave consistent, stable expression; the Ef1a (EIF1A) promoter gave a very mosaic expression pattern in the same cell line -- effect depends strongly on the promoter, not just the locus.';

update known_safe_harbors set tissue_context = 'Multiple tissues examined in vivo (mouse); heterogeneous across tissues, exact panel not itemized in evidence text' where source_pmid = '38752269' and evidence_summary = 'Direct comparison of ROSA26 vs. H11 in the same mouse (3 fluorescent reporters -- EGFP, tdTomato, mTagBFP2 -- under the CAG promoter, including a triple-transgenic model). Expression efficiency was higher at ROSA26 than H11 in most tissues examined. Substantial expression heterogeneity was observed even between cells of the same tissue.';
update public_safe_harbors_staging set tissue_context = 'Multiple tissues examined in vivo (mouse); heterogeneous across tissues, exact panel not itemized in evidence text' where source_pmid = '38752269' and evidence_summary = 'Direct comparison of ROSA26 vs. H11 in the same mouse (3 fluorescent reporters -- EGFP, tdTomato, mTagBFP2 -- under the CAG promoter, including a triple-transgenic model). Expression efficiency was higher at ROSA26 than H11 in most tissues examined. Substantial expression heterogeneity was observed even between cells of the same tissue.';

update known_safe_harbors set tissue_context = 'Multiple tissues examined in vivo (mouse); heterogeneous across tissues, exact panel not itemized in evidence text' where source_pmid = '38752269' and evidence_summary = 'In the same direct comparative study with ROSA26 (3 fluorescent reporters under CAG), expression efficiency at H11 was lower than at ROSA26 in most tissues, though still functional. Substantial heterogeneity between cells of the same tissue.';
update public_safe_harbors_staging set tissue_context = 'Multiple tissues examined in vivo (mouse); heterogeneous across tissues, exact panel not itemized in evidence text' where source_pmid = '38752269' and evidence_summary = 'In the same direct comparative study with ROSA26 (3 fluorescent reporters under CAG), expression efficiency at H11 was lower than at ROSA26 in most tissues, though still functional. Substantial heterogeneity between cells of the same tissue.';

update known_safe_harbors set tissue_context = 'Embryonic stem cells (mouse and human) and whole mouse in vivo' where source_pmid = '33202307' and evidence_summary = 'The H11 locus supports constitutive and conditional expression of the TIR1 transgene (AID degradation system) in both mouse AND human embryonic stem cells, and in mice in vivo -- cross-species validation of the same locus.';
update public_safe_harbors_staging set tissue_context = 'Embryonic stem cells (mouse and human) and whole mouse in vivo' where source_pmid = '33202307' and evidence_summary = 'The H11 locus supports constitutive and conditional expression of the TIR1 transgene (AID degradation system) in both mouse AND human embryonic stem cells, and in mice in vivo -- cross-species validation of the same locus.';

update known_safe_harbors set tissue_context = 'Whole organism level (systemic, in vivo dog); specific tissue not itemized in evidence text' where source_pmid = '32492024' and evidence_summary = 'In transgenic dogs generated by SCNT, the hEF1a promoter was silenced by DNA methylation (expression rescued by DNMT inhibition). The CMV promoter maintained strong expression at both organism and cell level in all transgenic dogs even after 19 months. Not a named safe harbor -- random integration via SCNT -- but direct silencing data in dog, the species most relevant to this project.';
update public_safe_harbors_staging set tissue_context = 'Whole organism level (systemic, in vivo dog); specific tissue not itemized in evidence text' where source_pmid = '32492024' and evidence_summary = 'In transgenic dogs generated by SCNT, the hEF1a promoter was silenced by DNA methylation (expression rescued by DNMT inhibition). The CMV promoter maintained strong expression at both organism and cell level in all transgenic dogs even after 19 months. Not a named safe harbor -- random integration via SCNT -- but direct silencing data in dog, the species most relevant to this project.';

-- (batch 1 tissue_context complete -- 13/13 records)
