-- Backfills tissue_context for staging_insert_batch10.sql (5), batch11.sql (6), batch12.sql (8) -- 19 records.

update known_safe_harbors set tissue_context = 'ESC/iPSC lines, including patient (Parkinson''s) and healthy-sibling-control iPSCs' where source_pmid = '24304893' and evidence_summary = 'FOUNDING PAPER of human H11: "we identified a novel human locus, H11, located in a safe, transcriptionally active intergenic region of chromosome 22" (confirms band 22q12.2 already on record via review). DICE system (dual cassette exchange via phiC31+Bxb1 integrases) with 100% specificity. Tested with mCherry and neural transcription factors (LMX1a, FOXA2, OTX2) in ESC/iPSC lines, including iPSC from a Parkinson''s patient and a healthy sibling control -- directly relevant to neuronal/dopaminergic differentiation.';
update public_safe_harbors_staging set tissue_context = 'ESC/iPSC lines, including patient (Parkinson''s) and healthy-sibling-control iPSCs' where source_pmid = '24304893' and evidence_summary = 'FOUNDING PAPER of human H11: "we identified a novel human locus, H11, located in a safe, transcriptionally active intergenic region of chromosome 22" (confirms band 22q12.2 already on record via review). DICE system (dual cassette exchange via phiC31+Bxb1 integrases) with 100% specificity. Tested with mCherry and neural transcription factors (LMX1a, FOXA2, OTX2) in ESC/iPSC lines, including iPSC from a Parkinson''s patient and a healthy sibling control -- directly relevant to neuronal/dopaminergic differentiation.';

update known_safe_harbors set tissue_context = 'Human T cells' where source_pmid = '32986839' and evidence_summary = 'Cas9-N57 fusion nuclease (Sleeping Beauty transposon DNA-binding domain fused to Cas9) used to insert an anti-CD19 CAR cassette at AAVS1 in human T cells -- unidirectional, specific insertion, fragments up to 12kb successfully integrated.';
update public_safe_harbors_staging set tissue_context = 'Human T cells' where source_pmid = '32986839' and evidence_summary = 'Cas9-N57 fusion nuclease (Sleeping Beauty transposon DNA-binding domain fused to Cas9) used to insert an anti-CD19 CAR cassette at AAVS1 in human T cells -- unidirectional, specific insertion, fragments up to 12kb successfully integrated.';

update known_safe_harbors set tissue_context = 'Mouse liver, in vivo cancer model' where source_pmid = '32986839' and evidence_summary = 'Same Cas9-N57 system used to insert oncogenic KrasG12D at ROSA26 (plus disruption of Trp53/Pten) to induce intrahepatic cholangiocarcinoma in mice -- not a locus failure, it confirms that ROSA26 expresses an inserted oncogene reliably and on command, used deliberately as a cancer model. Relevant as proof of reliable, controllable expression, even if in a different application context.';
update public_safe_harbors_staging set tissue_context = 'Mouse liver, in vivo cancer model' where source_pmid = '32986839' and evidence_summary = 'Same Cas9-N57 system used to insert oncogenic KrasG12D at ROSA26 (plus disruption of Trp53/Pten) to induce intrahepatic cholangiocarcinoma in mice -- not a locus failure, it confirms that ROSA26 expresses an inserted oncogene reliably and on command, used deliberately as a cancer model. Relevant as proof of reliable, controllable expression, even if in a different application context.';

update known_safe_harbors set tissue_context = 'Human T cells; humanized PBMC mouse model in vivo' where source_pmid = '36680242' and evidence_summary = 'Anti-HIV CAR (scFv from bNAb 10-1074) integrated at CCR5 in human T cells via CRISPR/Cas9. Specific lysis of HIV-infected cells in vitro. In a humanized PBMC mouse model, the CAR-T cells expanded and transiently limited HIV infection in vivo.';
update public_safe_harbors_staging set tissue_context = 'Human T cells; humanized PBMC mouse model in vivo' where source_pmid = '36680242' and evidence_summary = 'Anti-HIV CAR (scFv from bNAb 10-1074) integrated at CCR5 in human T cells via CRISPR/Cas9. Specific lysis of HIV-infected cells in vitro. In a humanized PBMC mouse model, the CAR-T cells expanded and transiently limited HIV infection in vivo.';

update known_safe_harbors set tissue_context = 'iPSCs, differentiated into hematopoietic cells including macrophages' where source_pmid = '26670276' and evidence_summary = 'Not transgene insertion, this is CCR5 disruption by CRISPR/Cas9 in iPSCs (12.5% editing with a single gRNA, rising to 27% with dual gRNA). iPSC lines homozygous for mutated CCR5 retained pluripotency characteristics and differentiated efficiently into hematopoietic cells, including macrophages. Edited macrophages were specifically resistant to CCR5-tropic virus, but not CXCR4-tropic virus -- confirms CCR5 loss is functionally well tolerated.';
update public_safe_harbors_staging set tissue_context = 'iPSCs, differentiated into hematopoietic cells including macrophages' where source_pmid = '26670276' and evidence_summary = 'Not transgene insertion, this is CCR5 disruption by CRISPR/Cas9 in iPSCs (12.5% editing with a single gRNA, rising to 27% with dual gRNA). iPSC lines homozygous for mutated CCR5 retained pluripotency characteristics and differentiated efficiently into hematopoietic cells, including macrophages. Edited macrophages were specifically resistant to CCR5-tropic virus, but not CXCR4-tropic virus -- confirms CCR5 loss is functionally well tolerated.';

update known_safe_harbors set tissue_context = 'Human peripheral blood T cells; in vivo mouse leukemia model' where source_pmid = '28225754' and evidence_summary = 'FOUNDING PAPER for using TRAC in CAR-T (Eyquem et al., highly cited). Anti-CD19 CAR directed to the TRAC locus (not random integration): uniform CAR expression in human peripheral blood T cells, increased potency vs. conventional CAR-T, with far superior performance in a mouse model of acute lymphoblastic leukemia. Avoids tonic CAR signaling, allows effective internalization/re-expression after repeated antigen exposure, delays effector T-cell differentiation and exhaustion.';
update public_safe_harbors_staging set tissue_context = 'Human peripheral blood T cells; in vivo mouse leukemia model' where source_pmid = '28225754' and evidence_summary = 'FOUNDING PAPER for using TRAC in CAR-T (Eyquem et al., highly cited). Anti-CD19 CAR directed to the TRAC locus (not random integration): uniform CAR expression in human peripheral blood T cells, increased potency vs. conventional CAR-T, with far superior performance in a mouse model of acute lymphoblastic leukemia. Avoids tonic CAR signaling, allows effective internalization/re-expression after repeated antigen exposure, delays effector T-cell differentiation and exhaustion.';

update known_safe_harbors set tissue_context = 'Human T cells; in vivo mouse tumor model' where source_pmid = '28237835' and evidence_summary = 'Anti-CD19 CAR inserted directly into the native TRAC locus via homing endonuclease + AAV donor template. Resulting cells do not express the endogenous TCR, show potent effector functions in vitro, and eliminate CD19+ tumors in a mouse model in vivo -- specifically designed for allogeneic production (avoids GvHD by eliminating the endogenous TCR through the insertion itself).';
update public_safe_harbors_staging set tissue_context = 'Human T cells; in vivo mouse tumor model' where source_pmid = '28237835' and evidence_summary = 'Anti-CD19 CAR inserted directly into the native TRAC locus via homing endonuclease + AAV donor template. Resulting cells do not express the endogenous TCR, show potent effector functions in vitro, and eliminate CD19+ tumors in a mouse model in vivo -- specifically designed for allogeneic production (avoids GvHD by eliminating the endogenous TCR through the insertion itself).';

update known_safe_harbors set tissue_context = 'Human T cells; mouse xenograft leukemia model' where source_pmid = '35573047' and evidence_summary = 'Virus-free editing method (CRISPR-Cas + double-stranded DNA template) optimized for CAR insertion at TRAC, combining DNA-sensor inhibition with HDR potentiation -- CAR knock-in rates at TRAC above 50% of cells. Resulting CAR-T cells showed antigen-specific cytotoxicity and cytokine production in vitro, and slowed leukemia progression in a mouse xenograft model. Amplicon sequencing revealed no significant indel formation at potential off-target sites.';
update public_safe_harbors_staging set tissue_context = 'Human T cells; mouse xenograft leukemia model' where source_pmid = '35573047' and evidence_summary = 'Virus-free editing method (CRISPR-Cas + double-stranded DNA template) optimized for CAR insertion at TRAC, combining DNA-sensor inhibition with HDR potentiation -- CAR knock-in rates at TRAC above 50% of cells. Resulting CAR-T cells showed antigen-specific cytotoxicity and cytokine production in vitro, and slowed leukemia progression in a mouse xenograft model. Amplicon sequencing revealed no significant indel formation at potential off-target sites.';

update known_safe_harbors set tissue_context = 'Jurkat T cells' where source_pmid = '27271519' and evidence_summary = 'CELiD (AAV-dependent) vector for CAR integration at AAVS1 in Jurkat cells: of 71 stably transfected clones tested, 30 contained the CAR gene within the AAVS1 site -- site-specific integration efficiency of 42.2%, quantified by nested PCR, sequencing, and Southern blot.';
update public_safe_harbors_staging set tissue_context = 'Jurkat T cells' where source_pmid = '27271519' and evidence_summary = 'CELiD (AAV-dependent) vector for CAR integration at AAVS1 in Jurkat cells: of 71 stably transfected clones tested, 30 contained the CAR gene within the AAVS1 site -- site-specific integration efficiency of 42.2%, quantified by nested PCR, sequencing, and Southern blot.';

update known_safe_harbors set tissue_context = 'Mechanistic/structural study, not cell-type specific; open conformation also confirmed in transgenic mice' where source_pmid = '10906224' and evidence_summary = 'Founding mechanistic paper (2000), explains WHY AAVS1 works: the Rep binding site (RBS) within AAVS1 is located near a DNase-I-hypersensitive "open" chromatin region, with enhancer-like transcriptional properties -- a "transcriptionally competent environment" that explains the locus''s accessibility to integration and AAV Rep proteins. Open conformation also confirmed in transgenic mice carrying the AAVS1 fragment.';
update public_safe_harbors_staging set tissue_context = 'Mechanistic/structural study, not cell-type specific; open conformation also confirmed in transgenic mice' where source_pmid = '10906224' and evidence_summary = 'Founding mechanistic paper (2000), explains WHY AAVS1 works: the Rep binding site (RBS) within AAVS1 is located near a DNase-I-hypersensitive "open" chromatin region, with enhancer-like transcriptional properties -- a "transcriptionally competent environment" that explains the locus''s accessibility to integration and AAV Rep proteins. Open conformation also confirmed in transgenic mice carrying the AAVS1 fragment.';

update known_safe_harbors set tissue_context = 'Endogenous locus biology, not a specific cell type -- systemic metabolic effect (vitamin B12 pathway)' where source_pmid = '40108300' and evidence_summary = 'Important biological caveat (not transgene expression data, this is endogenous locus biology): CLYBL encodes a real enzyme with its own function -- it repairs malyl-CoA, a citric-acid-cycle byproduct, preventing inhibition of methylmalonyl-CoA mutase and vitamin B12 depletion. CLYBL knockout has a real, measurable metabolic consequence, though apparently tolerable in the safe-harbor studies already on record. Worth not treating CLYBL as "neutral" without qualification.';
update public_safe_harbors_staging set tissue_context = 'Endogenous locus biology, not a specific cell type -- systemic metabolic effect (vitamin B12 pathway)' where source_pmid = '40108300' and evidence_summary = 'Important biological caveat (not transgene expression data, this is endogenous locus biology): CLYBL encodes a real enzyme with its own function -- it repairs malyl-CoA, a citric-acid-cycle byproduct, preventing inhibition of methylmalonyl-CoA mutase and vitamin B12 depletion. CLYBL knockout has a real, measurable metabolic consequence, though apparently tolerable in the safe-harbor studies already on record. Worth not treating CLYBL as "neutral" without qualification.';

update known_safe_harbors set tissue_context = 'Human T cells (anti-GD2 CAR-T, neuroblastoma target)' where source_pmid = '40123742' and evidence_summary = 'Cas9-CLIPT system (circular plasmid linearized in vitro by Cas9-RNP itself) for non-viral insertion at TRAC: up to 60% precise knock-in efficiency with NHEJ inhibition, even with large transgenes (2-6kb). Resulting anti-GD2 CAR-T cells (neuroblastoma) were potent, with a phenotype enriched in stem-cell memory.';
update public_safe_harbors_staging set tissue_context = 'Human T cells (anti-GD2 CAR-T, neuroblastoma target)' where source_pmid = '40123742' and evidence_summary = 'Cas9-CLIPT system (circular plasmid linearized in vitro by Cas9-RNP itself) for non-viral insertion at TRAC: up to 60% precise knock-in efficiency with NHEJ inhibition, even with large transgenes (2-6kb). Resulting anti-GD2 CAR-T cells (neuroblastoma) were potent, with a phenotype enriched in stem-cell memory.';

update known_safe_harbors set tissue_context = 'Real CAR-T patients, longitudinal in vivo follow-up (T cells)' where source_pmid = '39972592' and evidence_summary = 'Real longitudinal analysis in CAR-T patients: lentiviral integration concentrated in introns, with no major clonal proliferation after 1 year. Gammaretroviral integration concentrated in intergenic regions near transcription start sites -- divergent outcomes: one patient with no detectable CAR after 1 year, another with low-level oligoclonal persistence (future malignancy risk still unclear).';
update public_safe_harbors_staging set tissue_context = 'Real CAR-T patients, longitudinal in vivo follow-up (T cells)' where source_pmid = '39972592' and evidence_summary = 'Real longitudinal analysis in CAR-T patients: lentiviral integration concentrated in introns, with no major clonal proliferation after 1 year. Gammaretroviral integration concentrated in intergenic regions near transcription start sites -- divergent outcomes: one patient with no detectable CAR after 1 year, another with low-level oligoclonal persistence (future malignancy risk still unclear).';

update known_safe_harbors set tissue_context = 'Real patient cohort (449 patients), clinical follow-up -- T cells (CAR-T)' where source_pmid = '38266761' and evidence_summary = 'Real cohort of 449 patients treated with commercial CAR-T (CD19, BCMA): 3.6% developed a secondary malignancy at a median follow-up of 10.3 months; projected 5-year cumulative incidence of 15.2% (solid) and 2.3% (hematologic). Only 1 case of T-cell lymphoma effectively linked to the CAR (low transgene levels, pre-existing clone before infusion) -- authors'' conclusion: low risk of T-cell lymphoma attributable to CAR-T itself.';
update public_safe_harbors_staging set tissue_context = 'Real patient cohort (449 patients), clinical follow-up -- T cells (CAR-T)' where source_pmid = '38266761' and evidence_summary = 'Real cohort of 449 patients treated with commercial CAR-T (CD19, BCMA): 3.6% developed a secondary malignancy at a median follow-up of 10.3 months; projected 5-year cumulative incidence of 15.2% (solid) and 2.3% (hematologic). Only 1 case of T-cell lymphoma effectively linked to the CAR (low transgene levels, pre-existing clone before infusion) -- authors'' conclusion: low risk of T-cell lymphoma attributable to CAR-T itself.';

update known_safe_harbors set tissue_context = 'Real patient case (T cells), phase 1 clinical trial' where source_pmid = '33974080' and evidence_summary = 'REAL CLINICAL CASE, phase 1 trial: 2 patients developed lymphoma derived from CAR-modified T cells using the piggyBac transposon system (untargeted integration). Analysis of the first lymphoma: elevated transgene copy number, BUT no insertion in typical oncogenes -- the malignancy correlated more with copy number and unrelated structural genomic alterations than with the insertion site itself. The transgene promoter activated transcription of surrounding regions despite insulator sequences. One patient died.';
update public_safe_harbors_staging set tissue_context = 'Real patient case (T cells), phase 1 clinical trial' where source_pmid = '33974080' and evidence_summary = 'REAL CLINICAL CASE, phase 1 trial: 2 patients developed lymphoma derived from CAR-modified T cells using the piggyBac transposon system (untargeted integration). Analysis of the first lymphoma: elevated transgene copy number, BUT no insertion in typical oncogenes -- the malignancy correlated more with copy number and unrelated structural genomic alterations than with the insertion site itself. The transgene promoter activated transcription of surrounding regions despite insulator sequences. One patient died.';

update known_safe_harbors set tissue_context = 'Real patient cohort (T cells), clinical case series' where source_pmid = '34010392' and evidence_summary = 'Related/companion report to the case above: 2 of 10 patients treated with piggyBac-modified CD19 CAR-T cells developed CAR-T-cell lymphoma. Low confidence as the full abstract could not be obtained -- only the title and exact count (2/10) are confirmed.';
update public_safe_harbors_staging set tissue_context = 'Real patient cohort (T cells), clinical case series' where source_pmid = '34010392' and evidence_summary = 'Related/companion report to the case above: 2 of 10 patients treated with piggyBac-modified CD19 CAR-T cells developed CAR-T-cell lymphoma. Low confidence as the full abstract could not be obtained -- only the title and exact count (2/10) are confirmed.';

update known_safe_harbors set tissue_context = 'Real patient (T cells), clinical case report' where source_pmid = '31387880' and evidence_summary = 'Clonal expansion of CAR-T cells harboring lentiviral integration in the CBL gene following anti-CD22 CAR-T therapy -- a concerning proliferation signal linked to random integration at a specific gene. Low confidence as the full abstract could not be obtained, only the title.';
update public_safe_harbors_staging set tissue_context = 'Real patient (T cells), clinical case report' where source_pmid = '31387880' and evidence_summary = 'Clonal expansion of CAR-T cells harboring lentiviral integration in the CBL gene following anti-CD22 CAR-T therapy -- a concerning proliferation signal linked to random integration at a specific gene. Low confidence as the full abstract could not be obtained, only the title.';

update known_safe_harbors set tissue_context = 'Human CD4+ T cells' where source_pmid = '26755332' and evidence_summary = 'Direct comparison of 4 systems in human CD4+ T cells: the Sleeping Beauty (SB) transposon showed the distribution closest to true randomness -- "highest theoretical probability of hitting a safe-harbor locus by chance" of the 4 systems. piggyBac and MLV retrovirus showed unexpectedly similar patterns to each other, enriched near transcription start sites, colocalizing with BRD4-associated sites -- a convergent "tethering" mechanism that preferentially directs them toward active genes (riskier).';
update public_safe_harbors_staging set tissue_context = 'Human CD4+ T cells' where source_pmid = '26755332' and evidence_summary = 'Direct comparison of 4 systems in human CD4+ T cells: the Sleeping Beauty (SB) transposon showed the distribution closest to true randomness -- "highest theoretical probability of hitting a safe-harbor locus by chance" of the 4 systems. piggyBac and MLV retrovirus showed unexpectedly similar patterns to each other, enriched near transcription start sites, colocalizing with BRD4-associated sites -- a convergent "tethering" mechanism that preferentially directs them toward active genes (riskier).';

update known_safe_harbors set tissue_context = 'Cell lines and primary human fibroblasts/keratinocytes' where source_pmid = '21468003' and evidence_summary = 'Hybrid HIV-1/SB100X vector: integration up to 160x above background in cell lines and in primary human fibroblasts/keratinocytes. Lentiviral integrations showed a strong bias toward actively transcribed genes; in contrast, SB100X-mediated integrations from the same vector were far more gene-random -- confirms the safer profile of SB100X vs. conventional lentiviral integration.';
update public_safe_harbors_staging set tissue_context = 'Cell lines and primary human fibroblasts/keratinocytes' where source_pmid = '21468003' and evidence_summary = 'Hybrid HIV-1/SB100X vector: integration up to 160x above background in cell lines and in primary human fibroblasts/keratinocytes. Lentiviral integrations showed a strong bias toward actively transcribed genes; in contrast, SB100X-mediated integrations from the same vector were far more gene-random -- confirms the safer profile of SB100X vs. conventional lentiviral integration.';

update known_safe_harbors set tissue_context = 'Real patient cohort (10 patients), hematopoietic stem cells -- historical SCID-X1 gene therapy trial' where source_pmid = '18688286' and evidence_summary = 'THE FOUNDING CASE of the entire safe-harbor field: gene therapy trial for SCID-X1 (10 patients). A gammaretroviral vector integrated 35kb upstream of the LMO2 proto-oncogene, in antisense orientation, causing LMO2 overexpression in the leukemic clone. Leukemogenesis also required additional acquired mutations (NOTCH1 gain-of-function, CDKN2A deletion, TCR-beta/STIL-TAL1 translocation) -- it was not the insertion alone, but the insertion was the initial trigger. This is the historical incident that justifies the existence of this entire safe-harbor catalog.';
update public_safe_harbors_staging set tissue_context = 'Real patient cohort (10 patients), hematopoietic stem cells -- historical SCID-X1 gene therapy trial' where source_pmid = '18688286' and evidence_summary = 'THE FOUNDING CASE of the entire safe-harbor field: gene therapy trial for SCID-X1 (10 patients). A gammaretroviral vector integrated 35kb upstream of the LMO2 proto-oncogene, in antisense orientation, causing LMO2 overexpression in the leukemic clone. Leukemogenesis also required additional acquired mutations (NOTCH1 gain-of-function, CDKN2A deletion, TCR-beta/STIL-TAL1 translocation) -- it was not the insertion alone, but the insertion was the initial trigger. This is the historical incident that justifies the existence of this entire safe-harbor catalog.';

-- (batches 10-12 tissue_context complete -- 19/19 records)
