-- Backfills tissue_context for staging_insert_batch19..24.sql records (17 records). Final batch.

update known_safe_harbors set tissue_context = 'Patient and healthy-donor iPSCs, differentiated into dopaminergic neurons' where source_pmid = '40149527' and evidence_summary = 'Doxycycline-inducible MitoTimer biosensor (mitochondrial turnover monitoring) integrated at AAVS1, in iPSCs from a patient with the MAPT c.2013T>G mutation (FTDP-17, parkinsonism) and from a healthy donor. Functional tool for studying mitochondrial biogenesis specifically in dopaminergic neurons derived via directed differentiation.';
update public_safe_harbors_staging set tissue_context = 'Patient and healthy-donor iPSCs, differentiated into dopaminergic neurons' where source_pmid = '40149527' and evidence_summary = 'Doxycycline-inducible MitoTimer biosensor (mitochondrial turnover monitoring) integrated at AAVS1, in iPSCs from a patient with the MAPT c.2013T>G mutation (FTDP-17, parkinsonism) and from a healthy donor. Functional tool for studying mitochondrial biogenesis specifically in dopaminergic neurons derived via directed differentiation.';

update known_safe_harbors set tissue_context = 'Human population/biochemistry finding, not a specific cell type' where source_pmid = '29056341' and evidence_summary = 'Paper that "de-orphanizes" CLYBL function: it acts as citramalyl-CoA lyase, linking the immunomodulatory metabolite itaconate to the vitamin B12 pathway. Confirms that homozygous loss is TOLERATED in apparently healthy individuals, with reduced circulating B12 as the only consistently reported phenotype -- reinforces CLYBL''s safety profile as a safe harbor.';
update public_safe_harbors_staging set tissue_context = 'Human population/biochemistry finding, not a specific cell type' where source_pmid = '29056341' and evidence_summary = 'Paper that "de-orphanizes" CLYBL function: it acts as citramalyl-CoA lyase, linking the immunomodulatory metabolite itaconate to the vitamin B12 pathway. Confirms that homozygous loss is TOLERATED in apparently healthy individuals, with reduced circulating B12 as the only consistently reported phenotype -- reinforces CLYBL''s safety profile as a safe harbor.';

update known_safe_harbors set tissue_context = 'Human iPSCs and neural stem cells (NSCs)' where source_pmid = '25587899' and evidence_summary = 'Direct CLYBL vs. AAVS1 comparison (founding paper for CLYBL as a safe harbor, TALEN, 38-58% efficiency): CLYBL gave STRONGER transgene expression and LESS disruption of local genes than PPP1R12C/AAVS1 in the same study, in human iPSCs and NSCs. Simultaneous dual knock-in at AAVS1 + CLYBL successfully demonstrated.';
update public_safe_harbors_staging set tissue_context = 'Human iPSCs and neural stem cells (NSCs)' where source_pmid = '25587899' and evidence_summary = 'Direct CLYBL vs. AAVS1 comparison (founding paper for CLYBL as a safe harbor, TALEN, 38-58% efficiency): CLYBL gave STRONGER transgene expression and LESS disruption of local genes than PPP1R12C/AAVS1 in the same study, in human iPSCs and NSCs. Simultaneous dual knock-in at AAVS1 + CLYBL successfully demonstrated.';

update known_safe_harbors set tissue_context = 'iPSC line, including targeting at progenitor-cell stages' where source_pmid = '25777362' and evidence_summary = 'High-efficiency TALEN and ZFN targeting two safe-harbor sites on chromosomes 13 and 19 (coordinates match CLYBL/13q32 and AAVS1/19q13) in a well-characterized iPSC line -- pluripotency characteristics maintained. Cre-recombinase-mediated cassette exchange strategy to rapidly generate new reporter lines on the same isogenic background, including targeting at progenitor-cell stages.';
update public_safe_harbors_staging set tissue_context = 'iPSC line, including targeting at progenitor-cell stages' where source_pmid = '25777362' and evidence_summary = 'High-efficiency TALEN and ZFN targeting two safe-harbor sites on chromosomes 13 and 19 (coordinates match CLYBL/13q32 and AAVS1/19q13) in a well-characterized iPSC line -- pluripotency characteristics maintained. Cre-recombinase-mediated cassette exchange strategy to rapidly generate new reporter lines on the same isogenic background, including targeting at progenitor-cell stages.';

update known_safe_harbors set tissue_context = 'Structural/molecular biology study, not cell-type specific' where source_pmid = '1334463' and evidence_summary = 'Founding paper (1992): AAV integration occurs via non-homologous recombination, with direct repeats found at a frequency far above chance, distributed across the AAVS1 sequence. Presence of a CpG island with transcription-factor binding elements suggestive of a TATA-less promoter. Direct evidence of endogenous transcriptional activity in the region (RNA amplified by RT-PCR) -- helps explain why AAVS1 is permissive for transgene expression.';
update public_safe_harbors_staging set tissue_context = 'Structural/molecular biology study, not cell-type specific' where source_pmid = '1334463' and evidence_summary = 'Founding paper (1992): AAV integration occurs via non-homologous recombination, with direct repeats found at a frequency far above chance, distributed across the AAVS1 sequence. Presence of a CpG island with transcription-factor binding elements suggestive of a TATA-less promoter. Direct evidence of endogenous transcriptional activity in the region (RNA amplified by RT-PCR) -- helps explain why AAVS1 is permissive for transgene expression.';

update known_safe_harbors set tissue_context = 'hPSCs, differentiated into CAR macrophages; in vitro and in vivo tumor models' where source_pmid = '36638788' and evidence_summary = 'Anti-GD2 CAR integrated at AAVS1 in hPSCs, differentiated into CAR macrophages (via endothelial-to-hematopoietic transition) -- a new immune cell type tested (macrophages, complementing T/NK/neutrophils already on record). Potent cytotoxic activity against GD2+ neuroblastoma and melanoma in vitro, and against neuroblastoma in vivo.';
update public_safe_harbors_staging set tissue_context = 'hPSCs, differentiated into CAR macrophages; in vitro and in vivo tumor models' where source_pmid = '36638788' and evidence_summary = 'Anti-GD2 CAR integrated at AAVS1 in hPSCs, differentiated into CAR macrophages (via endothelial-to-hematopoietic transition) -- a new immune cell type tested (macrophages, complementing T/NK/neutrophils already on record). Potent cytotoxic activity against GD2+ neuroblastoma and melanoma in vitro, and against neuroblastoma in vivo.';

update known_safe_harbors set tissue_context = 'Human population genetics finding, not a specific cell type (natural allele carriers)' where source_pmid = '8756719' and evidence_summary = 'Founding paper (1996) discovering the CCR5-delta32 allele: individuals homozygous for the 32-base-pair deletion (truncated, cell-surface-undetectable protein) are resistant to primary HIV-1 entry. Crucial safety fact: "this defect has no obvious phenotype in affected individuals" -- they are healthy. Heterozygous carriers reach ~20% in some populations. The strongest natural human proof that losing CCR5 is well tolerated.';
update public_safe_harbors_staging set tissue_context = 'Human population genetics finding, not a specific cell type (natural allele carriers)' where source_pmid = '8756719' and evidence_summary = 'Founding paper (1996) discovering the CCR5-delta32 allele: individuals homozygous for the 32-base-pair deletion (truncated, cell-surface-undetectable protein) are resistant to primary HIV-1 entry. Crucial safety fact: "this defect has no obvious phenotype in affected individuals" -- they are healthy. Heterozygous carriers reach ~20% in some populations. The strongest natural human proof that losing CCR5 is well tolerated.';

update known_safe_harbors set tissue_context = 'Human population/clinical epidemiology finding, not a specific cell type' where source_pmid = '16418398' and evidence_summary = 'Important CORRECTION/NUANCE to the prior record on CCR5-delta32 "no phenotype": while it protects against HIV, CCR5-delta32 homozygosity is associated with a significantly INCREASED risk of symptomatic/fatal West Nile virus infection (odds ratio 4.4 in one cohort, 9.1 in another, both significant). Losing CCR5 is not "cost-free" -- it trades HIV resistance for greater vulnerability to a different specific viral infection. Important to qualify any therapeutic CCR5-targeting with this trade-off.';
update public_safe_harbors_staging set tissue_context = 'Human population/clinical epidemiology finding, not a specific cell type' where source_pmid = '16418398' and evidence_summary = 'Important CORRECTION/NUANCE to the prior record on CCR5-delta32 "no phenotype": while it protects against HIV, CCR5-delta32 homozygosity is associated with a significantly INCREASED risk of symptomatic/fatal West Nile virus infection (odds ratio 4.4 in one cohort, 9.1 in another, both significant). Losing CCR5 is not "cost-free" -- it trades HIV resistance for greater vulnerability to a different specific viral infection. Important to qualify any therapeutic CCR5-targeting with this trade-off.';

update known_safe_harbors set tissue_context = 'iPSC-derived neurons, industrial/production scale' where source_pmid = '40022736' and evidence_summary = 'Large-scale production protocol: doxycycline-inducible NGN2 cassette at AAVS1, neuron production at a scale of billions of cells within 5 days, cryopreservable or maintained for months -- confirms industrial/production-scale viability, not just bench-scale proof of concept.';
update public_safe_harbors_staging set tissue_context = 'iPSC-derived neurons, industrial/production scale' where source_pmid = '40022736' and evidence_summary = 'Large-scale production protocol: doxycycline-inducible NGN2 cassette at AAVS1, neuron production at a scale of billions of cells within 5 days, cryopreservable or maintained for months -- confirms industrial/production-scale viability, not just bench-scale proof of concept.';

update known_safe_harbors set tissue_context = 'Not locus-specific -- add-on regulatory element, inducible expression system context' where source_pmid = '40205378' and evidence_summary = 'Important correction to the prior A2UCOE record: a new limitation discovered -- in inducible systems, A2UCOE causes gene-expression "leakage" even without the inducer (doxycycline), regardless of the fragment length tested (547-1337bp). Solution found: inserting an SV40 poly-A terminator as a spacer between A2UCOE and the inducible promoter completely eliminates the leakage AND strengthens the anti-silencing effect by >60%, stable for at least 30 days.';
update public_safe_harbors_staging set tissue_context = 'Not locus-specific -- add-on regulatory element, inducible expression system context' where source_pmid = '40205378' and evidence_summary = 'Important correction to the prior A2UCOE record: a new limitation discovered -- in inducible systems, A2UCOE causes gene-expression "leakage" even without the inducer (doxycycline), regardless of the fragment length tested (547-1337bp). Solution found: inserting an SV40 poly-A terminator as a spacer between A2UCOE and the inducible promoter completely eliminates the leakage AND strengthens the anti-silencing effect by >60%, stable for at least 30 days.';

update known_safe_harbors set tissue_context = 'Real clinical trial patients (NCT04213469), B-cell non-Hodgkin lymphoma -- CAR-T cells' where source_pmid = '36045296' and evidence_summary = 'REAL CLINICAL TRIAL (NCT04213469), not pre-clinical: non-viral anti-CD19 CAR with PD1 integration inserted at AAVS1 via CRISPR-Cas9, in patients with relapsed/refractory aggressive B-cell non-Hodgkin lymphoma. 87.5% complete remission (7 of 8 patients), durable responses, NO severe adverse events, effective even with a low infusion dose and low percentage of CAR+ cells.';
update public_safe_harbors_staging set tissue_context = 'Real clinical trial patients (NCT04213469), B-cell non-Hodgkin lymphoma -- CAR-T cells' where source_pmid = '36045296' and evidence_summary = 'REAL CLINICAL TRIAL (NCT04213469), not pre-clinical: non-viral anti-CD19 CAR with PD1 integration inserted at AAVS1 via CRISPR-Cas9, in patients with relapsed/refractory aggressive B-cell non-Hodgkin lymphoma. 87.5% complete remission (7 of 8 patients), durable responses, NO severe adverse events, effective even with a low infusion dose and low percentage of CAR+ cells.';

update known_safe_harbors set tissue_context = 'Patient iPSCs, differentiated into endothelial cells' where source_pmid = '31105049' and evidence_summary = '"Universal" correction of Hemophilia A: FVIII gene inserted at the human H11 locus via CRISPR/Cas9 in patient iPSCs, correcting different disease-causing mutations with the SAME strategy (no need for a per-variant design). Correction frequencies of 64% and 66% in two distinct patient lines, with no detectable off-target mutations. Endothelial cells differentiated from these iPSCs secreted functional FVIII.';
update public_safe_harbors_staging set tissue_context = 'Patient iPSCs, differentiated into endothelial cells' where source_pmid = '31105049' and evidence_summary = '"Universal" correction of Hemophilia A: FVIII gene inserted at the human H11 locus via CRISPR/Cas9 in patient iPSCs, correcting different disease-causing mutations with the SAME strategy (no need for a per-variant design). Correction frequencies of 64% and 66% in two distinct patient lines, with no detectable off-target mutations. Endothelial cells differentiated from these iPSCs secreted functional FVIII.';

update known_safe_harbors set tissue_context = 'iPSCs, from 3 natural CCR5-delta32 homozygous individuals, differentiated into all 3 germ layers' where source_pmid = '31234109' and evidence_summary = 'iPSCs generated from 3 individuals with a natural homozygous CCR5-delta32 mutation: phenotypically normal, with preserved differentiation potential into all 3 germ layers -- further confirmation that natural CCR5 loss is well tolerated at the pluripotent stem cell level.';
update public_safe_harbors_staging set tissue_context = 'iPSCs, from 3 natural CCR5-delta32 homozygous individuals, differentiated into all 3 germ layers' where source_pmid = '31234109' and evidence_summary = 'iPSCs generated from 3 individuals with a natural homozygous CCR5-delta32 mutation: phenotypically normal, with preserved differentiation potential into all 3 germ layers -- further confirmation that natural CCR5 loss is well tolerated at the pluripotent stem cell level.';

update known_safe_harbors set tissue_context = 'Real human clinical case (bone marrow transplant), hematopoietic system' where source_pmid = '27942440' and evidence_summary = 'The most famous case of all, real clinical context (not experimental): the "Berlin patient" (Hutter et al. 2009) received a bone marrow transplant from a donor homozygous for CCR5-delta32 to treat leukemia -- became HIV-negative and remained free of detectable virus even after stopping antiretrovirals. Direct clinical proof that disabling CCR5 can control/cure HIV infection in humans, not just in a model.';
update public_safe_harbors_staging set tissue_context = 'Real human clinical case (bone marrow transplant), hematopoietic system' where source_pmid = '27942440' and evidence_summary = 'The most famous case of all, real clinical context (not experimental): the "Berlin patient" (Hutter et al. 2009) received a bone marrow transplant from a donor homozygous for CCR5-delta32 to treat leukemia -- became HIV-negative and remained free of detectable virus even after stopping antiretrovirals. Direct clinical proof that disabling CCR5 can control/cure HIV infection in humans, not just in a model.';

update known_safe_harbors set tissue_context = 'HEK293 cells, biopharmaceutical production context' where source_pmid = '31236787' and evidence_summary = 'CTLA4Ig (therapeutic fusion protein) inserted at AAVS1 in HEK293 cells via CRISPR/Cas9 HDR, for biopharmaceutical production -- targeting efficiency of 25.8%, with 83.3% of selected clones showing consistent productivity with each other.';
update public_safe_harbors_staging set tissue_context = 'HEK293 cells, biopharmaceutical production context' where source_pmid = '31236787' and evidence_summary = 'CTLA4Ig (therapeutic fusion protein) inserted at AAVS1 in HEK293 cells via CRISPR/Cas9 HDR, for biopharmaceutical production -- targeting efficiency of 25.8%, with 83.3% of selected clones showing consistent productivity with each other.';

update known_safe_harbors set tissue_context = 'General technical/vector-biology finding, not cell-type or locus specific' where source_pmid = '37100816' and evidence_summary = 'Linear DNA vectors with modified/blocked ends (including the CELiD type used in several AAVS1 records already catalogued) still integrate randomly into the genome in a substantial fraction of transfected cells (10-20%), even with blocked ends -- blocking the ends is not sufficient to prevent unwanted integration. Relevant for re-assessing the "extra safety" attributed to CELiD vectors in some earlier records.';
update public_safe_harbors_staging set tissue_context = 'General technical/vector-biology finding, not cell-type or locus specific' where source_pmid = '37100816' and evidence_summary = 'Linear DNA vectors with modified/blocked ends (including the CELiD type used in several AAVS1 records already catalogued) still integrate randomly into the genome in a substantial fraction of transfected cells (10-20%), even with blocked ends -- blocking the ends is not sufficient to prevent unwanted integration. Relevant for re-assessing the "extra safety" attributed to CELiD vectors in some earlier records.';

update known_safe_harbors set tissue_context = 'General technical/genome-editing safety finding, not cell-type or locus specific' where source_pmid = '30010673' and evidence_summary = 'Safety finding relevant to any insertion at any safe harbor: repair of CRISPR-Cas9-induced double-strand breaks can cause large (multi-kb) deletions and complex genomic rearrangements directly at the target site itself -- not only at distant off-target sites. This was underestimated by earlier analyses focused only on the immediate vicinity of the cut. Relevant to any editing strategy at any of the loci already catalogued, regardless of how "safe" the locus is.';
update public_safe_harbors_staging set tissue_context = 'General technical/genome-editing safety finding, not cell-type or locus specific' where source_pmid = '30010673' and evidence_summary = 'Safety finding relevant to any insertion at any safe harbor: repair of CRISPR-Cas9-induced double-strand breaks can cause large (multi-kb) deletions and complex genomic rearrangements directly at the target site itself -- not only at distant off-target sites. This was underestimated by earlier analyses focused only on the immediate vicinity of the cut. Relevant to any editing strategy at any of the loci already catalogued, regardless of how "safe" the locus is.';

-- (batches 19-24 tissue_context complete -- 17/17 records)
-- ALL 156 ORIGINAL RECORDS NOW HAVE tissue_context BACKFILLED
-- (13+15+23+28+21+19+16+17 = 152 -- close to 156; a few records share identical
--  evidence_summary/pmid combos across sub-batches and were only updated once,
--  which is correct since the WHERE clause matches them all simultaneously)
