-- Translation + stability for staging_insert_batch2.sql (15 records, PMID 41511364, review-derived).

update known_safe_harbors set evidence_summary = 'Cytogenetic band 19q13.4, intron 1 of PPP1R12C. Robust expression in hESCs/iPSCs without compromising pluripotency, but risk of silencing in cardiomyocytes, endothelial cells, myeloid cells, and hepatocytes, and in Jurkat T cells. Disrupts expression of PPP1R12C, TNNI3, and PPP6R1 (dense gene region). Via secondary review, not verified against the primary article.', stability = 'Robust in hPSCs; silencing risk after differentiation into cardiomyocytes/endothelial/myeloid/hepatocyte lineages' where source_pmid = '41511364' and evidence_summary = 'Banda 19q13.4, intrão 1 do gene PPP1R12C. Expressão robusta em hESCs/iPSCs sem comprometer pluripotência, mas risco de silenciamento em cardiomiócitos, células endoteliais, mieloides e hepatócitos, e em células Jurkat T. Perturba expressão de PPP1R12C, TNNI3 e PPP6R1 (região génica densa). Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 19q13.4, intron 1 of PPP1R12C. Robust expression in hESCs/iPSCs without compromising pluripotency, but risk of silencing in cardiomyocytes, endothelial cells, myeloid cells, and hepatocytes, and in Jurkat T cells. Disrupts expression of PPP1R12C, TNNI3, and PPP6R1 (dense gene region). Via secondary review, not verified against the primary article.', stability = 'Robust in hPSCs; silencing risk after differentiation into cardiomyocytes/endothelial/myeloid/hepatocyte lineages' where source_pmid = '41511364' and evidence_summary = 'Banda 19q13.4, intrão 1 do gene PPP1R12C. Expressão robusta em hESCs/iPSCs sem comprometer pluripotência, mas risco de silenciamento em cardiomiócitos, células endoteliais, mieloides e hepatócitos, e em células Jurkat T. Perturba expressão de PPP1R12C, TNNI3 e PPP6R1 (região génica densa). Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 3p25.3 (hROSA26), intron 2 of THUMPD3. Stable expression in hESCs across multiple differentiation lineages; no silencing reported; used in HEK293 and hTERT-RPE1. Via secondary review, not verified against the primary article.', stability = 'Stable across differentiation lineages; no silencing reported' where source_pmid = '41511364' and evidence_summary = 'Banda 3p25.3 (hROSA26), intrão 2 do gene THUMPD3. Expressão estável em hESCs ao longo de múltiplas linhagens de diferenciação; sem silenciamento reportado; usado em HEK293 e hTERT-RPE1. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 3p25.3 (hROSA26), intron 2 of THUMPD3. Stable expression in hESCs across multiple differentiation lineages; no silencing reported; used in HEK293 and hTERT-RPE1. Via secondary review, not verified against the primary article.', stability = 'Stable across differentiation lineages; no silencing reported' where source_pmid = '41511364' and evidence_summary = 'Banda 3p25.3 (hROSA26), intrão 2 do gene THUMPD3. Expressão estável em hESCs ao longo de múltiplas linhagens de diferenciação; sem silenciamento reportado; usado em HEK293 e hTERT-RPE1. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 22q12.2, intergenic region between DRG1 and EIF4ENIF1. Stable expression of several transgenes in hiPSCs without silencing; supports recombinase-mediated cassette exchange (RMCE). Via secondary review, not verified against the primary article.', stability = 'Stable in hiPSCs; no silencing reported' where source_pmid = '41511364' and evidence_summary = 'Banda 22q12.2, região intergénica entre DRG1 e EIF4ENIF1. Expressão estável de vários transgenes em hiPSCs sem silenciamento; permite troca de cassete mediada por recombinase (RMCE). Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 22q12.2, intergenic region between DRG1 and EIF4ENIF1. Stable expression of several transgenes in hiPSCs without silencing; supports recombinase-mediated cassette exchange (RMCE). Via secondary review, not verified against the primary article.', stability = 'Stable in hiPSCs; no silencing reported' where source_pmid = '41511364' and evidence_summary = 'Banda 22q12.2, região intergénica entre DRG1 e EIF4ENIF1. Expressão estável de vários transgenes em hiPSCs sem silenciamento; permite troca de cassete mediada por recombinase (RMCE). Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 3p21.31. Low probability of transgene expression, with gradual decline observed -- weak performance compared to AAVS1/ROSA26/H11/CLYBL. Upregulates flanking genes CCR1 and CCR3. Increases susceptibility to West Nile virus infection (the CCR5-delta32 mutation confers HIV resistance but carries this cost). Via secondary review, not verified against the primary article.', stability = 'Gradual decline in expression -- weakest performer among the loci compared' where source_pmid = '41511364' and evidence_summary = 'Banda 3p21.31. Baixa probabilidade de expressão do transgene, com declínio gradual observado -- desempenho fraco comparado a AAVS1/ROSA26/H11/CLYBL. Sobre-regula genes flanqueadores CCR1 e CCR3. Aumenta suscetibilidade a infeção pelo vírus do Nilo Ocidental (a mutação CCR5-delta32 confere resistência a HIV mas tem este custo). Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 3p21.31. Low probability of transgene expression, with gradual decline observed -- weak performance compared to AAVS1/ROSA26/H11/CLYBL. Upregulates flanking genes CCR1 and CCR3. Increases susceptibility to West Nile virus infection (the CCR5-delta32 mutation confers HIV resistance but carries this cost). Via secondary review, not verified against the primary article.', stability = 'Gradual decline in expression -- weakest performer among the loci compared' where source_pmid = '41511364' and evidence_summary = 'Banda 3p21.31. Baixa probabilidade de expressão do transgene, com declínio gradual observado -- desempenho fraco comparado a AAVS1/ROSA26/H11/CLYBL. Sobre-regula genes flanqueadores CCR1 e CCR3. Aumenta suscetibilidade a infeção pelo vírus do Nilo Ocidental (a mutação CCR5-delta32 confere resistência a HIV mas tem este custo). Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 13q32.1, intron 2 of the CLYBL gene itself. "Robust and superior" expression compared to AAVS1 in hiPSCs and neural stem cells. Minimal disruption of local gene expression (~50x reduction of CLYBL itself). No silencing reported; preserves pluripotency markers and differentiation capacity. Via secondary review, not verified against the primary article.', stability = 'No silencing reported; robust across differentiation' where source_pmid = '41511364' and evidence_summary = 'Banda 13q32.1, intrão 2 do próprio gene CLYBL. Expressão "robusta e superior" comparada a AAVS1 em hiPSCs e estaminais neurais. Disrupção mínima da expressão local (~50x redução do próprio CLYBL). Sem silenciamento reportado; preserva marcadores de pluripotência e capacidade de diferenciação. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 13q32.1, intron 2 of the CLYBL gene itself. "Robust and superior" expression compared to AAVS1 in hiPSCs and neural stem cells. Minimal disruption of local gene expression (~50x reduction of CLYBL itself). No silencing reported; preserves pluripotency markers and differentiation capacity. Via secondary review, not verified against the primary article.', stability = 'No silencing reported; robust across differentiation' where source_pmid = '41511364' and evidence_summary = 'Banda 13q32.1, intrão 2 do próprio gene CLYBL. Expressão "robusta e superior" comparada a AAVS1 em hiPSCs e estaminais neurais. Disrupção mínima da expressão local (~50x redução do próprio CLYBL). Sem silenciamento reportado; preserva marcadores de pluripotência e capacidade de diferenciação. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 4q13.1, intergenic, identified via pseudo-sites of the mCreI homing endonuclease. Robust integration and stable transgene expression for >45 days in rhabdomyosarcoma cells. Supports functional genome editing (Cas9 expression, PAX3/FOXO1 deletion). Not yet evaluated in iPSCs. Via secondary review, not verified against the primary article.', stability = 'Stable >45 days in rhabdomyosarcoma cells; not yet tested in iPSCs' where source_pmid = '41511364' and evidence_summary = 'Banda 4q13.1, intergénico, identificado via pseudo-sítios da endonuclease de homing mCreI. Integração robusta e expressão estável do transgene por >45 dias em células de rabdomiossarcoma. Suporta edição genómica funcional (expressão de Cas9, deleção de PAX3/FOXO1). Não avaliado ainda em iPSCs. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 4q13.1, intergenic, identified via pseudo-sites of the mCreI homing endonuclease. Robust integration and stable transgene expression for >45 days in rhabdomyosarcoma cells. Supports functional genome editing (Cas9 expression, PAX3/FOXO1 deletion). Not yet evaluated in iPSCs. Via secondary review, not verified against the primary article.', stability = 'Stable >45 days in rhabdomyosarcoma cells; not yet tested in iPSCs' where source_pmid = '41511364' and evidence_summary = 'Banda 4q13.1, intergénico, identificado via pseudo-sítios da endonuclease de homing mCreI. Integração robusta e expressão estável do transgene por >45 dias em células de rabdomiossarcoma. Suporta edição genómica funcional (expressão de Cas9, deleção de PAX3/FOXO1). Não avaliado ainda em iPSCs. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 1q31.3, intergenic, discovered via computational screening. Robust, sustained mRuby expression for >90 days in HEK293T and Jurkat; >20 days in primary T cells; >25 days in fibroblasts. Silencing reported in iPSC applications; effect on pluripotency not assessed. Via secondary review, not verified against the primary article.', stability = 'Stable >90 days in cell lines; silencing reported in iPSC applications' where source_pmid = '41511364' and evidence_summary = 'Banda 1q31.3, intergénico, descoberto por triagem computacional. Expressão robusta e sustentada de mRuby por >90 dias em HEK293T e Jurkat; >20 dias em células T primárias; >25 dias em fibroblastos. Silenciamento reportado em aplicações de iPSC; efeito na pluripotência não avaliado. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 1q31.3, intergenic, discovered via computational screening. Robust, sustained mRuby expression for >90 days in HEK293T and Jurkat; >20 days in primary T cells; >25 days in fibroblasts. Silencing reported in iPSC applications; effect on pluripotency not assessed. Via secondary review, not verified against the primary article.', stability = 'Stable >90 days in cell lines; silencing reported in iPSC applications' where source_pmid = '41511364' and evidence_summary = 'Banda 1q31.3, intergénico, descoberto por triagem computacional. Expressão robusta e sustentada de mRuby por >90 dias em HEK293T e Jurkat; >20 dias em células T primárias; >25 dias em fibroblastos. Silenciamento reportado em aplicações de iPSC; efeito na pluripotência não avaliado. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 3p24.3, intergenic, computational discovery. Performance similar to Rogi1; outperforms AAVS1 and CCR5. "Minimal" effect on the global transcriptional profile in HEK293T and Jurkat. Downregulation of the JUN oncogene observed. Via secondary review, not verified against the primary article.', stability = 'Similar profile to Rogi1; minimal transcriptome disruption' where source_pmid = '41511364' and evidence_summary = 'Banda 3p24.3, intergénico, descoberta computacional. Desempenho semelhante ao Rogi1; supera AAVS1 e CCR5. Efeito "mínimo" no perfil transcricional global em HEK293T e Jurkat. Sub-regulação do oncogene JUN observada. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 3p24.3, intergenic, computational discovery. Performance similar to Rogi1; outperforms AAVS1 and CCR5. "Minimal" effect on the global transcriptional profile in HEK293T and Jurkat. Downregulation of the JUN oncogene observed. Via secondary review, not verified against the primary article.', stability = 'Similar profile to Rogi1; minimal transcriptome disruption' where source_pmid = '41511364' and evidence_summary = 'Banda 3p24.3, intergénico, descoberta computacional. Desempenho semelhante ao Rogi1; supera AAVS1 e CCR5. Efeito "mínimo" no perfil transcricional global em HEK293T e Jurkat. Sub-regulação do oncogene JUN observada. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 1p13.2, intergenic. Stable expression in hESCs and iPSCs, with constitutive and inducible promoters. Supports Bxb1-integrase-mediated cassette exchange. Expression maintained for >=15 passages through differentiation. Via secondary review, not verified against the primary article.', stability = 'Stable for >=15 passages through differentiation' where source_pmid = '41511364' and evidence_summary = 'Banda 1p13.2, intergénico. Expressão estável em hESCs e iPSCs, com promotores constitutivos e indutíveis. Suporta troca de cassete mediada por integrase Bxb1. Expressão mantida por >=15 passagens ao longo de diferenciação. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 1p13.2, intergenic. Stable expression in hESCs and iPSCs, with constitutive and inducible promoters. Supports Bxb1-integrase-mediated cassette exchange. Expression maintained for >=15 passages through differentiation. Via secondary review, not verified against the primary article.', stability = 'Stable for >=15 passages through differentiation' where source_pmid = '41511364' and evidence_summary = 'Banda 1p13.2, intergénico. Expressão estável em hESCs e iPSCs, com promotores constitutivos e indutíveis. Suporta troca de cassete mediada por integrase Bxb1. Expressão mantida por >=15 passagens ao longo de diferenciação. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 18q21.31, intergenic. Similar characteristics to Pansio-1; minimal transcriptional effects. No silencing reported; maintained through neural, hepatic, and cardiac differentiation. Via secondary review, not verified against the primary article.', stability = 'No silencing reported through neural/hepatic/cardiac differentiation' where source_pmid = '41511364' and evidence_summary = 'Banda 18q21.31, intergénico. Características semelhantes ao Pansio-1; efeitos transcricionais mínimos. Sem silenciamento reportado; mantido através de diferenciação neural, hepática e cardíaca. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 18q21.31, intergenic. Similar characteristics to Pansio-1; minimal transcriptional effects. No silencing reported; maintained through neural, hepatic, and cardiac differentiation. Via secondary review, not verified against the primary article.', stability = 'No silencing reported through neural/hepatic/cardiac differentiation' where source_pmid = '41511364' and evidence_summary = 'Banda 18q21.31, intergénico. Características semelhantes ao Pansio-1; efeitos transcricionais mínimos. Sem silenciamento reportado; mantido através de diferenciação neural, hepática e cardíaca. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 19p13.3, intergenic. Expression profile similar to Pansio-1 and Olonne-18. No impact on expression of the nearest gene (ZNRF4). Via secondary review, not verified against the primary article.', stability = 'No silencing reported' where source_pmid = '41511364' and evidence_summary = 'Banda 19p13.3, intergénico. Perfil de expressão semelhante a Pansio-1 e Olonne-18. Sem impacto na expressão do gene mais próximo (ZNRF4). Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 19p13.3, intergenic. Expression profile similar to Pansio-1 and Olonne-18. No impact on expression of the nearest gene (ZNRF4). Via secondary review, not verified against the primary article.', stability = 'No silencing reported' where source_pmid = '41511364' and evidence_summary = 'Banda 19p13.3, intergénico. Perfil de expressão semelhante a Pansio-1 e Olonne-18. Sem impacto na expressão do gene mais próximo (ZNRF4). Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 3p22.2, intronic in GOLGA4. Blood-lineage-specific locus. Stable expression in HUDEP2 erythroid progenitors, maintained after differentiation into mature erythrocytes. Via secondary review, not verified against the primary article.', stability = 'Stable through differentiation into mature erythrocytes' where source_pmid = '41511364' and evidence_summary = 'Banda 3p22.2, intrónico no gene GOLGA4. Locus especifico de linhagem sanguínea. Expressão estável em progenitores eritroides HUDEP2, mantida após diferenciação em eritrócitos maduros. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 3p22.2, intronic in GOLGA4. Blood-lineage-specific locus. Stable expression in HUDEP2 erythroid progenitors, maintained after differentiation into mature erythrocytes. Via secondary review, not verified against the primary article.', stability = 'Stable through differentiation into mature erythrocytes' where source_pmid = '41511364' and evidence_summary = 'Banda 3p22.2, intrónico no gene GOLGA4. Locus especifico de linhagem sanguínea. Expressão estável em progenitores eritroides HUDEP2, mantida após diferenciação em eritrócitos maduros. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 6q25.3, intronic in ARID1B. Validated in HUDEP2 cells, stability profile similar to BLD_SHS10. Via secondary review, not verified against the primary article.', stability = 'Similar stability profile to BLD_SHS10 (see correction in batch 7/PMID 36131352)' where source_pmid = '41511364' and evidence_summary = 'Banda 6q25.3, intrónico no gene ARID1B. Validado em células HUDEP2, perfil de estabilidade semelhante ao BLD_SHS10. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 6q25.3, intronic in ARID1B. Validated in HUDEP2 cells, stability profile similar to BLD_SHS10. Via secondary review, not verified against the primary article.', stability = 'Similar stability profile to BLD_SHS10 (see correction in batch 7/PMID 36131352)' where source_pmid = '41511364' and evidence_summary = 'Banda 6q25.3, intrónico no gene ARID1B. Validado em células HUDEP2, perfil de estabilidade semelhante ao BLD_SHS10. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 8q24.12, associated with TAF2. Experimental validation in blood progenitors still ongoing -- lower confidence than the rest of this list, as this work is stated as incomplete. Via secondary review, not verified against the primary article.', stability = 'Validation incomplete/ongoing' where source_pmid = '41511364' and evidence_summary = 'Banda 8q24.12, associado a TAF2. Validação experimental em progenitores sanguíneos ainda em curso -- confiança mais baixa que os restantes desta lista, por ser trabalho declarado como incompleto. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 8q24.12, associated with TAF2. Experimental validation in blood progenitors still ongoing -- lower confidence than the rest of this list, as this work is stated as incomplete. Via secondary review, not verified against the primary article.', stability = 'Validation incomplete/ongoing' where source_pmid = '41511364' and evidence_summary = 'Banda 8q24.12, associado a TAF2. Validação experimental em progenitores sanguíneos ainda em curso -- confiança mais baixa que os restantes desta lista, por ser trabalho declarado como incompleto. Via review, não verificado contra artigo primário.';

update known_safe_harbors set evidence_summary = 'Cytogenetic band 7q36.1, within the ZNF767P pseudogene. T-cell-specific discovery via ATAC-seq. Durable CAR expression over multiple weeks in CAR-CD19 T cells; preserves the native T-cell receptor; long-term leukemia control demonstrated in vivo. Via secondary review, not verified against the primary article.', stability = 'Durable over multiple weeks; long-term in vivo control demonstrated' where source_pmid = '41511364' and evidence_summary = 'Banda 7q36.1, dentro do pseudogene ZNF767P. Descoberta específica de células T via ATAC-seq. Expressão duradoura de CAR ao longo de múltiplas semanas em células T CAR-CD19; mantém o recetor de células T nativo; controlo de leucemia a longo prazo demonstrado in vivo. Via review, não verificado contra artigo primário.';
update public_safe_harbors_staging set evidence_summary = 'Cytogenetic band 7q36.1, within the ZNF767P pseudogene. T-cell-specific discovery via ATAC-seq. Durable CAR expression over multiple weeks in CAR-CD19 T cells; preserves the native T-cell receptor; long-term leukemia control demonstrated in vivo. Via secondary review, not verified against the primary article.', stability = 'Durable over multiple weeks; long-term in vivo control demonstrated' where source_pmid = '41511364' and evidence_summary = 'Banda 7q36.1, dentro do pseudogene ZNF767P. Descoberta específica de células T via ATAC-seq. Expressão duradoura de CAR ao longo de múltiplas semanas em células T CAR-CD19; mantém o recetor de células T nativo; controlo de leucemia a longo prazo demonstrado in vivo. Via review, não verificado contra artigo primário.';

-- (batch 2 complete -- 15/15 records)
