-- Translation + stability field for staging_insert_batch1..6.sql records.
-- Matches by source_pmid + exact original (Portuguese) evidence_summary, so it
-- is safe to run even if a pmid/locus combo repeats with different text.
-- Run against BOTH tables so future promotions from staging stay consistent.

-- ===== batch 1 =====

update known_safe_harbors set evidence_summary = 'In human iPSCs, CRISPR/Cas9 targeting AAVS1 to insert optogenetic/chemogenetic receptors (ChR2/hM4Di) resulted in silencing -- TRE3G BI promoter showed 95.3-98.2% methylation in iPSCs, vs. only 5.9% in HEK293T with the same construct. Hypomethylated clones also failed to express. Differentiation into neural stem cells did not reverse silencing.', stability = 'Silenced in iPSCs (95-98% methylation); silencing not reversed by neural differentiation' where source_pmid = '41468306' and evidence_summary = 'Em iPSCs humanas, CRISPR/Cas9 alvejando AAVS1 para inserir recetores optogenéticos/quimiogenéticos (ChR2/hM4Di) resultou em silenciamento -- promotor TRE3G BI com 95.3-98.2% de metilação em iPSCs, vs. apenas 5.9% em HEK293T com a mesma construção. Clones hipometilados também falharam em expressar. Diferenciação para estaminais neurais não reverteu.';
update public_safe_harbors_staging set evidence_summary = 'In human iPSCs, CRISPR/Cas9 targeting AAVS1 to insert optogenetic/chemogenetic receptors (ChR2/hM4Di) resulted in silencing -- TRE3G BI promoter showed 95.3-98.2% methylation in iPSCs, vs. only 5.9% in HEK293T with the same construct. Hypomethylated clones also failed to express. Differentiation into neural stem cells did not reverse silencing.', stability = 'Silenced in iPSCs (95-98% methylation); silencing not reversed by neural differentiation' where source_pmid = '41468306' and evidence_summary = 'Em iPSCs humanas, CRISPR/Cas9 alvejando AAVS1 para inserir recetores optogenéticos/quimiogenéticos (ChR2/hM4Di) resultou em silenciamento -- promotor TRE3G BI com 95.3-98.2% de metilação em iPSCs, vs. apenas 5.9% em HEK293T com a mesma construção. Clones hipometilados também falharam em expressar. Diferenciação para estaminais neurais não reverteu.';

update known_safe_harbors set evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at ROSA26 maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.108nM.', stability = 'Stable >140 weeks in vivo' where source_pmid = '41341583' and evidence_summary = 'Ratinhos transgénicos com anticorpo humano anti-SEB inserido em ROSA26 mantiveram produção estável por >140 semanas sem comprometer viabilidade, com transmissão germinativa fiel por 6 gerações. KD=0.108nM.';
update public_safe_harbors_staging set evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at ROSA26 maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.108nM.', stability = 'Stable >140 weeks in vivo' where source_pmid = '41341583' and evidence_summary = 'Ratinhos transgénicos com anticorpo humano anti-SEB inserido em ROSA26 mantiveram produção estável por >140 semanas sem comprometer viabilidade, com transmissão germinativa fiel por 6 gerações. KD=0.108nM.';

update known_safe_harbors set evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at Hipp11 (H11) maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.154nM.', stability = 'Stable >140 weeks in vivo' where source_pmid = '41341583' and evidence_summary = 'Ratinhos transgénicos com anticorpo humano anti-SEB inserido em Hipp11 (H11) mantiveram produção estável por >140 semanas sem comprometer viabilidade, com transmissão germinativa fiel por 6 gerações. KD=0.154nM.';
update public_safe_harbors_staging set evidence_summary = 'Transgenic mice with a human anti-SEB antibody inserted at Hipp11 (H11) maintained stable production for >140 weeks without compromising viability, with faithful germline transmission over 6 generations. KD=0.154nM.', stability = 'Stable >140 weeks in vivo' where source_pmid = '41341583' and evidence_summary = 'Ratinhos transgénicos com anticorpo humano anti-SEB inserido em Hipp11 (H11) mantiveram produção estável por >140 semanas sem comprometer viabilidade, com transmissão germinativa fiel por 6 gerações. KD=0.154nM.';

update known_safe_harbors set evidence_summary = 'Macrophages isolated from Rosa26-Cas9 mice (Cas9-FZ line, Jackson Lab #026179, the most widely used worldwide) showed no defects in any commonly tested macrophage signaling pathway (RNA-seq + TLR3/TLR4/TRIF signaling immunoblot), contradicting an earlier report of differences.', stability = 'Not a duration study -- functional signaling assay only' where source_pmid = '41208113' and evidence_summary = 'Macrófagos isolados de ratinhos Rosa26-Cas9 (linha Cas9-FZ, Jackson Lab #026179, a mais usada globalmente) não mostraram defeitos em nenhuma via de sinalização macrofágica comummente testada (RNA-seq + imunoblot de sinalização TLR3/TLR4/TRIF), contrariando um relato anterior de diferenças.';
update public_safe_harbors_staging set evidence_summary = 'Macrophages isolated from Rosa26-Cas9 mice (Cas9-FZ line, Jackson Lab #026179, the most widely used worldwide) showed no defects in any commonly tested macrophage signaling pathway (RNA-seq + TLR3/TLR4/TRIF signaling immunoblot), contradicting an earlier report of differences.', stability = 'Not a duration study -- functional signaling assay only' where source_pmid = '41208113' and evidence_summary = 'Macrófagos isolados de ratinhos Rosa26-Cas9 (linha Cas9-FZ, Jackson Lab #026179, a mais usada globalmente) não mostraram defeitos em nenhuma via de sinalização macrofágica comummente testada (RNA-seq + imunoblot de sinalização TLR3/TLR4/TRIF), contrariando um relato anterior de diferenças.';

update known_safe_harbors set evidence_summary = 'Human trophoblast stem cells (hTSC, CT29 line) GFP-tagged via knock-in at AAVS1 remained proliferative and able to differentiate into extravillous cytotrophoblast and syncytiotrophoblast -- first demonstration of AAVS1 integration in this cell lineage.', stability = 'Stable through proliferation and differentiation (duration not quantified)' where source_pmid = '41523105' and evidence_summary = 'Células estaminais de trofoblasto humano (hTSC, linha CT29) marcadas com GFP via knock-in em AAVS1 mantiveram-se proliferativas e capazes de diferenciar em citotrofoblasto extraviloso e sinciciotrofoblasto -- primeira demonstração de integração AAVS1 nesta linhagem celular.';
update public_safe_harbors_staging set evidence_summary = 'Human trophoblast stem cells (hTSC, CT29 line) GFP-tagged via knock-in at AAVS1 remained proliferative and able to differentiate into extravillous cytotrophoblast and syncytiotrophoblast -- first demonstration of AAVS1 integration in this cell lineage.', stability = 'Stable through proliferation and differentiation (duration not quantified)' where source_pmid = '41523105' and evidence_summary = 'Células estaminais de trofoblasto humano (hTSC, linha CT29) marcadas com GFP via knock-in em AAVS1 mantiveram-se proliferativas e capazes de diferenciar em citotrofoblasto extraviloso e sinciciotrofoblasto -- primeira demonstração de integração AAVS1 nesta linhagem celular.';

update known_safe_harbors set evidence_summary = 'Biotin ligases (MicroID/TurboID) randomly integrated in mESCs express well in stem cells but silence completely after differentiation into neurons, regardless of promoter. The same construct targeted to the mHipp11 (H11) locus retained expression, correct localization, and activity after 8-10 days of neuronal differentiation.', stability = 'Active through 8-10 days of neuronal differentiation (vs. full silencing at random sites)' where source_pmid = '40036200' and evidence_summary = 'Ligases de biotina (MicroID/TurboID) integradas aleatoriamente em mESCs expressam bem em estaminais mas silenciam completamente após diferenciação em neurónios, independente do promotor. A mesma construção alvejada ao locus mHipp11 (H11) manteve expressão, localização correta e atividade após 8-10 dias de diferenciação neuronal.';
update public_safe_harbors_staging set evidence_summary = 'Biotin ligases (MicroID/TurboID) randomly integrated in mESCs express well in stem cells but silence completely after differentiation into neurons, regardless of promoter. The same construct targeted to the mHipp11 (H11) locus retained expression, correct localization, and activity after 8-10 days of neuronal differentiation.', stability = 'Active through 8-10 days of neuronal differentiation (vs. full silencing at random sites)' where source_pmid = '40036200' and evidence_summary = 'Ligases de biotina (MicroID/TurboID) integradas aleatoriamente em mESCs expressam bem em estaminais mas silenciam completamente após diferenciação em neurónios, independente do promotor. A mesma construção alvejada ao locus mHipp11 (H11) manteve expressão, localização correta e atividade após 8-10 dias de diferenciação neuronal.';

update known_safe_harbors set evidence_summary = 'Dox-inducible system (Tet-On 3G in hROSA26 + transgene in AAVS1) undergoes significant silencing in hiPSC-derived cardiomyocytes (hiPSC-CM). Sodium butyrate restores activity but compromises hiPSC viability. Relocating the cassette to the CLYBL locus improved promoter activity relative to AAVS1, both in hiPSC and hiPSC-CM.', stability = 'Silences after cardiomyocyte differentiation' where source_pmid = '39926351' and evidence_summary = 'Sistema dox-indutível (Tet-On 3G em hROSA26 + transgene em AAVS1) sofre silenciamento significativo em cardiomiócitos derivados de hiPSC (hiPSC-CM). Butirato de sódio restaura atividade mas compromete viabilidade das hiPSC. Realocar a cassete para o locus CLYBL melhorou a atividade do promotor face a AAVS1, tanto em hiPSC como em hiPSC-CM.';
update public_safe_harbors_staging set evidence_summary = 'Dox-inducible system (Tet-On 3G in hROSA26 + transgene in AAVS1) undergoes significant silencing in hiPSC-derived cardiomyocytes (hiPSC-CM). Sodium butyrate restores activity but compromises hiPSC viability. Relocating the cassette to the CLYBL locus improved promoter activity relative to AAVS1, both in hiPSC and hiPSC-CM.', stability = 'Silences after cardiomyocyte differentiation' where source_pmid = '39926351' and evidence_summary = 'Sistema dox-indutível (Tet-On 3G em hROSA26 + transgene em AAVS1) sofre silenciamento significativo em cardiomiócitos derivados de hiPSC (hiPSC-CM). Butirato de sódio restaura atividade mas compromete viabilidade das hiPSC. Realocar a cassete para o locus CLYBL melhorou a atividade do promotor face a AAVS1, tanto em hiPSC como em hiPSC-CM.';

update known_safe_harbors set evidence_summary = 'Direct comparison of 3 serine integrases (PhiC31, W-beta, Bxb1) at the Gt(ROSA)26Sor locus in mESCs -- all compatible with pluripotency and germline transmission; Bxb1 was 2-3x more efficient than the other two.', stability = 'Compatible with germline transmission (duration not separately quantified)' where source_pmid = '39777513' and evidence_summary = 'Comparação direta de 3 integrases de serina (PhiC31, W-beta, Bxb1) no locus Gt(ROSA)26Sor em mESCs -- todas compatíveis com pluripotência e transmissão germinativa; Bxb1 foi 2-3x mais eficiente que as outras duas.';
update public_safe_harbors_staging set evidence_summary = 'Direct comparison of 3 serine integrases (PhiC31, W-beta, Bxb1) at the Gt(ROSA)26Sor locus in mESCs -- all compatible with pluripotency and germline transmission; Bxb1 was 2-3x more efficient than the other two.', stability = 'Compatible with germline transmission (duration not separately quantified)' where source_pmid = '39777513' and evidence_summary = 'Comparação direta de 3 integrases de serina (PhiC31, W-beta, Bxb1) no locus Gt(ROSA)26Sor em mESCs -- todas compatíveis com pluripotência e transmissão germinativa; Bxb1 foi 2-3x mais eficiente que as outras duas.';

update known_safe_harbors set evidence_summary = 'Bxb1 system adapted for cassette exchange at AAVS1 in hiPSCs: the CAG promoter gave consistent, stable expression; the Ef1a (EIF1A) promoter gave a very mosaic expression pattern in the same cell line -- effect depends strongly on the promoter, not just the locus.', stability = 'Stable with CAG promoter; mosaic with Ef1a (promoter-dependent)' where source_pmid = '39777513' and evidence_summary = 'Sistema Bxb1 adaptado para troca de cassete em AAVS1 em hiPSCs: promotor CAG deu expressão consistente e estável; promotor Ef1a (EIF1A) deu padrão de expressão muito mosaico na mesma linha celular -- efeito depende fortemente do promotor, não só do locus.';
update public_safe_harbors_staging set evidence_summary = 'Bxb1 system adapted for cassette exchange at AAVS1 in hiPSCs: the CAG promoter gave consistent, stable expression; the Ef1a (EIF1A) promoter gave a very mosaic expression pattern in the same cell line -- effect depends strongly on the promoter, not just the locus.', stability = 'Stable with CAG promoter; mosaic with Ef1a (promoter-dependent)' where source_pmid = '39777513' and evidence_summary = 'Sistema Bxb1 adaptado para troca de cassete em AAVS1 em hiPSCs: promotor CAG deu expressão consistente e estável; promotor Ef1a (EIF1A) deu padrão de expressão muito mosaico na mesma linha celular -- efeito depende fortemente do promotor, não só do locus.';

update known_safe_harbors set evidence_summary = 'Direct comparison of ROSA26 vs. H11 in the same mouse (3 fluorescent reporters -- EGFP, tdTomato, mTagBFP2 -- under the CAG promoter, including a triple-transgenic model). Expression efficiency was higher at ROSA26 than H11 in most tissues examined. Substantial expression heterogeneity was observed even between cells of the same tissue.', stability = 'Higher expression efficiency than H11 (duration not separately quantified)' where source_pmid = '38752269' and evidence_summary = 'Comparação direta ROSA26 vs. H11 no mesmo ratinho (3 repórteres fluorescentes -- EGFP, tdTomato, mTagBFP2 -- sob promotor CAG, incluindo modelo triplo-transgénico). Eficiência de expressão superior em ROSA26 face a H11 na maioria dos tecidos examinados. Heterogeneidade substancial de expressão observada mesmo entre células do mesmo tecido.';
update public_safe_harbors_staging set evidence_summary = 'Direct comparison of ROSA26 vs. H11 in the same mouse (3 fluorescent reporters -- EGFP, tdTomato, mTagBFP2 -- under the CAG promoter, including a triple-transgenic model). Expression efficiency was higher at ROSA26 than H11 in most tissues examined. Substantial expression heterogeneity was observed even between cells of the same tissue.', stability = 'Higher expression efficiency than H11 (duration not separately quantified)' where source_pmid = '38752269' and evidence_summary = 'Comparação direta ROSA26 vs. H11 no mesmo ratinho (3 repórteres fluorescentes -- EGFP, tdTomato, mTagBFP2 -- sob promotor CAG, incluindo modelo triplo-transgénico). Eficiência de expressão superior em ROSA26 face a H11 na maioria dos tecidos examinados. Heterogeneidade substancial de expressão observada mesmo entre células do mesmo tecido.';

update known_safe_harbors set evidence_summary = 'In the same direct comparative study with ROSA26 (3 fluorescent reporters under CAG), expression efficiency at H11 was lower than at ROSA26 in most tissues, though still functional. Substantial heterogeneity between cells of the same tissue.', stability = 'Functional but lower efficiency than ROSA26' where source_pmid = '38752269' and evidence_summary = 'No mesmo estudo comparativo direto com ROSA26 (3 repórteres fluorescentes sob CAG), a eficiência de expressão em H11 foi inferior à de ROSA26 na maioria dos tecidos, embora ainda funcional. Heterogeneidade substancial entre células do mesmo tecido.';
update public_safe_harbors_staging set evidence_summary = 'In the same direct comparative study with ROSA26 (3 fluorescent reporters under CAG), expression efficiency at H11 was lower than at ROSA26 in most tissues, though still functional. Substantial heterogeneity between cells of the same tissue.', stability = 'Functional but lower efficiency than ROSA26' where source_pmid = '38752269' and evidence_summary = 'No mesmo estudo comparativo direto com ROSA26 (3 repórteres fluorescentes sob CAG), a eficiência de expressão em H11 foi inferior à de ROSA26 na maioria dos tecidos, embora ainda funcional. Heterogeneidade substancial entre células do mesmo tecido.';

update known_safe_harbors set evidence_summary = 'The H11 locus supports constitutive and conditional expression of the TIR1 transgene (AID degradation system) in both mouse AND human embryonic stem cells, and in mice in vivo -- cross-species validation of the same locus.', stability = 'Constitutive/conditional expression validated cross-species (duration not quantified)' where source_pmid = '33202307' and evidence_summary = 'Locus H11 suporta expressão constitutiva e condicional do transgene TIR1 (sistema de degradação AID) em estaminais embrionárias de ratinho E de humano, e em ratinhos in vivo -- validação cross-species do mesmo locus.';
update public_safe_harbors_staging set evidence_summary = 'The H11 locus supports constitutive and conditional expression of the TIR1 transgene (AID degradation system) in both mouse AND human embryonic stem cells, and in mice in vivo -- cross-species validation of the same locus.', stability = 'Constitutive/conditional expression validated cross-species (duration not quantified)' where source_pmid = '33202307' and evidence_summary = 'Locus H11 suporta expressão constitutiva e condicional do transgene TIR1 (sistema de degradação AID) em estaminais embrionárias de ratinho E de humano, e em ratinhos in vivo -- validação cross-species do mesmo locus.';

update known_safe_harbors set locus_name = 'Random integration (SCNT, not a named safe harbor)', evidence_summary = 'In transgenic dogs generated by SCNT, the hEF1a promoter was silenced by DNA methylation (expression rescued by DNMT inhibition). The CMV promoter maintained strong expression at both organism and cell level in all transgenic dogs even after 19 months. Not a named safe harbor -- random integration via SCNT -- but direct silencing data in dog, the species most relevant to this project.', stability = 'CMV promoter stable >19 months; hEF1a promoter silenced by methylation' where source_pmid = '32492024' and evidence_summary = 'Em cães transgénicos gerados por SCNT, o promotor hEF1a foi silenciado por metilação de DNA (expressão resgatada por inibição de DNMT). O promotor CMV manteve expressão forte a nível organismal e celular em todos os cães transgénicos mesmo após 19 meses. Não é um safe harbor nomeado -- integração aleatória via SCNT -- mas é dado direto de silenciamento em cão, a espécie do teu próprio projeto.';
update public_safe_harbors_staging set locus_name = 'Random integration (SCNT, not a named safe harbor)', evidence_summary = 'In transgenic dogs generated by SCNT, the hEF1a promoter was silenced by DNA methylation (expression rescued by DNMT inhibition). The CMV promoter maintained strong expression at both organism and cell level in all transgenic dogs even after 19 months. Not a named safe harbor -- random integration via SCNT -- but direct silencing data in dog, the species most relevant to this project.', stability = 'CMV promoter stable >19 months; hEF1a promoter silenced by methylation' where source_pmid = '32492024' and evidence_summary = 'Em cães transgénicos gerados por SCNT, o promotor hEF1a foi silenciado por metilação de DNA (expressão resgatada por inibição de DNMT). O promotor CMV manteve expressão forte a nível organismal e celular em todos os cães transgénicos mesmo após 19 meses. Não é um safe harbor nomeado -- integração aleatória via SCNT -- mas é dado direto de silenciamento em cão, a espécie do teu próprio projeto.';

-- (batch 1 complete -- 13/13 records. Continues in translate_batch_1-6.sql part 2 for batches 2-6.)
