-- Translation + stability for staging_insert_batch7.sql (28 records, PMID 38164941 / 36131352 / 35474867)

update known_safe_harbors set evidence_summary = 'Exact coordinates (nearest gene: MAGI3, not MYBPC as previously thought). Validated in hESC: log2 fold-change between -0.067 and 0.065 vs. untargeted; 96 differentially expressed genes out of 29,696 tested; >98% Clover-positive cells maintained over 15 passages; stable expression in neuronal, hepatic, cardiac, and pancreatic derivatives; normal karyotype; teratoma confirms all 3 germ layers; nearest differentially expressed gene is >3Mb from the integration site.', stability = 'Stable for 15 passages and across 3-germ-layer differentiation' where source_pmid = '38164941' and evidence_summary = 'Coordenadas exatas (gene mais próximo: MAGI3, não MAGI3 nao MYBPC como pensado antes). Validado em hESC: log2 fold-change entre -0.067 e 0.065 vs. não-alvejadas; 96 genes diferencialmente expressos em 29.696 testados; >98% de células Clover-positivas mantidas ao longo de 15 passagens; expressão estável em derivados neuronais, hepáticos, cardíacos e pancreáticos; cariótipo normal; teratoma confirma as 3 camadas germinativas; gene diferencialmente expresso mais próximo fica a >3Mb do sítio de integração.';
update public_safe_harbors_staging set evidence_summary = 'Exact coordinates (nearest gene: MAGI3, not MYBPC as previously thought). Validated in hESC: log2 fold-change between -0.067 and 0.065 vs. untargeted; 96 differentially expressed genes out of 29,696 tested; >98% Clover-positive cells maintained over 15 passages; stable expression in neuronal, hepatic, cardiac, and pancreatic derivatives; normal karyotype; teratoma confirms all 3 germ layers; nearest differentially expressed gene is >3Mb from the integration site.', stability = 'Stable for 15 passages and across 3-germ-layer differentiation' where source_pmid = '38164941' and evidence_summary = 'Coordenadas exatas (gene mais próximo: MAGI3, não MAGI3 nao MYBPC como pensado antes). Validado em hESC: log2 fold-change entre -0.067 e 0.065 vs. não-alvejadas; 96 genes diferencialmente expressos em 29.696 testados; >98% de células Clover-positivas mantidas ao longo de 15 passagens; expressão estável em derivados neuronais, hepáticos, cardíacos e pancreáticos; cariótipo normal; teratoma confirma as 3 camadas germinativas; gene diferencialmente expresso mais próximo fica a >3Mb do sítio de integração.';

update known_safe_harbors set evidence_summary = 'Exact coordinates (nearest gene: TXNL1). Same validation profile as Pansio-1: log2-FC -0.067 to 0.065, 111 differentially expressed genes out of 29,696, >98% Clover-positive for 15 passages, expression maintained across all 3 germ layers, normal karyotype, nearest DE gene >5Mb away.', stability = 'Stable for 15 passages and across 3-germ-layer differentiation' where source_pmid = '38164941' and evidence_summary = 'Coordenadas exatas (gene mais próximo: TXNL1). Mesmo perfil de validação que Pansio-1: log2-FC -0.067 a 0.065, 111 genes diferencialmente expressos de 29.696, >98% Clover-positivas por 15 passagens, expressão mantida nas 3 camadas germinativas, cariótipo normal, gene DE mais próximo a >5Mb.';
update public_safe_harbors_staging set evidence_summary = 'Exact coordinates (nearest gene: TXNL1). Same validation profile as Pansio-1: log2-FC -0.067 to 0.065, 111 differentially expressed genes out of 29,696, >98% Clover-positive for 15 passages, expression maintained across all 3 germ layers, normal karyotype, nearest DE gene >5Mb away.', stability = 'Stable for 15 passages and across 3-germ-layer differentiation' where source_pmid = '38164941' and evidence_summary = 'Coordenadas exatas (gene mais próximo: TXNL1). Mesmo perfil de validação que Pansio-1: log2-FC -0.067 a 0.065, 111 genes diferencialmente expressos de 29.696, >98% Clover-positivas por 15 passagens, expressão mantida nas 3 camadas germinativas, cariótipo normal, gene DE mais próximo a >5Mb.';

update known_safe_harbors set evidence_summary = 'Exact coordinates (nearest gene: ZNRF4). Same validation profile: log2-FC -0.067 to 0.065, 119 differentially expressed genes out of 29,696, >98% Clover-positive, expression maintained in derived neurons/hepatocytes/cardiomyocytes, normal karyotype. Nearest DE gene only ~1Mb away -- the closest of the three, still passed safety criteria.', stability = 'Stable across neuronal/hepatic/cardiac differentiation' where source_pmid = '38164941' and evidence_summary = 'Coordenadas exatas (gene mais próximo: ZNRF4). Mesmo perfil de validação: log2-FC -0.067 a 0.065, 119 genes diferencialmente expressos de 29.696, >98% Clover-positivas, expressão mantida em neurónios/hepatocitos/cardiomiócitos derivados, cariótipo normal. Gene DE mais próximo apenas a ~1Mb -- o mais próximo dos três, ainda assim aprovado nos critérios de segurança.';
update public_safe_harbors_staging set evidence_summary = 'Exact coordinates (nearest gene: ZNRF4). Same validation profile: log2-FC -0.067 to 0.065, 119 differentially expressed genes out of 29,696, >98% Clover-positive, expression maintained in derived neurons/hepatocytes/cardiomyocytes, normal karyotype. Nearest DE gene only ~1Mb away -- the closest of the three, still passed safety criteria.', stability = 'Stable across neuronal/hepatic/cardiac differentiation' where source_pmid = '38164941' and evidence_summary = 'Coordenadas exatas (gene mais próximo: ZNRF4). Mesmo perfil de validação: log2-FC -0.067 a 0.065, 119 genes diferencialmente expressos de 29.696, >98% Clover-positivas, expressão mantida em neurónios/hepatocitos/cardiomiócitos derivados, cariótipo normal. Gene DE mais próximo apenas a ~1Mb -- o mais próximo dos três, ainda assim aprovado nos critérios de segurança.';

update known_safe_harbors set evidence_summary = 'Exact coordinates (intron of GOLGA4). The only one of 3 candidates tested in HUDEP2 erythroid cells to show full success: GFP signal remained positive for 3 months, with no significant change in GOLGA4 expression or in adjacent genes within the same TAD.', stability = 'Stable >3 months in erythroid cells' where source_pmid = '36131352' and evidence_summary = 'Coordenadas exatas (intrão de GOLGA4). Único dos 3 candidatos testados em células eritroides HUDEP2 a mostrar sucesso completo: sinal de GFP mantido positivo por 3 meses, sem alteração significativa na expressão de GOLGA4 nem de genes adjacentes no mesmo TAD.';
update public_safe_harbors_staging set evidence_summary = 'Exact coordinates (intron of GOLGA4). The only one of 3 candidates tested in HUDEP2 erythroid cells to show full success: GFP signal remained positive for 3 months, with no significant change in GOLGA4 expression or in adjacent genes within the same TAD.', stability = 'Stable >3 months in erythroid cells' where source_pmid = '36131352' and evidence_summary = 'Coordenadas exatas (intrão de GOLGA4). Único dos 3 candidatos testados em células eritroides HUDEP2 a mostrar sucesso completo: sinal de GFP mantido positivo por 3 meses, sem alteração significativa na expressão de GOLGA4 nem de genes adjacentes no mesmo TAD.';

update known_safe_harbors set locus_name = 'BLD_SHS14 / BLD_SHS15', evidence_summary = 'CORRECTION to a prior record (batch 2, via secondary review): these two candidates (ARID1B and TAF2) were indeed tested in HUDEP2 cells alongside BLD_SHS10, but the primary article states that "only BLD_GSH_10 showed full success" -- suggesting these two did NOT have the same positive result the secondary review implied. Confidence lowered to reflect this contradiction; needs direct confirmation against the primary article before any use.', stability = 'Contradicted by primary source -- needs direct confirmation' where source_pmid = '36131352' and evidence_summary = 'CORRECAO a registo anterior (lote 2, via review secundaria): esses dois candidatos (ARID1B e TAF2) foram de facto testados em células HUDEP2 juntamente com o BLD_SHS10, mas o artigo primário indica que "apenas BLD_GSH_10 mostrou sucesso completo" -- sugerindo que estes dois NAO tiveram o mesmo resultado positivo que a review secundária deu a entender. Confiança baixada para refletir esta contradição; precisa de confirmação direta contra o artigo primário antes de qualquer uso.';
update public_safe_harbors_staging set locus_name = 'BLD_SHS14 / BLD_SHS15', evidence_summary = 'CORRECTION to a prior record (batch 2, via secondary review): these two candidates (ARID1B and TAF2) were indeed tested in HUDEP2 cells alongside BLD_SHS10, but the primary article states that "only BLD_GSH_10 showed full success" -- suggesting these two did NOT have the same positive result the secondary review implied. Confidence lowered to reflect this contradiction; needs direct confirmation against the primary article before any use.', stability = 'Contradicted by primary source -- needs direct confirmation' where source_pmid = '36131352' and evidence_summary = 'CORRECAO a registo anterior (lote 2, via review secundaria): esses dois candidatos (ARID1B e TAF2) foram de facto testados em células HUDEP2 juntamente com o BLD_SHS10, mas o artigo primário indica que "apenas BLD_GSH_10 mostrou sucesso completo" -- sugerindo que estes dois NAO tiveram o mesmo resultado positivo que a review secundária deu a entender. Confiança baixada para refletir esta contradição; precisa de confirmação direta contra o artigo primário antes de qualquer uso.';

update known_safe_harbors set evidence_summary = 'Rich validation (exact location only in a figure, not extractable from text): stable mRuby expression 90 days after integration in HEK293T, outperforming AAVS1 in the same assay. 94.7% mRuby+ primary T cells after selection; >92% GFP+ primary dermal fibroblasts, maintained >25 days. Single-cell RNA-seq shows minimal transcriptome disruption, no upregulation of cancer-associated pathways.', stability = 'Stable >90 days in cell lines; >25 days in fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Validação rica (localização exata só em figura, não extraível em texto): expressão estável de mRuby 90 dias após integração em HEK293T, superando o desempenho do AAVS1 no mesmo ensaio. 94.7% de células T primárias mRuby+ após selecção; >92% de fibroblastos dérmicos primários GFP+, mantido por >25 dias. RNA-seq de célula única mostra disrupção mínima do transcriptoma, sem sobre-regulação de vias associadas a cancro.';
update public_safe_harbors_staging set evidence_summary = 'Rich validation (exact location only in a figure, not extractable from text): stable mRuby expression 90 days after integration in HEK293T, outperforming AAVS1 in the same assay. 94.7% mRuby+ primary T cells after selection; >92% GFP+ primary dermal fibroblasts, maintained >25 days. Single-cell RNA-seq shows minimal transcriptome disruption, no upregulation of cancer-associated pathways.', stability = 'Stable >90 days in cell lines; >25 days in fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Validação rica (localização exata só em figura, não extraível em texto): expressão estável de mRuby 90 dias após integração em HEK293T, superando o desempenho do AAVS1 no mesmo ensaio. 94.7% de células T primárias mRuby+ após selecção; >92% de fibroblastos dérmicos primários GFP+, mantido por >25 dias. RNA-seq de célula única mostra disrupção mínima do transcriptoma, sem sobre-regulação de vias associadas a cancro.';

update known_safe_harbors set evidence_summary = 'Rich validation: stable mRuby expression 90 days in HEK293T AND Jurkat, outperforming the CCR5 locus in Jurkat. 91.8% mRuby+ primary T cells after selection; >92% GFP+ fibroblasts, maintained >25 days. Bulk RNA-seq showed no significant enrichment of cancer-associated genes or pathways.', stability = 'Stable >90 days in cell lines; >25 days in fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Validação rica: expressão estável de mRuby 90 dias em HEK293T E em Jurkat, superando o desempenho do locus CCR5 em Jurkat. 91.8% de células T primárias mRuby+ após selecção; >92% de fibroblastos GFP+, mantido >25 dias. RNA-seq em massa sem enriquecimento significativo de genes ou vias associadas a cancro.';
update public_safe_harbors_staging set evidence_summary = 'Rich validation: stable mRuby expression 90 days in HEK293T AND Jurkat, outperforming the CCR5 locus in Jurkat. 91.8% mRuby+ primary T cells after selection; >92% GFP+ fibroblasts, maintained >25 days. Bulk RNA-seq showed no significant enrichment of cancer-associated genes or pathways.', stability = 'Stable >90 days in cell lines; >25 days in fibroblasts' where source_pmid = '35474867' and evidence_summary = 'Validação rica: expressão estável de mRuby 90 dias em HEK293T E em Jurkat, superando o desempenho do locus CCR5 em Jurkat. 91.8% de células T primárias mRuby+ após selecção; >92% de fibroblastos GFP+, mantido >25 dias. RNA-seq em massa sem enriquecimento significativo de genes ou vias associadas a cancro.';

update known_safe_harbors set locus_name = 'BLD_GSH_1 (candidate, untested)', evidence_summary = 'Intron of ANP32E. Computational candidate via polymorphic mobile element insertions + epigenomics + 3D chromatin organization. Not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de ANP32E. Candidato computacional via inserções de elementos móveis polimórficos + epigenómica + organização 3D da cromatina. Não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_1 (candidate, untested)', evidence_summary = 'Intron of ANP32E. Computational candidate via polymorphic mobile element insertions + epigenomics + 3D chromatin organization. Not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de ANP32E. Candidato computacional via inserções de elementos móveis polimórficos + epigenómica + organização 3D da cromatina. Não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_2 (candidate, untested)', evidence_summary = 'Intron of NEK7. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de NEK7. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_2 (candidate, untested)', evidence_summary = 'Intron of NEK7. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de NEK7. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_3 (candidate, untested)', evidence_summary = 'Intron of NFRKB. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de NFRKB. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_3 (candidate, untested)', evidence_summary = 'Intron of NFRKB. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de NFRKB. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_4 (candidate, untested)', evidence_summary = 'Intron of VPS33A. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de VPS33A. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_4 (candidate, untested)', evidence_summary = 'Intron of VPS33A. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de VPS33A. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_5 (candidate, untested)', evidence_summary = 'Intron of ANKRD10. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de ANKRD10. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_5 (candidate, untested)', evidence_summary = 'Intron of ANKRD10. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de ANKRD10. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_6 (candidate, untested)', evidence_summary = 'Intron of GALK2. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de GALK2. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_6 (candidate, untested)', evidence_summary = 'Intron of GALK2. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de GALK2. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_7 (candidate, untested)', evidence_summary = 'Intergenic. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intergénico. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_7 (candidate, untested)', evidence_summary = 'Intergenic. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intergénico. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_8 (candidate, untested)', evidence_summary = 'Intron of DHX57. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de DHX57. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_8 (candidate, untested)', evidence_summary = 'Intron of DHX57. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de DHX57. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_9 (candidate, untested)', evidence_summary = 'Intron of FARSB. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de FARSB. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_9 (candidate, untested)', evidence_summary = 'Intron of FARSB. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de FARSB. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_11 (candidate, untested)', evidence_summary = 'Intron of LARS2. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de LARS2. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_11 (candidate, untested)', evidence_summary = 'Intron of LARS2. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de LARS2. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_12 (candidate, untested)', evidence_summary = 'Intron of SACM1L. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de SACM1L. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_12 (candidate, untested)', evidence_summary = 'Intron of SACM1L. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de SACM1L. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_13 (candidate, untested)', evidence_summary = 'Intron of AFF1. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de AFF1. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_13 (candidate, untested)', evidence_summary = 'Intron of AFF1. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de AFF1. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_16 (candidate, untested)', evidence_summary = 'Intron of TRMO. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de TRMO. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_16 (candidate, untested)', evidence_summary = 'Intron of TRMO. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de TRMO. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_17 (candidate, untested)', evidence_summary = 'Intron of FKBP15. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de FKBP15. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_17 (candidate, untested)', evidence_summary = 'Intron of FKBP15. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de FKBP15. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_18 (candidate, untested)', evidence_summary = 'Intron of CDK11A. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de CDK11A. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_18 (candidate, untested)', evidence_summary = 'Intron of CDK11A. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de CDK11A. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BLD_GSH_19 (candidate, untested)', evidence_summary = 'Intron of MORF4L1. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de MORF4L1. Candidato computacional, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BLD_GSH_19 (candidate, untested)', evidence_summary = 'Intron of MORF4L1. Computational candidate, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de MORF4L1. Candidato computacional, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BRN_GSH_1 (brain candidate, untested)', evidence_summary = 'Intron of AHCTF1. Computational candidate for brain cells, not experimentally tested. Relevant for neuronal applications.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de AHCTF1. Candidato computacional para células cerebrais, não testado experimentalmente. Relevante para aplicações neuronais.';
update public_safe_harbors_staging set locus_name = 'BRN_GSH_1 (brain candidate, untested)', evidence_summary = 'Intron of AHCTF1. Computational candidate for brain cells, not experimentally tested. Relevant for neuronal applications.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de AHCTF1. Candidato computacional para células cerebrais, não testado experimentalmente. Relevante para aplicações neuronais.';

update known_safe_harbors set locus_name = 'BRN_GSH_2 (brain candidate, untested)', evidence_summary = 'Intron of WNK1. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de WNK1. Candidato computacional para células cerebrais, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BRN_GSH_2 (brain candidate, untested)', evidence_summary = 'Intron of WNK1. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de WNK1. Candidato computacional para células cerebrais, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BRN_GSH_3 (brain candidate, untested)', evidence_summary = 'Intron of MICAL3. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de MICAL3. Candidato computacional para células cerebrais, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BRN_GSH_3 (brain candidate, untested)', evidence_summary = 'Intron of MICAL3. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de MICAL3. Candidato computacional para células cerebrais, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BRN_GSH_4 (brain candidate, untested)', evidence_summary = 'Intron of CRMP1. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de CRMP1. Candidato computacional para células cerebrais, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BRN_GSH_4 (brain candidate, untested)', evidence_summary = 'Intron of CRMP1. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de CRMP1. Candidato computacional para células cerebrais, não testado experimentalmente.';

update known_safe_harbors set locus_name = 'BRN_GSH_5 (brain candidate, untested)', evidence_summary = 'Intron of LOC221946. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de LOC221946. Candidato computacional para células cerebrais, não testado experimentalmente.';
update public_safe_harbors_staging set locus_name = 'BRN_GSH_5 (brain candidate, untested)', evidence_summary = 'Intron of LOC221946. Computational candidate for brain cells, not experimentally tested.', stability = 'Not experimentally tested' where source_pmid = '36131352' and evidence_summary = 'Intrão de LOC221946. Candidato computacional para células cerebrais, não testado experimentalmente.';

-- (batch 7 complete -- 28/28 records)
