-- Translation + stability for staging_insert_batch8.sql (12) and batch9.sql (9)

-- ===== batch 8 =====
update known_safe_harbors set evidence_summary = 'STRAIGHT-IN v2 system (landing pad platform) inserted at AAVS1 in a hiPSC line -- generation of genetically modified lines with ~100% efficiency in ~2-3 weeks.', stability = 'Fast generation (~2-3 weeks), ~100% efficiency' where source_pmid = '36495703' and evidence_summary = 'Sistema STRAIGHT-IN v2 (plataforma de landing pad) inserido em AAVS1 em linha hiPSC -- geração de linhas geneticamente modificadas com ~100% de eficiência em ~2-3 semanas.';
update public_safe_harbors_staging set evidence_summary = 'STRAIGHT-IN v2 system (landing pad platform) inserted at AAVS1 in a hiPSC line -- generation of genetically modified lines with ~100% efficiency in ~2-3 weeks.', stability = 'Fast generation (~2-3 weeks), ~100% efficiency' where source_pmid = '36495703' and evidence_summary = 'Sistema STRAIGHT-IN v2 (plataforma de landing pad) inserido em AAVS1 em linha hiPSC -- geração de linhas geneticamente modificadas com ~100% de eficiência em ~2-3 semanas.';

update known_safe_harbors set evidence_summary = 'Same STRAIGHT-IN v2 system also successfully generated at the CLYBL locus in the same hiPSC line -- same efficiency (~100%) and speed (~2-3 weeks) as AAVS1 in the same study.', stability = 'Fast generation (~2-3 weeks), ~100% efficiency' where source_pmid = '36495703' and evidence_summary = 'Mesmo sistema STRAIGHT-IN v2 também gerado com sucesso no locus CLYBL na mesma linha hiPSC -- mesma eficiência (~100%) e rapidez (~2-3 semanas) que AAVS1 no mesmo estudo.';
update public_safe_harbors_staging set evidence_summary = 'Same STRAIGHT-IN v2 system also successfully generated at the CLYBL locus in the same hiPSC line -- same efficiency (~100%) and speed (~2-3 weeks) as AAVS1 in the same study.', stability = 'Fast generation (~2-3 weeks), ~100% efficiency' where source_pmid = '36495703' and evidence_summary = 'Mesmo sistema STRAIGHT-IN v2 também gerado com sucesso no locus CLYBL na mesma linha hiPSC -- mesma eficiência (~100%) e rapidez (~2-3 semanas) que AAVS1 no mesmo estudo.';

update known_safe_harbors set evidence_summary = 'Tet-on-operator-controlled Cas9 integrated at AAVS1 in human iPSC -- cells remain pluripotent, differentiate into all 3 germ layers, normal karyotype.', stability = 'Pluripotent, normal karyotype after editing (duration not further quantified)' where source_pmid = '33207306' and evidence_summary = 'Cas9 controlado por operador Tet-on integrado em AAVS1 em iPSC humana -- células mantêm-se pluripotentes, diferenciam nas 3 camadas germinativas, cariótipo normal.';
update public_safe_harbors_staging set evidence_summary = 'Tet-on-operator-controlled Cas9 integrated at AAVS1 in human iPSC -- cells remain pluripotent, differentiate into all 3 germ layers, normal karyotype.', stability = 'Pluripotent, normal karyotype after editing (duration not further quantified)' where source_pmid = '33207306' and evidence_summary = 'Cas9 controlado por operador Tet-on integrado em AAVS1 em iPSC humana -- células mantêm-se pluripotentes, diferenciam nas 3 camadas germinativas, cariótipo normal.';

update known_safe_harbors set evidence_summary = 'Direct comparison of 3 loci in HEK293 cells: of AAVS1, CCR5, and human ROSA26 tested for eGFP expression, AAVS1 had the highest and most homogeneous expression of the three. Expression at AAVS1 sustained ~3 months without selection. Within AAVS1 itself, promoter ranking: CMV > EF1a > SV40 > TK.', stability = 'Sustained ~3 months without selection; best of 3 loci compared' where source_pmid = '32470292' and evidence_summary = 'Comparação direta a 3 loci em células HEK293: de AAVS1, CCR5 e ROSA26 humano testados para expressão de eGFP, AAVS1 teve a expressão mais alta e mais homogénea dos três. Expressão em AAVS1 sustentada ~3 meses sem seleção. Dentro do próprio locus AAVS1, ranking de promotores: CMV > EF1a > SV40 > TK.';
update public_safe_harbors_staging set evidence_summary = 'Direct comparison of 3 loci in HEK293 cells: of AAVS1, CCR5, and human ROSA26 tested for eGFP expression, AAVS1 had the highest and most homogeneous expression of the three. Expression at AAVS1 sustained ~3 months without selection. Within AAVS1 itself, promoter ranking: CMV > EF1a > SV40 > TK.', stability = 'Sustained ~3 months without selection; best of 3 loci compared' where source_pmid = '32470292' and evidence_summary = 'Comparação direta a 3 loci em células HEK293: de AAVS1, CCR5 e ROSA26 humano testados para expressão de eGFP, AAVS1 teve a expressão mais alta e mais homogénea dos três. Expressão em AAVS1 sustentada ~3 meses sem seleção. Dentro do próprio locus AAVS1, ranking de promotores: CMV > EF1a > SV40 > TK.';

update known_safe_harbors set evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), CCR5 underperformed AAVS1 in eGFP expression and homogeneity.', stability = 'Underperformed AAVS1 in the same study' where source_pmid = '32470292' and evidence_summary = 'No mesmo estudo comparativo direto em HEK293 (3 loci testados), CCR5 teve desempenho inferior ao AAVS1 em expressão e homogeneidade de eGFP.';
update public_safe_harbors_staging set evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), CCR5 underperformed AAVS1 in eGFP expression and homogeneity.', stability = 'Underperformed AAVS1 in the same study' where source_pmid = '32470292' and evidence_summary = 'No mesmo estudo comparativo direto em HEK293 (3 loci testados), CCR5 teve desempenho inferior ao AAVS1 em expressão e homogeneidade de eGFP.';

update known_safe_harbors set evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), human ROSA26 underperformed AAVS1 in eGFP expression and homogeneity.', stability = 'Underperformed AAVS1 in the same study' where source_pmid = '32470292' and evidence_summary = 'No mesmo estudo comparativo direto em HEK293 (3 loci testados), ROSA26 humano teve desempenho inferior ao AAVS1 em expressão e homogeneidade de eGFP.';
update public_safe_harbors_staging set evidence_summary = 'In the same direct comparative HEK293 study (3 loci tested), human ROSA26 underperformed AAVS1 in eGFP expression and homogeneity.', stability = 'Underperformed AAVS1 in the same study' where source_pmid = '32470292' and evidence_summary = 'No mesmo estudo comparativo direto em HEK293 (3 loci testados), ROSA26 humano teve desempenho inferior ao AAVS1 em expressão e homogeneidade de eGFP.';

update known_safe_harbors set locus_name = 'Chr1-eGSH', evidence_summary = 'Extragenic candidate locus on chromosome 1. Important cautionary finding: the locus itself allowed robust transgene expression, BUT a gene 2Mb away, within the same topologically associated domain (TAD), showed aberrant expression -- despite the distance, 3D TAD organization propagated the effect. The authors conclude Chr1-eGSH is not suitable for therapeutic gene integration despite the locus itself appearing good. Also tested with a suicide-gene safety system (HSV-TK/ganciclovir): sensitive in vitro, but resulting teratomas showed variable degrees of resistance in vivo -- the safety system itself is not reliably guaranteed.', stability = 'Locus itself stable, but distal TAD effect makes it unsuitable' where source_pmid = '30887735' and evidence_summary = 'Locus candidato extragénico no cromossoma 1. Achado importante e cautelar: o próprio locus permitiu expressão robusta do transgene, MAS um gene a 2Mb de distância, dentro do mesmo domínio topologicamente associado (TAD), mostrou expressão aberrante -- apesar da distância, a organização 3D do TAD propagou o efeito. Os autores concluem que Chr1-eGSH não é adequado para integração génica terapêutica apesar de o locus em si parecer bom. Também testado com sistema de segurança de gene suicida (HSV-TK/ganciclovir): sensível in vitro, mas teratomas resultantes mostraram graus variáveis de resistência in vivo -- o próprio sistema de segurança não é garantidamente fiável.';
update public_safe_harbors_staging set locus_name = 'Chr1-eGSH', evidence_summary = 'Extragenic candidate locus on chromosome 1. Important cautionary finding: the locus itself allowed robust transgene expression, BUT a gene 2Mb away, within the same topologically associated domain (TAD), showed aberrant expression -- despite the distance, 3D TAD organization propagated the effect. The authors conclude Chr1-eGSH is not suitable for therapeutic gene integration despite the locus itself appearing good. Also tested with a suicide-gene safety system (HSV-TK/ganciclovir): sensitive in vitro, but resulting teratomas showed variable degrees of resistance in vivo -- the safety system itself is not reliably guaranteed.', stability = 'Locus itself stable, but distal TAD effect makes it unsuitable' where source_pmid = '30887735' and evidence_summary = 'Locus candidato extragénico no cromossoma 1. Achado importante e cautelar: o próprio locus permitiu expressão robusta do transgene, MAS um gene a 2Mb de distância, dentro do mesmo domínio topologicamente associado (TAD), mostrou expressão aberrante -- apesar da distância, a organização 3D do TAD propagou o efeito. Os autores concluem que Chr1-eGSH não é adequado para integração génica terapêutica apesar de o locus em si parecer bom. Também testado com sistema de segurança de gene suicida (HSV-TK/ganciclovir): sensível in vitro, mas teratomas resultantes mostraram graus variáveis de resistência in vivo -- o próprio sistema de segurança não é garantidamente fiável.';

update known_safe_harbors set evidence_summary = 'Doxycycline-inducible Cas9 confirmed single-copy integrated at AAVS1, in iPSC derived from fetal liver B progenitors. Pluripotency maintained after editing. Robust, specific Cas9 expression after induction, functional gene editing confirmed by T7 endonuclease assay.', stability = 'Pluripotency maintained after editing (duration not further quantified)' where source_pmid = '28677529' and evidence_summary = 'Cas9 indutível por doxiciclina integrado em cópia única confirmada em AAVS1, em iPSC derivada de progenitores B de fígado fetal. Pluripotência mantida após edição. Expressão robusta e específica de Cas9 após indução, edição génica funcional confirmada por ensaio T7-endonuclease.';
update public_safe_harbors_staging set evidence_summary = 'Doxycycline-inducible Cas9 confirmed single-copy integrated at AAVS1, in iPSC derived from fetal liver B progenitors. Pluripotency maintained after editing. Robust, specific Cas9 expression after induction, functional gene editing confirmed by T7 endonuclease assay.', stability = 'Pluripotency maintained after editing (duration not further quantified)' where source_pmid = '28677529' and evidence_summary = 'Cas9 indutível por doxiciclina integrado em cópia única confirmada em AAVS1, em iPSC derivada de progenitores B de fígado fetal. Pluripotência mantida após edição. Expressão robusta e específica de Cas9 após indução, edição génica funcional confirmada por ensaio T7-endonuclease.';

update known_safe_harbors set evidence_summary = 'ZFN study at CCR5 and AAVS1: careful cassette design allows robust transgene expression without detectable transcriptional disruption of the target locus or flanking genes, demonstrated across several cell types including primary human lymphocytes.', stability = 'No detectable transcriptional disruption (duration not further quantified)' where source_pmid = '21857672' and evidence_summary = 'Estudo com ZFN em CCR5 e AAVS1: desenho cuidadoso de cassete permite expressão robusta do transgene sem perturbação transcricional detetável do locus-alvo nem dos genes flanqueadores, demonstrado em vários tipos celulares incluindo linfócitos humanos primários.';
update public_safe_harbors_staging set evidence_summary = 'ZFN study at CCR5 and AAVS1: careful cassette design allows robust transgene expression without detectable transcriptional disruption of the target locus or flanking genes, demonstrated across several cell types including primary human lymphocytes.', stability = 'No detectable transcriptional disruption (duration not further quantified)' where source_pmid = '21857672' and evidence_summary = 'Estudo com ZFN em CCR5 e AAVS1: desenho cuidadoso de cassete permite expressão robusta do transgene sem perturbação transcricional detetável do locus-alvo nem dos genes flanqueadores, demonstrado em vários tipos celulares incluindo linfócitos humanos primários.';

update known_safe_harbors set evidence_summary = 'Same study: CCR5 also showed robust expression without detectable transcriptional disruption of the locus or flanking genes, using the same careful cassette design, in primary human lymphocytes.', stability = 'No detectable transcriptional disruption (duration not further quantified)' where source_pmid = '21857672' and evidence_summary = 'Mesmo estudo: CCR5 também mostrou expressão robusta sem perturbação transcricional detetável do locus ou genes flanqueadores, usando o mesmo desenho de cassete cuidadoso, em linfócitos humanos primários.';
update public_safe_harbors_staging set evidence_summary = 'Same study: CCR5 also showed robust expression without detectable transcriptional disruption of the locus or flanking genes, using the same careful cassette design, in primary human lymphocytes.', stability = 'No detectable transcriptional disruption (duration not further quantified)' where source_pmid = '21857672' and evidence_summary = 'Mesmo estudo: CCR5 também mostrou expressão robusta sem perturbação transcricional detetável do locus ou genes flanqueadores, usando o mesmo desenho de cassete cuidadoso, em linfócitos humanos primários.';

update known_safe_harbors set evidence_summary = 'Founding paper (2010): ZFN targets PPP1R12C (AAVS1) without drug selection, transgenesis efficiency up to 15% in transient transfection, in transformed AND primary cells (fibroblasts, hES). Transgenes (shRNA, small-molecule-responsive cassettes, reporters) show consistent expression and sustained function for over 50 cell generations -- classic reference for "AAVS1 holds up over many generations".', stability = 'Sustained function for >50 cell generations' where source_pmid = '20508142' and evidence_summary = 'Paper fundador (2010): ZFN alveja PPP1R12C (AAVS1) sem seleção por fármaco, eficiência de transgénese até 15% em transfeção transitória, em células transformadas E primárias (fibroblastos, hES). Transgenes (shRNA, cassetes responsivas a pequenas moléculas, repórteres) mostram expressão consistente e função sustentada por mais de 50 gerações celulares -- referência clássica para "AAVS1 aguenta muitas gerações".';
update public_safe_harbors_staging set evidence_summary = 'Founding paper (2010): ZFN targets PPP1R12C (AAVS1) without drug selection, transgenesis efficiency up to 15% in transient transfection, in transformed AND primary cells (fibroblasts, hES). Transgenes (shRNA, small-molecule-responsive cassettes, reporters) show consistent expression and sustained function for over 50 cell generations -- classic reference for "AAVS1 holds up over many generations".', stability = 'Sustained function for >50 cell generations' where source_pmid = '20508142' and evidence_summary = 'Paper fundador (2010): ZFN alveja PPP1R12C (AAVS1) sem seleção por fármaco, eficiência de transgénese até 15% em transfeção transitória, em células transformadas E primárias (fibroblastos, hES). Transgenes (shRNA, cassetes responsivas a pequenas moléculas, repórteres) mostram expressão consistente e função sustentada por mais de 50 gerações celulares -- referência clássica para "AAVS1 aguenta muitas gerações".';

update known_safe_harbors set evidence_summary = 'Human HPRT locus (KhES-1 hES line) targeted via homologous recombination + Cre-recombinase site-specific integration. Tetracycline/doxycycline-responsive inducible reporter system, with self-renewal and pluripotency maintained. Confirms in human the same type of locus already validated in mouse (Hprt1) in earlier batches.', stability = 'Self-renewal and pluripotency maintained (duration not further quantified)' where source_pmid = '20071742' and evidence_summary = 'Locus HPRT humano (linha hES KhES-1) alvejado por recombinação homóloga + integração sítio-específica por recombinase Cre. Sistema repórter indutível por tetraciclina responsivo a doxiciclina, com auto-renovação e pluripotência mantidas. Confirma em humano o mesmo tipo de locus já validado em ratinho (Hprt1) nos lotes anteriores.';
update public_safe_harbors_staging set evidence_summary = 'Human HPRT locus (KhES-1 hES line) targeted via homologous recombination + Cre-recombinase site-specific integration. Tetracycline/doxycycline-responsive inducible reporter system, with self-renewal and pluripotency maintained. Confirms in human the same type of locus already validated in mouse (Hprt1) in earlier batches.', stability = 'Self-renewal and pluripotency maintained (duration not further quantified)' where source_pmid = '20071742' and evidence_summary = 'Locus HPRT humano (linha hES KhES-1) alvejado por recombinação homóloga + integração sítio-específica por recombinase Cre. Sistema repórter indutível por tetraciclina responsivo a doxiciclina, com auto-renovação e pluripotência mantidas. Confirma em humano o mesmo tipo de locus já validado em ratinho (Hprt1) nos lotes anteriores.';

-- ===== batch 9 =====
update known_safe_harbors set evidence_summary = 'Voltage indicator (VSFP, FRET) under the CAG promoter stably expressed at AAVS1 in hiPSC-CM (cardiomyocytes). Functionally validated in ventricular, atrial, and nodal subtypes, in 2D monolayers and in 3D context, with high-throughput optical action-potential recordings.', stability = 'Stable expression validated across cardiomyocyte subtypes' where source_pmid = '36274846' and evidence_summary = 'Indicador de voltagem (VSFP, FRET) sob promotor CAG estavelmente expresso em AAVS1 em hiPSC-CM (cardiomiócitos). Validado funcionalmente em subtipos ventricular, atrial e nodal, em monocamadas 2D e em contexto 3D, com gravações óticas de potencial de ação de alto rendimento.';
update public_safe_harbors_staging set evidence_summary = 'Voltage indicator (VSFP, FRET) under the CAG promoter stably expressed at AAVS1 in hiPSC-CM (cardiomyocytes). Functionally validated in ventricular, atrial, and nodal subtypes, in 2D monolayers and in 3D context, with high-throughput optical action-potential recordings.', stability = 'Stable expression validated across cardiomyocyte subtypes' where source_pmid = '36274846' and evidence_summary = 'Indicador de voltagem (VSFP, FRET) sob promotor CAG estavelmente expresso em AAVS1 em hiPSC-CM (cardiomiócitos). Validado funcionalmente em subtipos ventricular, atrial e nodal, em monocamadas 2D e em contexto 3D, com gravações óticas de potencial de ação de alto rendimento.';

update known_safe_harbors set evidence_summary = 'Genetically encoded fluorescent biosensors (GEFBs) inserted at AAVS1 via CRISPR/Cas HDR, with puromycin selection and negligible off-target editing. Biosensor expression maintained through differentiation into multiple lineages.', stability = 'Maintained through multi-lineage differentiation' where source_pmid = '34505269' and evidence_summary = 'Biossensores fluorescentes geneticamente codificados (GEFBs) inseridos em AAVS1 via CRISPR/Cas HDR, com seleção por puromicina e edição off-target negligenciável. Expressão do biossensor mantida ao longo de diferenciação em múltiplas linhagens.';
update public_safe_harbors_staging set evidence_summary = 'Genetically encoded fluorescent biosensors (GEFBs) inserted at AAVS1 via CRISPR/Cas HDR, with puromycin selection and negligible off-target editing. Biosensor expression maintained through differentiation into multiple lineages.', stability = 'Maintained through multi-lineage differentiation' where source_pmid = '34505269' and evidence_summary = 'Biossensores fluorescentes geneticamente codificados (GEFBs) inseridos em AAVS1 via CRISPR/Cas HDR, com seleção por puromicina e edição off-target negligenciável. Expressão do biossensor mantida ao longo de diferenciação em múltiplas linhagens.';

update known_safe_harbors set evidence_summary = 'Therapeutic AGXT minigene (for primary hyperoxaluria type 1) inserted at AAVS1 in patient iPSC, with no off-target insertions. Robust expression of the (codon-optimized) AGT enzyme confirmed in derived hepatocyte-like cells -- proof of concept for functional correction.', stability = 'Robust expression confirmed in differentiated hepatocyte-like cells' where source_pmid = '31402115' and evidence_summary = 'Minigene AGXT terapêutico (para hiperoxalúria primária tipo 1) inserido em AAVS1 em iPSC de doente, sem inserções off-target. Expressão robusta da enzima AGT (codão-otimizada) confirmada em derivados hepatócito-like -- prova de conceito de correção funcional.';
update public_safe_harbors_staging set evidence_summary = 'Therapeutic AGXT minigene (for primary hyperoxaluria type 1) inserted at AAVS1 in patient iPSC, with no off-target insertions. Robust expression of the (codon-optimized) AGT enzyme confirmed in derived hepatocyte-like cells -- proof of concept for functional correction.', stability = 'Robust expression confirmed in differentiated hepatocyte-like cells' where source_pmid = '31402115' and evidence_summary = 'Minigene AGXT terapêutico (para hiperoxalúria primária tipo 1) inserido em AAVS1 em iPSC de doente, sem inserções off-target. Expressão robusta da enzima AGT (codão-otimizada) confirmada em derivados hepatócito-like -- prova de conceito de correção funcional.';

update known_safe_harbors set evidence_summary = 'Lysosomal iduronidase enzyme (deficient in Mucopolysaccharidosis type I) targeted to CCR5 in human CD34+ hematopoietic stem cells. Enzyme secretion above normal endogenous level, long-term repopulation capacity and multi-lineage differentiation maintained, improvement of biochemical/phenotypic abnormalities in an immunocompromised mouse model of the disease.', stability = 'Long-term repopulation capacity maintained in vivo' where source_pmid = '31492863' and evidence_summary = 'Enzima lisossomal iduronidase (défice na Mucopolissacaridose tipo I) alvejada a CCR5 em células estaminais hematopoiéticas CD34+ humanas. Secreção de enzima acima do nível endógeno normal, capacidade de repovoamento a longo prazo e diferenciação multi-linhagem mantida, melhoria de anomalias bioquímicas/fenotípicas em modelo murino imunocomprometido da doença.';
update public_safe_harbors_staging set evidence_summary = 'Lysosomal iduronidase enzyme (deficient in Mucopolysaccharidosis type I) targeted to CCR5 in human CD34+ hematopoietic stem cells. Enzyme secretion above normal endogenous level, long-term repopulation capacity and multi-lineage differentiation maintained, improvement of biochemical/phenotypic abnormalities in an immunocompromised mouse model of the disease.', stability = 'Long-term repopulation capacity maintained in vivo' where source_pmid = '31492863' and evidence_summary = 'Enzima lisossomal iduronidase (défice na Mucopolissacaridose tipo I) alvejada a CCR5 em células estaminais hematopoiéticas CD34+ humanas. Secreção de enzima acima do nível endógeno normal, capacidade de repovoamento a longo prazo e diferenciação multi-linhagem mantida, melhoria de anomalias bioquímicas/fenotípicas em modelo murino imunocomprometido da doença.';

update known_safe_harbors set evidence_summary = 'Full-length F9 cDNA (factor IX) inserted at AAVS1 in iPSC from a hemophilia B patient. No off-target mutations detected by whole-genome sequencing. Derived hepatocytes stably secreted hFIX and survived short-term transplant in NOD/SCID mice.', stability = 'Stable secretion through short-term transplant survival' where source_pmid = '29625575' and evidence_summary = 'cDNA F9 completo (fator IX) inserido em AAVS1 em iPSC de doente com hemofilia B. Sem mutações off-target detetadas por sequenciação do genoma completo. Hepatócitos derivados secretaram hFIX de forma estável e sobreviveram a transplante de curto prazo em ratinhos NOD/SCID.';
update public_safe_harbors_staging set evidence_summary = 'Full-length F9 cDNA (factor IX) inserted at AAVS1 in iPSC from a hemophilia B patient. No off-target mutations detected by whole-genome sequencing. Derived hepatocytes stably secreted hFIX and survived short-term transplant in NOD/SCID mice.', stability = 'Stable secretion through short-term transplant survival' where source_pmid = '29625575' and evidence_summary = 'cDNA F9 completo (fator IX) inserido em AAVS1 em iPSC de doente com hemofilia B. Sem mutações off-target detetadas por sequenciação do genoma completo. Hepatócitos derivados secretaram hFIX de forma estável e sobreviveram a transplante de curto prazo em ratinhos NOD/SCID.';

update known_safe_harbors set evidence_summary = 'hFIX inserted at AAVS1 in human mesenchymal stem cells (MSCs) -- a novel cell context compared to other records. Stem cell traits maintained after integration; hFIX effectively expressed in vivo and in vitro, with no significant expression differences between individual clones.', stability = 'Stable, consistent expression across clones' where source_pmid = '28112377' and evidence_summary = 'hFIX inserido em AAVS1 em células estaminais mesenquimais (MSC) humanas -- contexto celular novo face aos restantes registos. Traços de célula estaminal mantidos após integração; hFIX expresso eficazmente in vivo e in vitro, sem diferenças significativas de expressão entre clones individuais.';
update public_safe_harbors_staging set evidence_summary = 'hFIX inserted at AAVS1 in human mesenchymal stem cells (MSCs) -- a novel cell context compared to other records. Stem cell traits maintained after integration; hFIX effectively expressed in vivo and in vitro, with no significant expression differences between individual clones.', stability = 'Stable, consistent expression across clones' where source_pmid = '28112377' and evidence_summary = 'hFIX inserido em AAVS1 em células estaminais mesenquimais (MSC) humanas -- contexto celular novo face aos restantes registos. Traços de célula estaminal mantidos após integração; hFIX expresso eficazmente in vivo e in vitro, sem diferenças significativas de expressão entre clones individuais.';

update known_safe_harbors set evidence_summary = 'Targeted integration in human CD34+ HSPCs: up to 58% Venus+ cells with 6-16% human cell engraftment marking in mice. In HSPCs from X-linked chronic granulomatous disease patients, gp91phox transgene at AAVS1 gave ~15% expression and increased NADPH oxidase activity in neutrophils ex vivo; in transplanted mice, 4-11% of human cells in bone marrow expressed gp91phox -- moderate but carefully quantified efficiency.', stability = 'Detectable engraftment and expression in vivo (moderate efficiency)' where source_pmid = '26950749' and evidence_summary = 'Integração alvejada em CD34+ HSPCs humanas: até 58% de células Venus+ com 6-16% de marcação de células humanas após enxerto em ratinhos. Em HSPCs de doentes com doença granulomatosa crónica ligada ao X, transgene gp91phox em AAVS1 deu ~15% de expressão e atividade NADPH oxidase aumentada em neutrófilos ex vivo; em ratinhos transplantados, 4-11% das células humanas na medula óssea expressaram gp91phox -- eficiência moderada mas quantificada em detalhe.';
update public_safe_harbors_staging set evidence_summary = 'Targeted integration in human CD34+ HSPCs: up to 58% Venus+ cells with 6-16% human cell engraftment marking in mice. In HSPCs from X-linked chronic granulomatous disease patients, gp91phox transgene at AAVS1 gave ~15% expression and increased NADPH oxidase activity in neutrophils ex vivo; in transplanted mice, 4-11% of human cells in bone marrow expressed gp91phox -- moderate but carefully quantified efficiency.', stability = 'Detectable engraftment and expression in vivo (moderate efficiency)' where source_pmid = '26950749' and evidence_summary = 'Integração alvejada em CD34+ HSPCs humanas: até 58% de células Venus+ com 6-16% de marcação de células humanas após enxerto em ratinhos. Em HSPCs de doentes com doença granulomatosa crónica ligada ao X, transgene gp91phox em AAVS1 deu ~15% de expressão e atividade NADPH oxidase aumentada em neutrófilos ex vivo; em ratinhos transplantados, 4-11% das células humanas na medula óssea expressaram gp91phox -- eficiência moderada mas quantificada em detalhe.';

update known_safe_harbors set evidence_summary = 'Founding paper (2009): transgene inserted at AAVS1 in hESC to create a robust, drug-inducible overexpression system -- one of the first documented uses of AAVS1 for this purpose, alongside OCT4 and PITX3 reporters (target genes, not safe harbors).', stability = 'Robust, inducible system (duration not further quantified)' where source_pmid = '19680244' and evidence_summary = 'Paper fundador (2009): transgene inserido em AAVS1 em hESC para criar sistema de sobre-expressão robusto e indutível por fármaco -- um dos primeiros usos documentados de AAVS1 com este propósito, ao lado de repórteres OCT4 e PITX3 (genes-alvo, não safe harbors).';
update public_safe_harbors_staging set evidence_summary = 'Founding paper (2009): transgene inserted at AAVS1 in hESC to create a robust, drug-inducible overexpression system -- one of the first documented uses of AAVS1 for this purpose, alongside OCT4 and PITX3 reporters (target genes, not safe harbors).', stability = 'Robust, inducible system (duration not further quantified)' where source_pmid = '19680244' and evidence_summary = 'Paper fundador (2009): transgene inserido em AAVS1 em hESC para criar sistema de sobre-expressão robusto e indutível por fármaco -- um dos primeiros usos documentados de AAVS1 com este propósito, ao lado de repórteres OCT4 e PITX3 (genes-alvo, não safe harbors).';

update known_safe_harbors set locus_name = 'Pseudo-attP sites (phiC31 integrase)', evidence_summary = 'A different locus category from AAVS1/ROSA26: endogenous pseudo-attP sites targeted by phiC31 integrase in hESC (not a single named locus, a hotspot profile). GFP under the Oct4 promoter tracked endogenous Oct4 expression (expected, responds to differentiation); GFP under the EF1alpha promoter gave stable, persistent expression. Clones retained differentiation capacity into all 3 germ layers.', stability = 'Stable/persistent under EF1alpha; expected downregulation under Oct4 promoter' where source_pmid = '17962703' and evidence_summary = 'Categoria de locus diferente de AAVS1/ROSA26: sítios pseudo-attP endógenos alvejados pela integrase phiC31 em hESC (não um locus único nomeado, um perfil de pontos quentes de integração). GFP sob promotor Oct4 acompanhou a expressão endógena de Oct4 (esperado, responde a diferenciação); GFP sob promotor EF1alpha deu expressão estável e persistente. Clones mantiveram capacidade de diferenciação nas 3 camadas germinativas.';
update public_safe_harbors_staging set locus_name = 'Pseudo-attP sites (phiC31 integrase)', evidence_summary = 'A different locus category from AAVS1/ROSA26: endogenous pseudo-attP sites targeted by phiC31 integrase in hESC (not a single named locus, a hotspot profile). GFP under the Oct4 promoter tracked endogenous Oct4 expression (expected, responds to differentiation); GFP under the EF1alpha promoter gave stable, persistent expression. Clones retained differentiation capacity into all 3 germ layers.', stability = 'Stable/persistent under EF1alpha; expected downregulation under Oct4 promoter' where source_pmid = '17962703' and evidence_summary = 'Categoria de locus diferente de AAVS1/ROSA26: sítios pseudo-attP endógenos alvejados pela integrase phiC31 em hESC (não um locus único nomeado, um perfil de pontos quentes de integração). GFP sob promotor Oct4 acompanhou a expressão endógena de Oct4 (esperado, responde a diferenciação); GFP sob promotor EF1alpha deu expressão estável e persistente. Clones mantiveram capacidade de diferenciação nas 3 camadas germinativas.';

-- (batches 8-9 complete -- 12+9 = 21/21 records)
